### ISSUE TITLE
Usage in RoR

### ISSUE THREAD

**Issue by vmamaev** [jquense/react-big-calendar#1]
Hello could you advice me how to use this component in Ruby on rails? 

needs compiled source...

**Comment by jquense** [comment]
Hi there. I don't really know anything about the rails pipeline so I can't really speak to it but the npm package has compiled code in it, can you use that?

**Comment by macejmic** [comment]
@vmamaev 

You need to add Gem "browserify-rails" and package.json file to your root directory. Then run npm install in your terminal which creates node_modules directory in your root directory as well.

The last thing is just config for this calendar component:

```
BigCalendar = require('react-big-calendar');
moment      = require('moment');

BigCalendar.setLocalizer(
  BigCalendar.momentLocalizer(moment)
);
```

And from that moment you're able to use <BigCalendar /> component in your ROR project.

**Comment by jquense** [comment]
thanks!

**Comment by varun-raj** [comment]
This could help you. https://blog.skcript.com/setting-up-browserify-and-react-on-rails-ef5bc0f07cda#.de7s1dn22

**Comment by fergyfresh** [comment]
Where do you have to put the config you mentioned above  @macejmic?
