### ISSUE TITLE
dynamically change the height of time slot 

### ISSUE THREAD

**Issue by mikeyyyzhao** [jquense/react-big-calendar#1471]
#### Do you want to request a _feature_ or report a _bug_?
Feature

#### What's the current behavior?
Currently, in order to change the height of timeslot, you have to change it in the css through .rbc-timeslot-group. However, if you're trying to dynamically change the height of the slot, say to let users see more hours of the day or less hours of the day, it's not possible. I've looked into timeSlotWrapper in components but that seems to only change the height of the lines within the timeslot and not the entire timeslot itself. 

#### What's the expected behavior?
We can dynamically set the height of timeslot (similar to how you can set it in rbc-timeslot-group) either through giving us a class name selector or something else.

**Comment by emilienh** [comment]
Trying to do this as well, but no luck.

**Comment by emilienh** [comment]
Opened a PR to address this:
https://github.com/intljusticemission/react-big-calendar/pull/1509

**Comment by emilienh** [comment]
Opened a PR to address this: https://github.com/intljusticemission/react-big-calendar/pull/1510

**Comment by emilienh** [comment]
Please look into the PR, it's an easy fix and it's extremely useful

**Comment by schester44** [comment]
You can also accomplish changing the height of time slot groups by adding a CSS class to the parent element of the <Calendar />

```
<div className={`calendar-zoom-${someDynamicZoomLevel}`}>
  <Calendar />
</div>
```

then in your CSS: 

```
.calendar-zoom-<level> .rbc-timeslot-group {
   
}
```


at least, thats how i've accomplished it in the past. An all JS solution may be cleaner though, I will check it out. thanks for the PR!
