### ISSUE TITLE
Receiving Multiple Console Warnings

### ISSUE THREAD

**Issue by AngeloAnolin** [jquense/react-big-calendar#1481]
#### Do you want to request a _feature_ or report a _bug_?
Reporting a Bug

#### What's the current behavior?
In the Console, there's a lot of warnings saying something like:

```
Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Uncontrolled(Calendar)

```

#### What's the expected behavior?
No console warnings related to the prescribed method by Facebook.

#### Code Sample

1. See this example: [Big Calendar Demo](https://stackblitz.com/edit/big-calendar-demo)
2. Modify the dependencies. Remove react-big-calendar and add again. Notice that the version number changes (From 0.22.0 to 0.22.1)
3. In the browser emulator, expand the console panel. Notice the warnings generated.

**Comment by rever96** [comment]
Don't stale it. theese warning has to be fixed

**Comment by kiril-daskalov** [comment]
UP!
