### ISSUE TITLE
Bug - Drag&Drop resizes events

### ISSUE THREAD

**Issue by Uhel** [jquense/react-big-calendar#1496]
# Bug - Drag&Drop resizes events
- When dragging an event sometimes it resizes. It happens in two latest versions (`0.22.1`, `0.22.0`). 
- It works fine in version `0.21.0`, but it uses old unsave lifecycle methods componentWillReceiveProps and componentWillMount which without `UNSAFE_` prefix won't work in React version 17.
- Can you please fix this bug?

![react-big-calendar-bug](https://user-images.githubusercontent.com/23128633/66733099-bb67f680-ee5e-11e9-8414-b369f9c4c235.gif)
- I cloned the component's repozitory and run it ([link](https://github.com/intljusticemission/react-big-calendar)). But it doesn't work either in my testing project.
- version: 0.22.1
- Opera, Chrome, Mozilla Firefox on Ubuntu Budgie

**Comment by mustafahlvc** [comment]
There is a workaround for the resize issue from: 
https://github.com/intljusticemission/react-big-calendar/issues/1387#issuecomment-531465438

You add the the specific version in the resolutions of the package.json:
```js
 "resolutions": {
        "date-arithmetic": "3.1.0"
  },
```

**Comment by Uhel** [comment]
It works!!! :tada: :tada: :tada: 
Thank you very much! :+1:

**Comment by rever96** [comment]
That's still not fixed, every import of react-big-calendar is using ^4.0.1 version of date-arithmetic.
Changing it manually to 3.1.0 on package-lock.json doesn't help, either add `"resolutions": {
        "date-arithmetic": "3.1.0"
  },` to package.json doesn't help

**Comment by darkcattz** [comment]
Hello, 

Is this problem resolved? Can we remove the dependency on "date-arithmetic": "3.1.0"

Thanks

**Comment by darkcattz** [comment]
[https://github.com/jquense/date-math/issues/18](https://github.com/jquense/date-math/issues/18)
