### ISSUE TITLE
Calendar is not working on internet explorer 11

### ISSUE THREAD

**Issue by tugii** [jquense/react-big-calendar#1525]
_bug_

#### What's the current behavior?

Hi guys, 

On IE11 is the calendar not working. I just opened the [Demo Page](http://intljusticemission.github.io/react-big-calendar/examples/index.html) on IE11.

#### What's the expected behavior?

That the calendar is working also on IE11.

**Comment by jquense** [comment]
TBH i don't have to support IE11 so tracking down places where it doesn't work isn't a super high priority. If you could provide more context or specifically waht is not working there is a much higher chance it'll get fixed :)

**Comment by mrluc** [comment]
The demo page doesn't work for me either in IE11 on browserstack, can confirm -- however I'm using it in a project and just checked IE11 via browserstack, and it renders -- it just has a bug where you need to hover before it will get laid out correctly!

Ie all of the 'calendar events' that get laid out start off squished over to the left in about a 20px column on first view, or when changing day/month/etc view, but then when I hover over any element, it apparently recalculates.

I'm just leaving this for others who may be searching for 'IE11'.

And this makes me think that maybe the solution to my problem is forcing a recalculate somehow. I wonder if there's an api to do that, to nudge the calendar and say "ok, *now* try to lay out again".

**Comment by mrluc** [comment]
Update: from looking at what things would cause it to re-layout on IE, I ended up with an IE11-specific hack that's gross, but might work (for that project at least) until IE11 dies:

```javascript
const nudge = () => {
  document.querySelector('.rbc-FOO').style.paddingRight = '0px';
}

useEffect(() => {
  isIE11 && setTimeout(nudge, 10)
}, [date, view])
```

Didn't dig into the underlying IE11 syntax error in the demo though.

**Comment by azsuth** [comment]
I am getting the error `Object doesn't support the property or method 'closest'`. There is a suggested polyfill to fix it on [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Element/closest).

```
if (window.Element && !Element.prototype.closest) {
  Element.prototype.closest =
  function(s) {
    var matches = (this.document || this.ownerDocument).querySelectorAll(s),
        i,
        el = this;
    do {
      i = matches.length;
      while (--i >= 0 && matches.item(i) !== el) {};
    } while ((i < 0) && (el = el.parentElement));
    return el;
  };
}
```

**Comment by martin-strobel** [comment]
hello,
I recently found the same issue.

> The demo page doesn't work for me either in IE11 on browserstack, can confirm -- however I'm using it in a project and just checked IE11 via browserstack, and it renders -- it just has a bug where you need to hover before it will get laid out correctly!

I tracked down the problem and found the source: https://github.com/intljusticemission/react-big-calendar/blob/77004e2a51dfa466341e14d2dab35466822d0efb/src/TimeGrid.js#L73

**Comment by IndProgo** [comment]
To get Calendar work on IE11, in addition to 'element-closest' polyfill, I also added css rules, specific for ie11
```css
@media all and (-ms-high-contrast: none), (-ms-high-contrast: active) {
  .rbc-date-cell,
  .rbc-month-row {
    flex-basis: 100%;
  }
  .rbc-day-slot {
    flex: 1 1;
  }
}
```

**Comment by jazeee** [comment]
Neither `.rbc-date-cell` nor `.rbc-month-row` are in our code, and adding `flex: 1 1` to `.rbc-day-slot` didn't seem to help.

I was able to fix my calendar by adding `min-height: 500px` to `.rbc-time-view` class.

**Comment by cutterbl** [comment]
Big Calendar does not support IE.
