### ISSUE TITLE
popup = {false} brings up day view

### ISSUE THREAD

**Issue by dcmodie** [jquense/react-big-calendar#1527]
Report a bug

When you set popup = {false}, it goes to the day view.  I don't want that, I have my own pop up and I want the view to remain in the same place.  

Expected behavior:
popup = {false}, simply turns off the baked-in '+more' modal.  Going to the day view should be independent, with its own boolean. Why are these two things intertwined?

**Comment by antondomratchev** [comment]
Use `onSelectEvent` or `onSelectSlot` to trigger your own popup render. Don't include the popup prop in the Calendar component at all.

**Comment by dcmodie** [comment]
I am trying to use my own modal for the '+more' click.  I don't want to use the baked-in modal for it.  The callbacks you mentioned are for an event, and a day, respectively.

**Comment by paulhuisman** [comment]
@dcmodie How did you solve this?

**Comment by dcmodie** [comment]
I could only hack.  I found the baked-in modal element, and set display:none.  Can't remember if I did it after the component was loaded or in the css file.  Probably the latter.  I don't have access to the code.  Anyway, it worked.
