### ISSUE TITLE
Events are incorrectly placed when their duration is less than step

### ISSUE THREAD

**Issue by tobiasandersen** [jquense/react-big-calendar#1529]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?
Events are incorrectly placed when their duration is less than the `step` property. In the image below you can see that the event starts at 16.00, but it's placed at the 15-16 slot (rather than on the 16-17 slot). You can see the behavior in this [CodeSandbox](https://codesandbox.io/s/wizardly-davinci-h3253) as well. 

![image](https://user-images.githubusercontent.com/3599069/69068021-5c306f80-0a24-11ea-822a-e519e2dc3584.png)

This was bug introduced by https://github.com/intljusticemission/react-big-calendar/pull/1204. I can see that @TrySound tried to fix it first by reverting the behavior added by the PR above with https://github.com/intljusticemission/react-big-calendar/commit/17b6cfdf7c71e6b9117e9d552231ab17f8ff081c but then added it back (with some adjustments) with https://github.com/intljusticemission/react-big-calendar/commit/02c289245a403f40e1c98095c87b58d83a9c32a0.

**Comment by Npervic** [comment]
I am experiencing the same problem. I wrote about it in this PR #1462 .

**Comment by marwej** [comment]
Same issue here. Also a case where duration is longer than `step` but start time is not "on step".

![image](https://user-images.githubusercontent.com/5296840/73543973-66b1b100-4438-11ea-9c00-b8b3b3ba92c1.png)

**Comment by marwej** [comment]
I changed `step` to 15, but the last event was still placed incorrectly.

![image](https://user-images.githubusercontent.com/5296840/73544200-f0fa1500-4438-11ea-9c68-d09cae12248b.png)

**Comment by tobiasandersen** [comment]
For me this was fixed with https://github.com/jquense/react-big-calendar/pull/1462.
