### ISSUE TITLE
Revisit the PR for date-fns localizer

### ISSUE THREAD

**Issue by harel** [jquense/react-big-calendar#1541]
#### Do you want to request a _feature_ or report a _bug_?

A now closed issue and PR dealt with adding date-fns as a localizer. It was determined to wait until date-fns has reached 2.0 release which has now happened a while ago. 

Original Issue: https://github.com/intljusticemission/react-big-calendar/issues/816
Original PR: https://github.com/intljusticemission/react-big-calendar/pull/855

Would it be possible to revisit the PR now that date-fns is released?

New PR for consideration: https://github.com/intljusticemission/react-big-calendar/pull/1542

**Comment by harel** [comment]
Alternatively, because the DateLocalizer is now exported, it is possible to decouple the localizers completely  from the Calendar code. I'm currently running the localizer in the PR I posted in my app code as a utility and use it to init the calendar instead of having  a built in version. This can allow localizers to be separate packages or utilities if this becomes the norm.

**Comment by aureooms** [comment]
Can this issue be closed now that #1542 has been merged?

**Comment by harel** [comment]
fine with me :)
