### ISSUE TITLE
Help on creating a custom agenda view

### ISSUE THREAD

**Issue by paulhuisman** [jquense/react-big-calendar#1544]
Hi guys,

First of, great work on the plugin! I really like it.

I was wondering if you could explain me how to make a custom agenda view. I'd like to add a few extra columns to the table. From another ticket i gathered that there is no hook and a custom view is necessery. 

However i don't know how to do that.. sooo if you could point me into the right direction that'd be great!

Cheers

**Comment by ntelkedzhiev** [comment]
Same question here.

**Comment by gkrinc** [comment]
Looking at the source code that doesn't appear to be possible at the moment. So it seems the only way to really do this would be to fork this repo, which kinda sucks :(

**Comment by cutterbl** [comment]
RBC is (currently) written completely with the older style class components. There aren't (currently) any hooks in the code, and though you'll see a `CalendarContext.js` file, it doesn't appear to be used. All of that aside, what you're asking for does appear to be possible...

You can replace any `View` in RBC by providing _your own_ custom view. Basic steps for a custom `Agenda` view:

- copy `Agenda.js` from RBC source
- adjust to create _your_ layout
- make sure all of it's methods are still accessible
- apply that to your Calendar config

```
<Calendar
  components={{
    agenda: MyAgenda
  }}
  />
```
There is a [Custom View Example](https://github.com/jquense/react-big-calendar/blob/master/examples/demos/customView.js) in the [doc site](http://jquense.github.io/react-big-calendar/examples/index.html#customView) (this one for the Week `View`). I haven't tried this myself yet, but it may be possible to write your own as a function component (not seeing anything, initially, that would prevent it). You do appear to be limited to what you can access (the props RBC passes in). I'd suggest firing up a CodeSandbox and just play with it.

**Comment by paulhuisman** [comment]
Hey @cutterbl 

I tried implementing a custom agenda (list) view based on your [Custom View example](https://github.com/jquense/react-big-calendar/blob/master/examples/demos/customView.js).

However, i did not manage to get it to work (yet). Maybe you see what's wrong.. Here's my code:

**CustomAgenda.jsx**
```
import React, { Component, useState, useRef }  from 'react'
import ReactDOM, {render} from "react-dom";

class CustomAgenda extends React.Component {
  render() {
    let { date } = this.props
    let range = CustomAgenda.range(date)

    return (
      <React.Fragment>
        <>
          <h2>TEST</h2>
          <table className="table"></table>
        </>
      </React.Fragment>
    );
  }
}

CustomAgenda.range = date => {
  let start = date
  let end = dates.add(start, 2, 'day')

  let current = start
  let range = []

  while (dates.lte(current, end, 'day')) {
    range.push(current)
    current = dates.add(current, 1, 'day')
  }

  return range
}

CustomAgenda.navigate = (date, action) => {
  switch (action) {
    case Navigate.PREVIOUS:
      return dates.add(date, -3, 'day')

    case Navigate.NEXT:
      return dates.add(date, 3, 'day')

    default:
      return date
  }
}

CustomAgenda.title = date => {
  return `My awesome week: ${date.toLocaleDateString()}`
}
```

**EventCalendar.jsx**
```
<Calendar
          popup
          selectable
          date={this.state.calendarDate}
          onNavigate={this.handleNavigate}
          onView={this.handleView}
          messages={messages}
          formats={formats} 
          localizer={localizer}
          showMultiDayTimes={true}
          scrollToTime={new Date(1970, 1, 1, 8)}
          defaultView={this.state.calendarView}
          events={this.state.events}
          onSelectEvent={this.onSelectEvent}
          onSelectSlot={this.handleSelect}
          eventPropGetter={this.customEventPropGetter}
          components={{
            event: this.formatEvent,
            agenda: CustomAgenda
          }}
        />
```

It shows the 'normal' agenda list view when using this code.

**Comment by cutterbl** [comment]
I've never done a custom Agenda view, though I know it can be done. I would start by copying the current Agenda view and making your own adustments.

**Comment by michaelhayman** [comment]
To anyone else coming here trying to debug things - 

1) it's not `components` prop, it's the `view` prop.  
2) you need to return true if you want to use the default view for 'other' views, otherwise you'll get a confusing error about `title`.

```
<Calendar
  views={{
    week: true,
    month: true,
    day: true,
    agenda: MyCustomAgendaComponent
  }}
  ...
/>
```

After that, you can use the custom view linked above (even the week view renders when passed in as a value to the agenda key, as a starting point), or copy the library's agenda component and use that instead, both work with `0.26.0`.

**Comment by cutterbl** [comment]
Thanks @michaelhayman, nice catch. Definite fat finger here. What I get for answering questions on two separate projects at the same time.

**Comment by inoumen** [comment]
It's messed in some parts but this is how I made it, and it works :) 
My tip: before making your own component, it's better to clone the react-big-calendar repo to pick up from there some pieces of code as I have below (inRange function, for example). And pay attention to the AgendaView.navigate, as the default component has a bug that is fixed here. 

```JavaScript
import React from 'react'
import * as dates from 'date-arithmetic'
import PropTypes from 'prop-types'
import cn from 'classnames'
import dayjs from 'dayjs'
import styles from ''

function rangeFunc(start, end, unit = 'day') {
  let current = start
  const days = []
  while (dates.lte(current, end, unit)) {
    days.push(current)
    current = dates.add(current, 1, unit)
  }
  return days
}

function inRange(e, start, end, accessors) {
  const eStart = dates.startOf(accessors.start(e), 'day')
  const eEnd = accessors.end(e)
  const startsBeforeEnd = dates.lte(eStart, end, 'day')
  const endsAfterStart = !dates.eq(eStart, eEnd, 'minutes')
    ? dates.gt(eEnd, start, 'minutes')
    : dates.gte(eEnd, start, 'minutes')
  return startsBeforeEnd && endsAfterStart
}

export const AgendaView = ({ accessors, localizer, length, date, events }) => {
  const renderDay = (day, events) => {
    events = events.filter((e) =>
      inRange(e, dates.startOf(day, 'day'), dates.endOf(day, 'day'), accessors)
    )
    return events.map((event, idx) => {
      return (
        <div key={idx}>
          {idx === 0 && (
            <div className={styles.dateWrap}>
              <p>{localizer.format(day, 'MMMM DD')}</p>
              <div className={styles.line} />
            </div>
          )}
          <div
            className={cn(styles.record, {
              [styles.canceled]: event.resources.data.canceled,
            })}
          >
            <div className={styles.time}>{timeRangeLabel(day, event)}</div>
            <div className={styles.eventTitle}>{accessors.title(event)}</div>
            <div className={styles.details}>
              <span>City: </span>
              <span>{event.resources.city}</span>
            </div>
          </div>
        </div>
      )
    }, [])
  }

  const timeRangeLabel = (day, event) => {
    const end = accessors.end(event)
    const start = accessors.start(event)

    if (!accessors.allDay(event)) {
      if (dayjs(start).day() === dayjs(end).day()) {
        const timePeriod = `${dayjs(start).format('h:mma')} – ${dayjs(
          end
        ).format('h:mma')}`
        return timePeriod
      } else {
        const startDate = dayjs(start).format('DD-MM YYYY, h:mma')
        const endDate = dayjs(end).format('DD-MM YYYY, h:mma')
        return `${startDate} – ${endDate}`
      }
    }
  }

  const end = dates.add(date, length, 'day')
  const range = rangeFunc(date, end, 'day')
  events = events.filter((event) => inRange(event, date, end, accessors))
  events.sort((a, b) => +accessors.start(a) - +accessors.start(b))

  return (
    <div>
      {events.length !== 0
        ? range.map((day, idx) => renderDay(day, events, idx))
        : 'No event dates in range'}
    </div>
  )
}

AgendaView.title = (start, { localizer }) => {
  const end = dates.add(start, 1, 'month')
  return localizer.format({ start, end }, 'agendaHeaderFormat')
}

AgendaView.navigate = (date, action) => {
  const sDate = dayjs(date).startOf('month').toDate()
  switch (action) {
    case 'PREV':
      return dates.add(sDate, -1, 'month')
    case 'NEXT':
      return dates.add(sDate, 1, 'month')
    default:
      return date
  }
}

AgendaView.propTypes = {
  events: PropTypes.array,
  date: PropTypes.instanceOf(Date),
  length: PropTypes.number,
  selected: PropTypes.object,
  accessors: PropTypes.object.isRequired,
  components: PropTypes.object.isRequired,
  getters: PropTypes.object.isRequired,
  localizer: PropTypes.object.isRequired,
}

```

**Comment by MightyVivekKolkatta** [comment]
Can you provide CustomAgenda Code ?

**Comment by cutterbl** [comment]
I believe the [Custom Component Rendering](http://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/examples--example-8) example is a custom agenda layout, and includes a link to sample code.
