### ISSUE TITLE
Drag and Drop: Multi-day to single-day resize. 

### ISSUE THREAD

**Issue by IshFish** [jquense/react-big-calendar#1549]
#### Do you want to request a _feature_ or report a _bug_?

A Bug

#### What's the current behavior?

In month view with drag and drop enabled, when I resize an event that occurs within a day to 2 or more days that works great. If I then try to resize it back to its initial length of one day it prevents me from doing so, stopping on the second day. If I resize the start date I can then resize the end date to correct position

![dndResize](https://user-images.githubusercontent.com/35322418/70662301-0e70f500-1cba-11ea-8585-929d305a1e35.gif)

#### What's the expected behavior?

Resizing multi-day events to a single day works fine, as such I expected that if I made a single day event a multi-day event I would be able to return it to its single-day form.

**Comment by cutterbl** [comment]
resolved
