### ISSUE TITLE
Drag and Drop - Gaining access to "new" event time.

### ISSUE THREAD

**Issue by schester44** [jquense/react-big-calendar#1551]
When dragging an event, the events start and end times are for the event's current start and end time. I'm trying to gain access to the _current_ time of where the event is positioned within the calendar while being dragged. 

Here is a screen recording https://recordit.co/yYWO5mt4Tt 

I'd like to update the times and duration on the right side while the event is being dragged/resized.

I'm having trouble finding in the source whether that prop/date is being made available or not.

**Comment by schester44** [comment]
oh apparently it does this already, I must be using the wrong callback

**Comment by schester44** [comment]
actually, I think the DnD example is just updating the "label" but still not making the start/end times of the event available to any accessible component.

**Comment by cutterbl** [comment]
Not entirely sure I understand what you're asking. The `onEventDrop` is called when you drag an event to a new slot, and `onEventResize` is called when you resize an event. There is a [DnD Example](http://jquense.github.io/react-big-calendar/examples/index.html#dnd) in the docs that gives source code showing how each one works. (There is not method documentation itself, as it is an addon, which is frustrating).

- `onEventDrop({event <Event>, start <Date>, end <Date>, isAllDay <Bool>})` - This doesn't automatically update your `events`, not does it automatically update the `event` you were moving, but it gives you the data you need to do so. The [Example Code](https://github.com/jquense/react-big-calendar/blob/master/examples/demos/dnd.js) lays out a pretty clear path on how you could handle it.
- `onEventResize({event <Event>, start <Date>, end <Date>, isAllDay <Bool>})` - This doesn't automatically update your `events`, not does it automatically update the `event` you were resizing, but it gives you the data you need to do so. The [Example Code](https://github.com/jquense/react-big-calendar/blob/master/examples/demos/dnd.js) lays out a pretty clear path on how you could handle it.

**Comment by schester44** [comment]
@cutterbl thanks for responding. Those events are basically 'on end' events, as in they only fire when the action of dragging/resizing is finished. Using those, I am able to update the position of an event.

What I want to do though is display the current time for the event while the event is being resized.

So, using resizing as an example.. `onEventResize` would really be `onEventResizeEnded` since it only fires when the action is finished. What i'm looking for is a true `onEventResize` event that fires while the event is being resized so that I can tap into the current time/position of the event being resized.

Here is a gif of the current issue:
https://recordit.co/zgbK6jmFqm

Notice how the event time doesn't update until I stop dragging the event card. I'd like to update the event time as i'm dragging the event card.

**Comment by schester44** [comment]
ahh I figured it out....

My events have `startTime` and `endTime` properties, so I make use of the start|end accessors. When dragging, the calendar updates `event.start` and `event.end`. 

My event card was using startTime, which wasn't being updated until onEventResize was called. Changing my code to something like this did the trick.

```
format(event.start || event.startTime, 'h:mm A')
```
