### ISSUE TITLE
Month view dates off-by-one in certain timezones

### ISSUE THREAD

**Issue by whiskeyseven** [jquense/react-big-calendar#1555]
I'm seeing a strange issue where my month view has mislabled dates.
Today, when this screenshot was taken, is Wednesday December 18 2019.

![Screen Shot 2019-12-18 at 7 48 10 PM](https://user-images.githubusercontent.com/4267111/71123652-cdae3a00-21eb-11ea-9911-edade55051bb.png)

I have set my system time zone to Central Africa Time to test (since that is where the issue was reported to me). As you can see, the dates show the month starting on the 30th and ending on the 30th (instead of 1 - 31). Additionally, the week incorrectly starts with Sat instead of Sun. And finally, the current day is incorrectly highlighted as the 17th instead of the 18th.

This ONLY occurs in timezones outside of North America. If I set my system time to US East, everything renders correctly. The correct "today" is highlighted on the 18th, the dates are 1-31, and the week day order starts with Sunday.

I'm using momentLocalizer. If I console log a fresh moment instance, I see everything looks correct. The date is correct, and the locale information seems to indicate the days of the week should be Sunday, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday

![Screen Shot 2019-12-18 at 11 18 51 PM](https://user-images.githubusercontent.com/4267111/71124168-eff48780-21ec-11ea-8ee4-c84040133912.png)

My code is straightforward regarding locale:
```
localizer = momentLocalizer(moment)
moment.locale('en',{
  week: {
    dow: 0,
    doy: 1,
  }
})

<Calendar
  popup
  localizer={localizer}
  events={this.filteredEvents()}
  defaultDate={this.findMonthInDateRange()}
  startAccessor="startOn"
  endAccessor="endOn"
  views={['month']}
...
```

Again, if I set my system time to US East, everything works correctly.

Is this an issue with the localizer? The documentation seems to indicate that the localizer only controls date string formatting and language.

What else might alter the date labeling in month view?

Thanks in advance!

**Comment by whiskeyseven** [comment]
follow up: the issue is a result of setting a default timezone in moment that is different from the computer system time. in my app, the user is allowed to set a default timezone for their account.

for example, if my code contains the following:
`moment.tz.setDefault(userRecord.timezoneName);`
where userRecord.timezoneName = "EST", react-big-calendar will render incorrectly if my computer system timezone is set several timezones off (HKT, for example)

whenever the 2 match, everything works correctly.

**Comment by cdimitroulas** [comment]
I'm encountering a similar issue when setting a different timezone as default with `moment-timezone`. Using version `0.19.2` of react-big-calendar.

**Comment by cutterbl** [comment]
RBC doesn't have built-in timezone support, expecting us to write our own implementation based on whichever localizer we use. Here's a [GitHub repo](https://github.com/cutterbl/react-big-calendar-with-timezones) of example code using the Moment localizer, including a [CodeSandbox Example](https://codesandbox.io/s/github/cutterbl/react-big-calendar-with-timezones/tree/master/?fontsize=14).

**Comment by cutterbl** [comment]
Documentation on [working with Timezones](http://jquense.github.io/react-big-calendar/examples/index.html?path=/story/guides-timezones--page) in Big Calendar.
