### ISSUE TITLE
All day event cell does not align correctly with below timeslot cell in week view when zoom out text size

### ISSUE THREAD

**Issue by vivianlw1025** [jquense/react-big-calendar#1559]
OS: Windows 10 Enterprise
Browser: Chrome Version 78.0.3904.108 (Official Build) (64-bit), Firefox 71.0 (64-bit)
Display Resolution: 1920*1080

We use react-big-calendar in our web email client for calendar view display. We found problem that all day event cell does not align correctly with timeslot cell in week view when zoom out text size to more than 125%, Please check screenshot in our product webpage
![image](https://user-images.githubusercontent.com/52697073/71334442-3a715d80-2579-11ea-97ec-257195d839eb.png)

We found the same issue in react-big-calendar demo site as well
http://intljusticemission.github.io/react-big-calendar/examples/index.html#basic
![image](https://user-images.githubusercontent.com/52697073/71334416-16ae1780-2579-11ea-8327-52653612ee7e.png)

**Comment by jcieslar** [comment]
The error is also on http://intljusticemission.github.io/react-big-calendar/examples/index.html#selectable 
when you open it with direct link or when you refresh calendar with `defaultView="week"`

![Webpack App 2020-02-06 21-42-39-11hdn](https://user-images.githubusercontent.com/1283589/73977987-a93d2700-492b-11ea-987f-6a17052b2177.jpg)

**Comment by cutterbl** [comment]
Resolved
