### ISSUE TITLE
Event Not displaying based on start time, it depends on End time in One day view

### ISSUE THREAD

**Issue by sathishkumars92** [jquense/react-big-calendar#1563]
I'm happy with your work in big calendar, It helped us a lot. One Issue we are facing is in the below image, the event starts at 4pm but it show like 3.45pm. How to control the UI event to
start at correct starting point. Will be looking forward for your reply.

<img width="245" alt="calendar_ui" src="https://user-images.githubusercontent.com/3184062/71902829-dc539580-3188-11ea-83ad-b7e7a88e8f61.PNG">

**Comment by sudhamab** [comment]
hi, any thoughts on this? would like to know the answer for this as well.

**Comment by Dric0** [comment]
same issue here

**Comment by mfranchitti** [comment]
Same issue - anyone ever resolve thise?

**Comment by vAskitsa** [comment]
If value of your 'step' attribute is lower than value of your 'timeslots' attribute this will happen.
There are multiple issues and some pull request about this but it seems that this will never get resolved.
Change value of your step attribute to be 15 minutes and it'll work until you need shorter than 15 minutes events.

**Comment by sudhamab** [comment]
thanks @vAskitsa  ! that worked. sorry for the delay in responding.
