### ISSUE TITLE
date-fns localizer dayHeaderFormat string shows day of year instead of day of week

### ISSUE THREAD

**Issue by villa7** [jquense/react-big-calendar#1567]
The formatting strings for `date-fns` are different from those required for `moment`

#### Do you want to request a _feature_ or report a _bug_?
bug
#### What's the current behavior?

![image](https://user-images.githubusercontent.com/1696813/72549841-76899c80-385f-11ea-8132-b5f2e3c17235.png)

```js
dayHeaderFormat: 'dddd MMM dd',
agendaDateFormat: 'ddd MMM dd'
```

#### What's the expected behavior?

![image](https://user-images.githubusercontent.com/1696813/72549883-8f924d80-385f-11ea-8c2d-d320d8b9b9ef.png)

```js
dayHeaderFormat: 'cccc MMM dd',
agendaDateFormat: 'ccc MMM dd'
```

**Comment by yann-combarnous** [comment]
Same issue here. @jquense  , any change this PR gets merged?
