### ISSUE TITLE
DIsplay custom component( not event or toolbar ).

### ISSUE THREAD

**Issue by adityay-perpetualny** [jquense/react-big-calendar#1569]
#### Do you want to request a _feature_ or report a _bug_?
Not a bug or feature May be a help

#### What's the current behavior?
Can only customized known component such as event and toolbar

#### What's the expected behavior?

![image](https://user-images.githubusercontent.com/44191071/72704211-1f950780-3b7e-11ea-819f-9576395c4446.png)

I want a custom component which can be hovered( like a tooltip but not on the event )  each day conditionally . This is not a toolbar or event component. Completely new component as shown in the screenshot( the dotted one in circle on date 17 box ) .

Could you please help me in this.

**Comment by cutterbl** [comment]
First pass, I would think you'd be able to do this with a custom `dateCellWrapper` component, but it seems that this is a background behind the content row, so onClick and hover events won't make it to the components. You'd have to use use the `components.month.dateHeader` with a custom `DateHeader`. Here's a (messy) [CodeSandbox Example](https://codesandbox.io/embed/goofy-allen-wkmem?fontsize=14&hidenavigation=1&theme=dark).

**Comment by Angelk90** [comment]
@cutterbl : Do you know how I can customize this:
![image](https://user-images.githubusercontent.com/20476002/87040442-fe3ddb80-c1f0-11ea-9f7d-8c660a036314.png)

**Comment by cutterbl** [comment]
@Angelk90 Yes, you can write a custom `event` template. For instance, I needed different displays between a standard `event` and an `allDay` `event`. So I created a `CustomEvent`

```
import React from 'react';
import PropTypes from 'prop-types';
import StandardEvent from './StandardEvent.component';
import AllDayEvent from './AllDayEvent.component';
import styles from './CustomEvent.module.scss';

const propTypes = {
  event: PropTypes.object.isRequired,
  isAllDay: PropTypes.bool
};

const CustomEvent = ({ event, isAllDay, ...props }) => {
  return (
    <div className={styles['appointments-custom-event']}>
      {!isAllDay ? (
        <StandardEvent event={event} {...props} />
      ) : (
        <AllDayEvent event={event} {...props} />
      )}
    </div>
  );
};

CustomEvent.propTypes = propTypes;
export default CustomEvent;
```

Then, for example, my `StandardEvent` looks like this

```
import React, { Fragment } from 'react';
import PropTypes from 'prop-types';
import classnames from 'classnames';
import { moment } from '@my/components';
import { useAppointments } from '../../appointments.context';
import styles from './CustomEvent.module.scss';

const propTypes = {
  event: PropTypes.object.isRequired
};

const StandardEvent = ({ event }) => {
  const { timeZoneId } = useAppointments();
  return (
    <table>
      <tbody>
        <tr>
          <td>
            {event.PatientFamilyName && event.PatientGivenName && (
              <Fragment>
                <span className={styles.strong}>
                  <strong>
                    {event.PatientFamilyName}, {event.PatientGivenName}
                  </strong>
                </span>
                <br />
              </Fragment>
            )}
            <span
              className={classnames({
                [styles.strong]:
                  !event.PatientFamilyName && !event.PatientGivenName
              })}
            >
              {event.EncounterTypeDescription}
            </span>
          </td>
          <td
            className={classnames(
              styles['appointments-custom-event-date'],
              styles.strong
            )}
          >
            <span>
              {moment(event.StartDateTime)
                .tz(timeZoneId)
                .format('hh:mma')}
            </span>
          </td>
        </tr>
      </tbody>
    </table>
  );
};

StandardEvent.propTypes = propTypes;
export default StandardEvent;
```

Then I had to apply my `CustomEvent` as a custom component. I found that I had to specify it at the view type level.

```
components={{
  toolbar: CustomToolbar,
  week: {
    event: CustomEvent,
  },
  month: {
    event: CustomEvent,
  },
  day: {
    event: CustomEvent,
  },
}}
```

**Comment by fleckc3** [comment]
@cutterbl Thanks for this info. By chance would you be willing to show your css files for these?
