### ISSUE TITLE
No extra blank space on all day event cell to click for creating more all day events easily

### ISSUE THREAD

**Issue by vivianlw1025** [jquense/react-big-calendar#1571]
OS: Windows 10 Enterprise
Browser: Chrome Version 78.0.3904.108 (Official Build) (64-bit), Firefox 71.0 (64-bit)
Display Resolution: 1920*1080

We use react-big-calendar in our web email client for calendar view display. We found a usability issue that when more all day events display in week/day view, there is no extra white space on all day event cell for user to click on it to create new event easily

Below is our product snapshot
![image](https://user-images.githubusercontent.com/52697073/72954478-7cd5c680-3dd3-11ea-8307-6d52d50b8428.png)

The same issue happens on react-big-calendar demo site as well
![image](https://user-images.githubusercontent.com/52697073/72954617-f8377800-3dd3-11ea-8a56-eaffec30dab5.png)

Suggest to provide such blank space in all day event cell as well

**Comment by cutterbl** [comment]
I had to override the styles to get that space

```
.rbc-allday-cell > .rbc-row-content {
  padding-bottom: 15px;
}
```
