### ISSUE TITLE
use loop in dayPropGetter prop

### ISSUE THREAD

**Issue by maryam-rostami** [jquense/react-big-calendar#1581]
Hi guys, I have a question about dayPropGetter :
I want use map inside the  dayPropGetter  method and use if() to return different background, but it dosent happen, inside of map dosent return style and  it is not working

my codes are here:

```
customDayPropGetter = (date) => {
         let data = [{day: 2020-02-15,holidayType : 1},{day: 2020-02-20,holidayType : 0}]
                  data.map((item,index) =>{
                         if (item.day === date && item.holidayType == 0)
                             return { style: { backgroundColor: "red" } }

                         if (item.day === date && item.holidayType == 1)
                              return { style: { backgroundColor: "orange" } }
            _})_
           
    }
```
how can I fix it ?

**Comment by maryam-rostami** [comment]
I solved my problem
it Should be used find()  instead of map():


`customDayPropGetter = (date) => {
        let data = [{day: 2020-02-15,holidayType : 1},{day: 2020-02-20,holidayType : 0}];

            var obj = data.find((element, index) => {
                if ((element.day === date && element.holidayType === 0) ||
                    (element.day === date && element.holidayType === 1) 
                     return data[index]
            });
            if(obj !== undefined && obj.day === date &&  obj.holidayType === 0)
            return { style: { backgroundColor: "red" } }
            else if(obj !== undefined && obj.day === date && obj.holidayType === 1)
            return { style: { backgroundColor: "orange" } }

            else return { style: { backgroundColor: "#fff" } }

    }`




Maybe someone had this problem

**Comment by cutterbl** [comment]
@maryam-rostami How does this work? Doesn't the `customDayPropGetter` take a full JS Date object as the argument? The value you are applying to `day`, in your code above, would be evaluated as a math expression. Is it just pseudocode?
