### ISSUE TITLE
Missing start script

### ISSUE THREAD

**Issue by ikmofem7** [jquense/react-big-calendar#1585]
i have downloaded folder and after npm i recieving missing start scripts

**Comment by cutterbl** [comment]
I cloned the repo and ran npm i and everything is working flawlessly. Check the `package.json` file for the available scripts. You can run `npm run storybook` to spin up Storybook and see it's all working. You can run `npm run examples` and go to `http://localhost:3000/examples` in your browser to see a local version of the documentation site.
