### ISSUE TITLE
Displaying multiple events that have same name, but with different dates (on one calendar)

### ISSUE THREAD

**Issue by nickallenjr** [jquense/react-big-calendar#1587]
#### Do you want to request a _feature_ or report a _bug_?
Feature or Bug? Not sure.

#### What's the current behavior?
I have a calendar that I want to display events that have one name, but multiple dates.

My event info looks like this:
{
  id: 58321,
  name: "Reg Dat",
  description: "day",
  categoryId: 6,
  categoryName: "Test",
  recurring: true,
  dates: [{
             days: {startDate: "02/29/2020", endDate: "02/29/2020"},
             numPreDays: 1,
             numPostDays: 1,
             rangeSeq: 7
      },{
             days: {startDate: "02/22/2020", endDate: "02/22/2020"},
             numPreDays: 2,
             numPostDays: 2,
             rangeSeq: 8
      }]
}
My calendar setup is like so:

                                               <BigCalendar
                                                    localizer={localizer}
                                                    events={this.props.events.events}
                                                    selectable={true}
                                                    defaultView="month"                                                    
                                                    date={addMonths(this.state.date, 0)}
                                                    views={['month']}
                                                    titleAccessor="name"
                                                    startAccessor={(start)=>{
                                                        var s = toNewDate(start.dates[0].days.startDate);
                                                        return s
                                                    }}
                                                    endAccessor={(end) => {
                                                        var e = toNewDate(end.dates[0].days.endDate);
                                                        return e
                                                    }}
                                               />

As it stands I can only display one event at a time. If you notice i'm setting my start and end accessors to reference the date in array index 0. So to display both events what I did inside my start and end accessors was this:

                                                        startAccessor={(start) => {
                                                          start.dates.forEach(date => {
                                                              var s = toNewDate(date.days.startDate);
                                                              return s
                                                          })
                                                       }
                                                      endAccessor={(end) => {
                                                        end.dates.forEach(date => {
                                                            var s = toNewDate(date.days.endDate);
                                                            return addDays(s, date.numPostDays);
                                                        })
                                                       }

However now it doesn't display either event in my calendar.

P.S. toNewDate just splits those Strings into actual date objects.

#### What's the expected behavior?
I want to display the event on the calendar for both dates. I hope this makes sense. I will try to create a code sandbox soon.

Thanks

**Comment by nickallenjr** [comment]
Code Sandbox
https://codesandbox.io/embed/react-big-calendar-example-eej52?fontsize=14&hidenavigation=1&theme=dark

**Comment by schester44** [comment]
```
endAccessor={(end) => {
    end.dates.forEach(date => {
         var s = toNewDate(date.days.endDate);
          return addDays(s, date.numPostDays);
     })
}
```
In your example above, you're not actually returning anything for the start|end accessors. Also, you can only ever return a single value for the start|end accessors since those are ran on each event.

If you want to display 1 event which has multiple start/end times (such as recurring events) you'll need to normalize your data and create multiple separate events for the events that have multiple start/end times.

Some pseudo code to get you started:


```
const allEvents = {
  id: 58321,
  name: "Reg Dat",
  description: "day",
  categoryId: 6,
  categoryName: "Test",
  recurring: true,
  dates: [
    {
      days: { startDate: "02/29/2020", endDate: "02/29/2020" },
      numPreDays: 1,
      numPostDays: 1,
      rangeSeq: 7
    },
    {
      days: { startDate: "02/22/2020", endDate: "02/22/2020" },
      numPreDays: 2,
      numPostDays: 2,
      rangeSeq: 8
    }
  ]
};

const flattenEvents = allEvents => {
  const events = [];

  for (let i = 0; i < events.length; i++) {
    const { dates, ...event } = events[i];

    if (!Array.isArray(dates) || dates.length === 0) continue;

    dates.forEach(date => {
      events.push({ ...event, ...date });
    });
  }

  return events;
};

const MyApp = ({ allEvents }) => {
  const events = flattenEvents(allEvents);

  return (
    <Calendar
      events={events}
      startAccessor={event => {
        return toNewDate(event.days.startDate);
      }}
      endAccessor={event => {
        return toNewDate(event.days.endDate);
      }}
    />
  );
};
```

**Comment by nickallenjr** [comment]
@schester44 Thanks a lot for the response and the pseudo code! It makes total sense what your saying I couldn't think of the words recurring events, but that's exactly what I meant! This will help me meet my deadline at work!!! Cheers!
