### ISSUE TITLE
How to adjust space to the right of events in weekly view

### ISSUE THREAD

**Issue by mikeyyyzhao** [jquense/react-big-calendar#1589]
We made a change somewhere along the way that deleted the space to the right of events in weekly view. I'm having a difficult time tracing back where in the code RBC determines the width and where to place events (multiple events). I tried hacking it and setting max-width to 95% and that works for single events but for multiple events in the same slot, it no longer works. Heres a view of our current events view. 

<img width="93" alt="Screenshot 2020-02-18 10 43 09" src="https://user-images.githubusercontent.com/4956032/74767395-a4397b00-523b-11ea-8a00-ce01051d6424.png">

**Comment by cutterbl** [comment]
resolved
