### ISSUE TITLE
Full props and method

### ISSUE THREAD

**Issue by jacky-ew** [jquense/react-big-calendar#1590]
Need a documentation explaining all the props and any possible methods. Cause the current documentation shows only basic props. Other deeper props usage cannot be found.

**Comment by jquense** [comment]
If you need more docs please consult the source code, we aren't hiding better docs somewhere :P

**Comment by jacky-ew** [comment]
May i know which component props to edit to change the container style for `day` cell display in basic calendar

**Comment by jquense** [comment]
use the css classes to target specific containers for styling
