### ISSUE TITLE
Hyphen between dates not rendering properly

### ISSUE THREAD

**Issue by nullsage** [jquense/react-big-calendar#1593]
#### Do you want to request a _feature_ or report a _bug_?
Bug
#### What's the current behavior?
The hyphen used between dates isnt rendering properly. I am getting some sort of ascii characters. See attachment or visit https://whoismarkinman.com/kiosk and go to the schedule page and click on week or agenda on the calendar.
![no-dash](https://user-images.githubusercontent.com/6161840/75118595-519bfc80-5649-11ea-8a68-8f1ab1fc587f.PNG)

**Comment by oestrogen** [comment]
@nullsage This is a problem with your setup, not with react-big-calendar. 

Your page is being interpreted by browsers as having character encoding ISO-8859-1, but it's the en dashes are in UTF-8.

Set `<meta charset="UTF-8">` in `<head>`. Make sure you save your source files as UTF-8 files and make sure your web server  output UTF-8.

It seems https://whoismarkinman.com/ have the encoding `text/html; charset=UTF-8`, but https://whoismarkinman.com/kiosk/ only have the encoding `text/html`.

**Comment by nullsage** [comment]
Awesome thank you so much; i knew it had to be something simple :)
