### ISSUE TITLE
Discord invite link broken

### ISSUE THREAD

**Issue by Ryanauger95** [jquense/react-big-calendar#1595]
The discord invite link is broken. I would like to join the channel on discord, can you please provide a new link here? 

Thanks!

**Comment by malouro** [comment]
Would like to mention here that the `#react-big-calendar` channel was removed from the Reactiflux Discord server. The readme might have to be updated to just no longer mention the Discord server 😢

**Comment by Ryanauger95** [comment]
Is there any other community?

**Comment by Ryanauger95** [comment]
@malouro , just bumping this!

**Comment by malouro** [comment]
@Ryanauger95 I don't know of any personally, but it might be worth asking around in the Reactiflux Discord server (the invite is on [their website](https://www.reactiflux.com/))

**Comment by jquense** [comment]
updated to the general library channel, there isn't a RBC specific channel anymore

**Comment by Ryanauger95** [comment]
@jquense Which one is the general library channel? I just see a list of libraries.. "react-router", "redux", ...."react-beautiful-dnd"
