### ISSUE TITLE
Times are slightly off in the day view compared to the actual time in the event

### ISSUE THREAD

**Issue by alexfellow** [jquense/react-big-calendar#1596]
#### Do you want to request a _feature_ or report a _bug_?
bug

#### What's the current behavior?
Times are off even for the test example from the official web site:
http://jquense.github.io/react-big-calendar/examples/index.html

Just set up view = `day` and date = `12 of April`:
![image](https://user-images.githubusercontent.com/55251728/75192380-1b7e7b80-5722-11ea-87cc-f05fbb2ffde8.png)

#### What's the expected behavior?
Meetings on their places

**Comment by alexfellow** [comment]
For week view also reproduced (see last two, for example)

![image](https://user-images.githubusercontent.com/55251728/75192881-25ed4500-5723-11ea-9f9b-ec29c2154dfb.png)

**Comment by DiegoGregoracci** [comment]
@alexfellow I was running into the same problem. In my case, I had an event with the end property set before the start (ie start: 15:00, end: 14:00) and all the events rendered awfully.
I downloaded the example code and works fine locally fyi, maybe something is not correctly installed online.
Hope that helps

**Comment by alexfellow** [comment]
@DiegoGregoracci Thank you for your comment.
I am afraid, it's not my case. I also faced this bug in the real project. The same behavior with a wrong events position is observed with 100% valid events (with correct start/end times) that comes from the calendar app

**Comment by cutterbl** [comment]
stale
