### ISSUE TITLE
Events Straddling Two Days in Resource Treated As AllDay Events

### ISSUE THREAD

**Issue by jjinho** [jquense/react-big-calendar#1610]
#### What's the current behavior?
When using resources, under Day View, when I add an event that straddles two days (e.g. January 28, 2018 @ 11:00 PM to January 29, 2018 @ 5:00 AM), the event is listed as an all day event on both days.

Example is shown here: https://codesandbox.io/s/youthful-resonance-2c6h4

#### What's the expected behavior?
Instead, I would expect that the same behavior as any event, except that the event on the current day would go till midnight, and on the next day, the event would start from midnight to the end.

I do want to say that I think this component is really awesome, and although this is a fringe case, it still can occur in my app and a fix or work around would be super helpful!

**Comment by francoiscampbell** [comment]
I ran into the same issue, the `showMultiDayTimes` prop fixed that for me:

https://jquense.github.io/react-big-calendar/examples/index.html#prop-showMultiDayTimes

**Comment by jorgecuevas92** [comment]
I had the same issue and can confirm that adding the property `showMultiDayTimes` does solve the problem.
