### ISSUE TITLE
Single Event works, Multi Event doesn't?

### ISSUE THREAD

**Issue by vitorvicente** [jquense/react-big-calendar#1611]
I'm having an issue transforming from using a single event to an event list.
I'm using axios to make a get request from my database (screenshots provided bellow), and mapping the raw output into the correct format, however when I try to map more than 1 object the calendar just doesn't recognize them, it also doesn't seem to throw any erros?

Database: https://gyazo.com/6585ad9f7813334d435aec93e9ffa743
Axios BackEnd: https://gyazo.com/8d5f4125f0b2dc54b5001973e9310739

Single Event Code: https://gyazo.com/bf6409c6a3c2a8f2e6fbebde6242db8f
Single Event Calendar: https://gyazo.com/bf6409c6a3c2a8f2e6fbebde6242db8f

Multi Event Code:https://gyazo.com/279e6345a629ef6ea0885da07c550955
Multi Event Calendar: https://gyazo.com/09be50f9d5c9f04a595ece66072dfff7

It's also weird as the console.log statement returns the array in the correct fashion... so I'm not really sure why this isn't working?

**Comment by cutterbl** [comment]
stale
