### ISSUE TITLE
Bug with times in week view for March

### ISSUE THREAD

**Issue by milicamitk** [jquense/react-big-calendar#1617]
#### Do you want to request a _feature_ or report a _bug_?

Request a bug
#### What's the current behavior?

March 2020:
<img width="1180" alt="march-2020" src="https://user-images.githubusercontent.com/22446587/77154583-48f9e300-6a9c-11ea-80fa-9fecebe0b0cc.png">

March 2021:
<img width="1195" alt="march-2021" src="https://user-images.githubusercontent.com/22446587/77154603-531be180-6a9c-11ea-8206-82b681312e66.png">

I check for a few years in the calendar, always exist the same issue. In last week's view between March and April, the user can't choose 2 AM time. Have a duplicate slot of 3 AM.

The issue is because of DST.

#### What's the expected behavior?

Ability to choose 2 AM time in week view.

**Comment by SatioO** [comment]
Any workaround on this? I am facing a similar issue where the calendar skips time between 2 AM to 3 AM.

<img width="272" alt="Screen Shot 2022-01-14 at 12 58 02 PM" src="https://user-images.githubusercontent.com/6435708/149468458-67adb9af-c47c-4d00-bf9b-a4a03105a7f8.png">



@milicamitk @jeanlazarou @sonnyp @tiwatson @ogyr

**Comment by milicamitk** [comment]
@jeanlazarou @sonnyp @tiwatson @ogyr @SatioO Here is the pr for this issue https://github.com/jquense/react-big-calendar/pull/1624
