### ISSUE TITLE
refactor to hooks?

### ISSUE THREAD

**Issue by sibelius** [jquense/react-big-calendar#1620]
#### Do you want to request a _feature_ or report a _bug_?
feature

#### What's the current behavior?
it shows many warnings in strict mode

related to https://github.com/jquense/react-big-calendar/issues/1570
and https://github.com/jquense/react-big-calendar/issues/1481

#### What's the expected behavior?

it should work well without warnings in strict mode

would you accept a migration to hooks to fix all this warnings?

**Comment by jquense** [comment]
sure, always open to PRs. They need to be thorough tho, i don't have much time to review for this lib!

**Comment by GingerJams206** [comment]
I'm using this in a project of my own...has this gone anywhere since March of 2020?

**Comment by jquense** [comment]
nope!

**Comment by DanielUche** [comment]
Is this still an issue, I want to use this component in a new project but I fear this warning is an issue.

**Comment by mdestafadilah** [comment]
Any alternative here?

**Comment by jbcortez** [comment]
Well this is a huge bummer. Any plans on ever fixing this? Also, any alternative packages out there? I'd hate to have to build a calendar from scratch.

**Comment by mdestafadilah** [comment]
I think someone created a hook version and done. nice job @AugustoCalaca  #1687 , please close this issued @sibelius. thx

**Comment by andresmurillo13** [comment]
react_devtools_backend.js:4012 Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code. See https://reactjs.org/link/unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://reactjs.org/link/derived-state

Please update the following components: DayColumn2

**Comment by royscript** [comment]
I had these error. Please, upgrade the code.

![image](https://user-images.githubusercontent.com/27907731/216846127-e12d6249-2d09-4374-9719-ba5d4e10a75a.png)

**Comment by bu6n** [comment]
Don't want to sound harsh but this is an open source project and most people fixing bugs are doing so for free. We have a Slack space where we are discussing the next version of react-big-calendar. It's not as easy as "upgrading the code". If you want to help: https://join.slack.com/t/bigcalendar/shared_invite/zt-1ml1j99af-qIvqOfosMog1W7WxM0~j2Q

**Comment by MichaelKleyman** [comment]
The slack channel is down. Would anyone in this issue thread be open to tackling this issue ourselves. Its open source so maybe we can fix the issue.

**Comment by MichaelKleyman** [comment]
Update, i ended up fixing the issue on my end, nothing wrong with the RBC code as far as i know. For future nextjs13 and higher version users, simply going into the next.config.js and setting the config as shown below fixes the issue because by default strictmode is set to true, and that was causing my issue

const nextConfig = {
  reactStrictMode: false,
};

**Comment by travelerr** [comment]
> Update, i ended up fixing the issue on my end, nothing wrong with the RBC code as far as i know. For future nextjs13 and higher version users, simply going into the next.config.js and setting the config as shown below fixes the issue because by default strictmode is set to true, and that was causing my issue
> 
> const nextConfig = { reactStrictMode: false, };

can confirm this worked for me. thank yo
