### ISSUE TITLE
Drag and drop - Event frozen in week view

### ISSUE THREAD

**Issue by zheyujie** [jquense/react-big-calendar#1623]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?
Use DND wrapper:
1. Go to Week view (I haven't tried Day view but I suspect it has the same problem)
2. Find a draggable event
3. Click on the event and drag it to somewhere else BUT do not drop it
4. Hold the mouse and move the event back to its original position, drop it

Sometime the event may be frozen after dropping it (i.e. it can no longer be moved/resized, and it will always be shown when you navigate to next/previous week)
I've got a short video showing the problem:
https://www.loom.com/share/be40ac085e4347c4b91b4ff4eb95542a

#### What's the expected behavior?
The event should not be frozen.

Current workaround:
Either remount the calendar component, or switch to Month/Day view and then switch back to Week and the frozen event starts working again.

I cloned the source code locally and added some logging to onEventDrop callback and I can confirm the callback is not called when this happens. The problem seems to be intermittent.

**Comment by cutterbl** [comment]
resolved
