### ISSUE TITLE
Style entire calendar cell based on event type

### ISSUE THREAD

**Issue by mirceasirbu** [jquense/react-big-calendar#1627]
Hello there!

I'm trying to change the entire date cell based on the type of the event in that specific day. I can easily style the event wrapper, but I also need to style the date which is rendered in a separate component. I've even tried to modify the cell with `dateCellWrapper`, but it seems I don't have access to the event there. 

I worked this out using a custom Event where I display an additional date, and style it with CSS by placing it on top, but I'd like to know if anyone has a more elegant solution! 

Bellow is a screenshot of what I'm trying to achieve. 

Thanks a lot for your good work!

![Screen Shot 2020-04-01 at 23 59 11](https://user-images.githubusercontent.com/17257384/78187122-8c7a2700-7476-11ea-87bb-17fe0fbb2428.png)

**Comment by amirsanni** [comment]
`dayPropGetter` prop is what you need. [See here](http://jquense.github.io/react-big-calendar/examples/index.html#prop-dayPropGetter)
