### ISSUE TITLE
Selects the wrong slot

### ISSUE THREAD

**Issue by rush86999** [jquense/react-big-calendar#1628]
#### Do you want to request a _feature_ or report a _bug_?
bug
#### What's the current behavior?
selecting the wrong slot. about 5 hours behind I think. 
Using moment-timezone for localizer and latest react-big-calendar
![captured](https://user-images.githubusercontent.com/16848240/78187954-671cf700-743d-11ea-96d6-b1a7617131ea.gif)

**Comment by cutterbl** [comment]
Using [Timezones](http://jquense.github.io/react-big-calendar/examples/index.html?path=/story/guides-timezones--page) with Big Calendar
