### ISSUE TITLE
Still not working in setting width & height by eventPropGetter

### ISSUE THREAD

**Issue by vimiPonyai** [jquense/react-big-calendar#1630]
Thanks for react-big-calendar, one of the wonderful calendar lib for React.
Here I am facing a problem is that I can\`t set the width and height for the event by using `eventPropGetter`, maybe it the same as this issue but I try many methods still not working.
https://github.com/jquense/react-big-calendar/issues/524

"react": "^16.8.6",
"react-big-calendar": "^0.19.2",

#### What's the current behavior?
The width is auto set other value when two events overlap.
![image](https://user-images.githubusercontent.com/44854469/78689593-1586d780-7929-11ea-9d2b-63e7724be91d.png)

#### What's the expected behavior?
set to 10% or sth else as the `eventPropGetter` return
```
export const eventStyleGetter = (): EventPropGetter<Event> => {
  const func = (
    event: Event, // eslint-disable-line @typescript-eslint/no-unused-vars
    start: string | Date, // eslint-disable-line @typescript-eslint/no-unused-vars
    end: string | Date, // eslint-disable-line @typescript-eslint/no-unused-vars
    isSelected: boolean, // eslint-disable-line @typescript-eslint/no-unused-vars
  ): { className?: string; style?: React.CSSProperties } => {
    return {
      style: {
        borderWidth: 0,
        borderLeftWidth: 4,
        borderLeftColor: getColor(event).borderLeftColor,
        backgroundColor: getColor(event).backgroundColor,
        borderRadius: '0 4px 4px 0',
        boxShadow: '2px 2px 8px 0 #BEBFC2',
        left: '100% !important',
        width: '10% !important',
      },
    };
  };
  return func;
};
```

**Comment by cutterbl** [comment]
stale
