### ISSUE TITLE
Adding an event the day and moment the DST begins leads to an endless loop

### ISSUE THREAD

**Issue by jeanlazarou** [jquense/react-big-calendar#1632]
#### Do you want to request a _feature_ or report a _bug_?

A bug.

#### What's the current behavior?

I am using v0.23.0.

When trying to add an event the day DST begins, say from 00:00 to 10:00 (for instance Sunday 2021-03-28 / Europe), the browser enters an endless loop because it starts adding "15 minutes" (the step used) and the "add" function of "date-math" is failing (somehow) when we add 15 minutes to 01:45, it gets back to 01:00 again and again, see my comment (https://github.com/jquense/date-math/issues/18#issuecomment-610853124) in a open issue.

#### What's the expected behavior?

It should not go for the endless loop and create/add the event to the calendar.

**Comment by cutterbl** [comment]
resolved
