### ISSUE TITLE
Anyone here have tried a clickable events and show a modal with the details of the events selected?

### ISSUE THREAD

**Issue by dextreeamper** [jquense/react-big-calendar#1634]
#### Do you want to request a _feature_ or report a _bug_?
a feature
#### What's the current behavior?
I am using "react-big-calendar": "^0.24.1",

I follow this tutorial
https://codesandbox.io/s/l9jwl0kj6m

#### What's the expected behavior?
To have a clickable events and show a modal with the events selected details.

**Comment by cryps** [comment]
I've that on my project. I've used the property `onSelectSlot` to set a state that will open my modal dialog.

**Comment by OmniElliott** [comment]
Ive this kind of feature up in my project as well. I also used onSelectSlot to display a bootstrap modal based on state

**Comment by achyuthkp27** [comment]
> Ive this kind of feature up in my project as well. I also used onSelectSlot to display a bootstrap modal based on state

can you share the code

**Comment by kimfucious** [comment]
I just did this, so it's fresh in my mind.  I'll share here, in hopes that it helps.

First you need your events assessible.  Mine are stored in Redux state as an array of objects.  Something like this.  I'm using `resource` to pork-barrel additional info that I want to use later.

```js
const event = [{ 
  title:"Susan's Passport Expires",
  start:"2030-06-23T00:00:00+07:00",
  end:"2030-06-23T23:59:59+07:00",
  allDay:true,
  resource: {
    userId:"ec1f6076-9fcc-48c6-b0e9-e39dbc29557x",
    eventType:"visaExtensionWorkPermit" 
    }
}]
```

Once you have an array of objects available (e.g. events, as in below), use the onselectEvent param of the BigCalendar (whatever you call it) object to fire off a function (e.g. handleSelectedEvent):

```jsx
<BigCalendar
  localizer={localizer}
  onSelectEvent={(event) => handleSelectedEvent(event)}
  popup
  events={myCalendarEvents}
  startAccessor="start"
  endAccessor="end"
  style={{ width: "100%", height: 600 }}
/>
```

```js
const handleSelectedEvent = (event) => {
  setSelectedEmployee(
    myEmployees.items.filter((item) => item.id === event.resource.userId)[0]
  );
  setSelectedEvent(event);
  $("#calendar-event-modal").modal("show");
};
```
Using `jquery` here, as this project is Bootstrap, and it comes with `jquery`, so why not?

Regardless, the above is a bit-non standard as I'm using the resource to provide an ID for a user whose data will be used to partially populate the modal data.  That's the filter bit above.

End result is like this:

![image](https://user-images.githubusercontent.com/26792769/88284781-2f9dc780-cd18-11ea-9101-9bc23ffab946.png)

There are other ways to do this, obvioiusly.

I hope that helps someone.
