### ISSUE TITLE
Many events at the same time

### ISSUE THREAD

**Issue by ronmara** [jquense/react-big-calendar#1637]
#### Do you want to request a _feature_ or report a _bug_?
feature I think

#### What's the current behavior?
<img width="1321" alt="Screen Shot 2020-04-14 at 2 27 09" src="https://user-images.githubusercontent.com/11742944/79170233-744fc380-7df7-11ea-92b2-5f8b8a5004ea.png">

#### What's the expected behavior?
When I have a lot of events at the same time on day view, they are too small. Is there any way to expend the hour height and show all of the event one below another?

**Comment by cutterbl** [comment]
stale
