### ISSUE TITLE
Using onSelecting - How to tell when selecting has "Stopped"

### ISSUE THREAD

**Issue by ncarbon** [jquense/react-big-calendar#1642]
I want to fire a callback that handles an event creation based on the slot a user selects and drags. It looks like `onSelecting` is what I'd need. I tried it but the issue is that it fires a callback (opens a modal in my case) during the selection process, so it does so multiple times during the select and drag. I am not sure how to use onSelecting in this case. I'm thinking of adding an event listener for when mouse is released, is this the only option or does the react-big-calendar api provide a more straightforward solution?

**Comment by RodrigoSosa95** [comment]
I have the same question, did you find any solution?

**Comment by JakubTiimo** [comment]
Same question
