### ISSUE TITLE
How do i access `rbc-month-row` ? There is no row wrapper available 

### ISSUE THREAD

**Issue by yashsharma04** [jquense/react-big-calendar#1643]
#### Do you want to request a _feature_ or report a _bug_?
Discuss a feature
#### What's the current behavior?
There is no row wrapper available to take control of the entire row in month view 

#### What's the expected behavior?
Want control over `rbc-month-row`

**Comment by jquense** [comment]
not sure what you mean by "access", you can write some CSS if you need to style it

**Comment by yashsharma04** [comment]
Want control over the div which has `rbc-month-row`

**Comment by jquense** [comment]
there is not at the moment sorry
