### ISSUE TITLE
Multiple resources per event

### ISSUE THREAD

**Issue by alexhnar** [jquense/react-big-calendar#1649]
Hi

This is an awesome component, thanks! I'd like to be able to assign multiple resources to a single event and then render this in the resource view.

In my events object, I have an array of ids for each resource linked. This seems to prevent the event from rendering. If I change this to a single ID string it works fine.

Has anyone managed to make this work?

Cheers
Alex

**Comment by ELI7VH** [comment]
Could this please be implemented? 

I have also had to iterate thru my events and create multiples based on resources in an event. seems crazy to have to duplicate data this much.

**Comment by mitsol** [comment]
As I'm also interessted in allocating multiple resources to an event, i started changing the code.

Basically what i did, I modified the `groupEvents(events)` method in `src/utils/Resources.js` to

```js
    groupEvents(events) {
      // console.log("groupEvents",events);
      const eventsByResource = new Map()

      if (!resources) {
        // console.log("no resources");
        // Return all events if resources are not provided
        eventsByResource.set(NONE, events)
        return eventsByResource
      }

      events.forEach(event => {
        const id = accessors.resource(event) || NONE

        //split up if it is an array
        if (Array.isArray(id)) {
          id.forEach(item => {
            let resourceEvents = eventsByResource.get(item) || []
            resourceEvents.push(event)
            eventsByResource.set(item, resourceEvents)
          })
        } else {
          let resourceEvents = eventsByResource.get(id) || []
          resourceEvents.push(event)
          eventsByResource.set(id, resourceEvents)
        }
      })
      // console.log("eventsByResource", eventsByResource);
      return eventsByResource
    },
```

this allows then to show the event in all allocated resources. This then works for both, events with resources as id or array of ids:

```js
    {
      id: 2,
      title: 'Team lead meeting',
      start: new Date(2018, 0, 29, 8, 30, 0),
      end: new Date(2018, 0, 29, 12, 30, 0),
      resourceId: [3,2],
    },

Any other suggestions?
    {
      id: 11,
      title: 'Birthday Party',
      start: new Date(2018, 0, 30, 7, 0, 0),
      end: new Date(2018, 0, 30, 10, 30, 0),
      resourceId: 1
    },
```

**Comment by basstager** [comment]
@jquense or @cutterbl Any chance my latest PR to this issue (https://github.com/jquense/react-big-calendar/pull/2405) could be reviewed? Very much appreciated!

**Comment by Lavanya-ipro** [comment]
Hello team is it possible resource group scheduler timeline view events using react big calendar like below view
![scheduler](https://github.com/user-attachments/assets/6e1e9dc3-5fc0-4934-9bf9-5cea6d257293)

if has any possiblity can some provide links with react big calendar pls

**Comment by cutterbl** [comment]
@Lavanya-ipro As of now, no one has yet submitted a PR that would allow for a horizontal resource view
