### ISSUE TITLE
Reoccurring Events (yearly)

### ISSUE THREAD

**Issue by AEDesigns** [jquense/react-big-calendar#1654]
#### Do you want to request a _feature_ or report a _bug_?
Feaures
#### What's the current behavior?
Is there functionality currently for events that happen yearly (birthdays, anniversaries, etc)? I've been reading through the docs and am having a hard time pinning it down if so. 

Thanks!

**Comment by jquense** [comment]
thee is no builtin functionality for reoccurring events, since how they are implementing is usually app specific
