### ISSUE TITLE
Not possible to resize event for 2 dates

### ISSUE THREAD

**Issue by AIvanov22** [jquense/react-big-calendar#1658]
#### Do you want to request a _feature_ or report a _bug_?
Bug
#### What's the current behavior?
If the event in the week view takes two days, then it is not possible to change the size of the event up. Resizing an event down works.

![Screencast-2020-05-12-161202](https://user-images.githubusercontent.com/47416368/81696598-cb839b00-946c-11ea-9b6d-3a613f973b8b.gif)

#### What's the expected behavior?
Resize working correctly.

**Comment by cutterbl** [comment]
resolved
