### ISSUE TITLE
Change the first day of the week to Monday

### ISSUE THREAD

**Issue by Angelk90** [jquense/react-big-calendar#1661]
Hi @jquense,
I would like to make sure that the calendar starts as the first day on Monday and the last day on Sunday.

How can I do?

**Comment by azouaoui-med** [comment]
that's a moment configuration 

```
moment.updateLocale("en", { week: {
  dow: 1, // First day of week is Monday
  doy: 4  // First week of year must contain 4 January (7 + 1 - 4)
}});
```

you can read more here [https://momentjscom.readthedocs.io/en/latest/moment/07-customization/16-dow-doy/](https://momentjscom.readthedocs.io/en/latest/moment/07-customization/16-dow-doy/)

**Comment by Angelk90** [comment]
@azouaoui-med : Do you know how I can change the language of the days according to the selected language? #1660
