### ISSUE TITLE
how to show a range of months?

### ISSUE THREAD

**Issue by chesiri** [jquense/react-big-calendar#1662]
#### Do you want to request a _feature_ or report a _bug_?
_feature_ 

Hi, i need show a calendar with **N** quantity of months.

or rather a **range of months**: 

```[march, june, july]```

Any idea?

**Comment by jquense** [comment]
Hi there, this isn't supported, you'd have to build your own month custom view to handle it if you want that behavior

**Comment by chesiri** [comment]
jquense, thank for your response.
Can you tell me how to do it?

thanks

**Comment by jquense** [comment]
sure! read through the source code, especially how the Month view is implemented and how the calender  `view` Prop allows custom components, build something that suits your needs
