### ISSUE TITLE
Is it possible to show "show more" button on a day with two event?

### ISSUE THREAD

**Issue by pikama** [jquense/react-big-calendar#1663]
I know it wouldn't show "+1 more" because both of them occupy two row on showing two event and one event with "+1 more" button.

I want to change the event design that user can add a picture to event. It is not enough space to show two or more event so need to display "show more" button to let user watch all the event in popup box.

Is there a way to fulfill this issues?

![up](https://user-images.githubusercontent.com/34977908/82199112-da1bf780-992f-11ea-87fc-cdc878d2feed.png)

Thanks

**Comment by jquense** [comment]
It's not possible, `show more ` is based on available space, not number of events. It's a function of the layout styling, there are a few past issues about this that might be useful if you can fine them
