### ISSUE TITLE
Use of custom layout functions

### ISSUE THREAD

**Issue by tomtom5152** [jquense/react-big-calendar#1664]
According to [DayEventLayout](https://github.com/jquense/react-big-calendar/blob/v0.24.6/src/utils/DayEventLayout.js#L16) it is possible to provide the calendar with a custom layout function via prop, although this usage is completely undocumented. 

In implementing TypeScript prop and function type definitions the lack of documentation has caused the review team [to wonder](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44708#issuecomment-629144300) if this is an intended use case of the implementation, or if the ability to do this is just an unintended side effect of how it has been implemented.

Or, in less verbose terms, is the ability to use a custom layout function a feature stable, but otherwise undocumented API or is it subject to change and for internal use only?

**Comment by jquense** [comment]
It's stable and a public API. It's just undocumented maybe b/c the docs haven't been deployed in a while I'm not sure

**Comment by tomtom5152** [comment]
Perfect thank you, I shall close this issue then as there are others tracking the status of documentation for things.
