### ISSUE TITLE
Duplicate event shows randomly when resizing calendar event

### ISSUE THREAD

**Issue by vdamrongsri** [jquense/react-big-calendar#1666]
#### Do you want to request a _feature_ or report a _bug_?
Report a bug
#### What's the current behavior?
When resizing an event in the `month` view that has a `start` date on a Sunday or Saturday (at the far left side or right side of calendar), a duplicate event appears.

Video file url of bug:
https://staging.cdn.oriio.io/vano/staging/1589911573920967417/rbc-resize-event-bug.mov

#### What's the expected behavior?
When resizing an event no duplicate event should appear.

**Comment by ksk6794** [comment]
@hawaiiansurfer, Did you manage to solve the problem?
I got a similar effect.

![Screen Recording 2020-06-19 at 16 22 06](https://user-images.githubusercontent.com/19248059/85137538-0cc85100-b24a-11ea-87f9-b788912e9a58.gif)

**Comment by hawaiiansurfer** [comment]
@ksk6794 no, I have not managed to workaround it and haven't diven into the code yet. for now, this feature doesn't seem to be production ready as it has multiple bugs

**Comment by ksk6794** [comment]
@hawaiiansurfer I created a bug report with a detailed case description
https://github.com/jquense/react-big-calendar/issues/1683

**Comment by cutterbl** [comment]
Closing this, moving all discussion to #1683
