### ISSUE TITLE
rbc-current-time-indicator - all week view

### ISSUE THREAD

**Issue by telltokichu** [jquense/react-big-calendar#1670]
#### Do you want to request a _feature_ or report a _bug_?
It is a feature
#### What's the current behavior?
rbc-current-time-indicator is highlighted only in current day

#### What's the expected behavior?
I need to show the rbc-current-time-indicator full line throughout the week like Outlook Indicator.

Any workaround ? 
It would be very helpful to others also.
Thanks in advance.

**Comment by ChristmasWoe** [comment]
@telltokichu Hi, have you found any work around?

**Comment by flackeryy** [comment]
same!

**Comment by BanshiCES** [comment]
any update on it?

**Comment by adamkjall** [comment]
Here is a workaround if anyone's interested :) 

This code is run after the react-big-calendar is mounted and needs to be rerun if you change between views, i'd put it in the same file as react-big-calendar and let it run each render to make sure it's always doing it's job

```
export const updateTimeIndicator = (view) => {
  const timeIndicator = document.querySelector('.rbc-current-time-indicator');

  if (timeIndicator) {
    const nDayOfWeek = dayjs().day();
    let left;
    let width;

    if (view === VIEWS.DAY) {
      left = 0;
      width = 100;
    } else {
      left = (nDayOfWeek - 1) * -100;
      width = 700;
    }

    timeIndicator.style.setProperty('--width', `${width}%`);
    timeIndicator.style.setProperty('--left', `${left}%`);
  }
};
```

and you also need to modify your css/scss for the class "rbc-current-time-indicator", the ::before just adds a circle to the left of the indicator, so you can discard that if you only want a straight line

```
.rbc-current-time-indicator {
  --left: 0%;
  --width: 100%;
  position: absolute;


  left: var(--left);
  width: var(--width);
  z-index: 5;
  height: 1px;
  border: 1px dashed $current-time-color;
  pointer-events: none;

  &::before {
    display: inline-block;
    content: '';
    background-color: $current-time-color;
    width: 12px;
    height: 12px;
    border-radius: 50%;
    margin-left: -12px;
    margin-bottom: 12px;
    margin-top: -6px;
  }
}

```

**Comment by abdulhussain111** [comment]
just add this into your css file 

.rbc-current-time-indicator {
  left: -1500px;
}

the left position should be something that covers the whole week. that's it
