### ISSUE TITLE
Event Listener does function when it loaded

### ISSUE THREAD

**Issue by rafaelparayno** [jquense/react-big-calendar#1672]
My browser is Chrome 
react-big-calendar version 6.13.1
#### What's the current behavior?
when the big react calendar loaded the event listener does not trigger when it started I have to click the next button then go back to the current month and the action event can now function.
<!--

#### What's the expected behavior?

When the component loaded. The event listener can be trigger once i done something when it started

**Comment by KhaledMohamedP** [comment]
@rafaelparayno which event listener? can you be more specific please?

**Comment by rafaelparayno** [comment]
The onEventDrop as well onSelectEvent.
