### ISSUE TITLE
Dynamically change timeslot height

### ISSUE THREAD

**Issue by vAskitsa** [jquense/react-big-calendar#1673]
Do you want to request a _feature_ or report a _bug_?
feature
#### What's the current behavior?
I may be asking for the moon but i have following situation and i hope someone can give me ideas.
If this is wrong place to ask it i'll delete my post.

I generate dynamically events to my calendar for example with timeslot range 38 and step 38(like in picture). But when i have custom size event which not fit in timeslot i cant draw new event below it.
Like in picture my dragging is forced to start 08:32 or 09:10 and then i have to manually set time to get new event fit in empty space.

![rbcslot](https://user-images.githubusercontent.com/44556897/83276244-ff82ee00-a1d8-11ea-8476-10d705eb0ac4.PNG)

Which is the best solution?

-Set my step attribute to be 1 minute?
this allow me start dragging where i want but it will decrease usability a lot. I want add new events with one click because my event size is constant(expect these exceptions that cause this issue).
Also 1 minute step attribute cause performance issue although not so big.

-I have popup which allow set time manually when click event but it will decrease usability more.

-In some way get time slot detect event size and wrap it(update calendar grid when custom size event occurs).

-Other better solution which did not come to my mind.

I think there are no proper solution because it would be hard to implement efficiently.
I noticed that this happen also with Google calendar if your meeting end for example 12:11 and you want add event to start right after it.
I know my case is little unusual but there's no shame in asking(:.
#### What's the expected behavior?

Optional feature make timeslot wrap event.

**Comment by KhaledMohamedP** [comment]
@vAskitsa, 

I'm having little trouble understanding your request, but having a 1 minute slots could skew the calendar and increase its height. 

I'll recommend sticking with 5 minutes slots and having an option to change the time in the popup modal. This way you get the best of the two worlds.

**Comment by vAskitsa** [comment]
Sorry if my request is unclear my weak english cause it.
I said 1 minute "step" not "slot" and i already have it and it not skew the calendar.
User is allowed to set step and slot size in my software and i also have this popup modal which open when event is clicked and allow you set time.
I think i am asking too much. I should set step to be one minute which is annoying when i have to be so accurate when draw events.
