### ISSUE TITLE
selectableState = true for some events and = false for other events

### ISSUE THREAD

**Issue by alyshahudson** [jquense/react-big-calendar#1675]
how do I make some of the events static and others reactive on the draggable calendar (for example, if I want to display an appointment and not allow the user to move or delete it)

**Comment by cutterbl** [comment]
Use the [draggableAccessor](http://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/addons-drag-and-drop-props--draggable-accessor) to control which events can and can not be dragged.
