### ISSUE TITLE
How to highlight selected day or days in react big calendar

### ISSUE THREAD

**Issue by idomiralin** [jquense/react-big-calendar#1678]
#### What's the expected behavior?
I would like to be able to highlight the selected days in react big calendar.

I have tried using onSelectSlot, but it doesn't change the color for example.

                    <Calendar
                            selectable={true}
                            popup
                            localizer={localizer}
                            events={events}
                            startAccessor="start"
                            endAccessor="end"
                            components={{
                                dateCellWrapper: ColoredDateCellWrapper
                            }}
                            style={{
                                display: 'flex',
                                paddingTop: '20px',
                                height: '75vh',
                            }}
                            onSelectSlot={handleSlotSelection}
                        />

                     const handleSlotSelection = ({ start, end, action }) => {
                          return  { style: { backgroundColor: 'red' } };
                     };

**Comment by cutterbl** [comment]
You select events, or a slot, not a specific day. That said, you can, maybe, use the `slotPropGetter` to apply custom slot styling for a specific day.

**Comment by Zarogon** [comment]
You can use custom dateCellWrapper
`import React, { Children } from 'react';
import PropTypes from 'prop-types';

export const DateCellWrapper = (props, selected) => {
    const { children, value } = props;
    const isSelected = new Date(value).valueOf() === new Date(selected).valueOf();
    const isPastDay = new Date(value).valueOf() < new Date().valueOf();

    return React.cloneElement(Children.only(children), {
        style: {
            ...children.style,
            backgroundColor: isSelected ? '#DEECF9' : isPastDay ? '#fbfcfd' : 'white',
            borderRight: `1px solid #e5e9f0`,
            borderBottom: `1px solid #e5e9f0`,
        },
    });
};

DateCellWrapper.propTypes = {
    selected: PropTypes.any.isRequired,
};`
