### ISSUE TITLE
Events not rendering on Safari with "events" prop

### ISSUE THREAD

**Issue by jodelat** [jquense/react-big-calendar#1680]
#### What's the current behavior?
Google Chrome works fine but on Safari the events array dont render on the calendar.

Here is an example of one the objects in the list.

        let eventObject = {
          id: event.id,
          start: new Date(event.start_datetime),
          end: new Date(event.end_datetime),
          title: event.name,
          results: event.results,
          clients: event.clients,
          eventUsers: event.event_users,
          meetings: event.meetings,
          groupType: event.group_type,
          sessionType: event.event_type,
          createdBy: event.created_by
        };

**Comment by cutterbl** [comment]
I'm seeing all of the events displayed correctly, in Safari, from the [documentation site](https://jquense.github.io/react-big-calendar/examples/index.html). Maybe the issue is something in your local implementation?

**Comment by arturormk** [comment]
This is more than a year old, but I just stumbled upon the same problem.

Your code is assuming that the Date constructor can take an ISO YYYY-MM-DD format string, but this is not standard and Safari does not support it. See [https://stackoverflow.com/questions/4310953/invalid-date-in-safari](https://stackoverflow.com/questions/4310953/invalid-date-in-safari).

To ensure compatibility, you can use datefns.parseISO like this:

```
import parseISO from 'date-fns/parseISO';
// ...
start: parseISO(event.start_datetime),
end: parseISO(event.end_datetime),

```
