### ISSUE TITLE
No overload matches this call.

### ISSUE THREAD

**Issue by coolvijaymca** [jquense/react-big-calendar#1692]
Hi All trying to use Big Calendar in my project and created a yearly view, however receiving error while mention views in 

Version : 0.20.4
`
import BigCalendar from 'react-big-calendar';
import 'react-big-calendar/lib/css/react-big-calendar.css';

 <BigCalendar
                      views={{ week: true, day: true, year: Year }}// Error on this line               
                      localizer={localizer}
                      selectable
                      events={this.state.eventData}
                      startAccessor="EventDate"
                      endAccessor="EndDate"
                      eventPropGetter={this.eventStyleGetter}
                      onSelectSlot={this.onSelectSlot}
                      components={{
                        event: this.renderEvent
                      }}
                      onSelectEvent={this.onSelectEvent}
                      defaultDate={moment().startOf('day').toDate()}
                      messages={
                        {
                          'today': strings.todayLabel,
                          'previous': strings.previousLabel,
                          'next': strings.nextLabel,
                          'month': strings.monthLabel,
                          'week': strings.weekLabel,
                          'day': strings.dayLable,
                          'showMore': total => `+${total} ${strings.showMore}`
                        }
                      }
                    />`

Error is 

(JSX attribute) views?: Views
No overload matches this call.
  Overload 1 of 2, '(props: Readonly<BigCalendarProps<any, object>>): BigCalendar<any, object>', gave the following error.
    Type '{ week: true; day: true; month: true; }' is not assignable to type 'Views'.
      Type '{ week: true; day: true; month: true; }' is missing the following properties from type '{ day: boolean | SFC<{}> | Component<{}, {}, any>; agenda: boolean | SFC<{}> | Component<{}, {}, any>; month: boolean | SFC<{}> | Component<{}, {}, any>; week: boolean | ... 1 more ... | Component<...>; work_week: boolean | ... 1 more ... | Component<...>; }': agenda, work_week
  Overload 2 of 2, '(props: BigCalendarProps<any, object>, context?: any): BigCalendar<any, object>', gave the following error.
    Type '{ week: true; day: true; month: true; }' is not assignable to type 'Views'.
      Type '{ week: true; day: true; month: true; }' is missing the following properties from type '{ day: boolean | SFC<{}> | Component<{}, {}, any>; agenda: boolean | SFC<{}> | Component<{}, {}, any>; month: boolean | SFC<{}> | Component<{}, {}, any>; week: boolean | ... 1 more ... | Component<...>; work_week: boolean | ... 1 more ... | Component<...>; }': agenda, work_weekts(2769)
index.d.ts(258, 5): The expected type comes from property 'views' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<BigCalendar<any, object>> & Readonly<{ children?: ReactNode; }> & Readonly<...>'
![Cal-error](https://user-images.githubusercontent.com/27564614/86165430-410cfe80-bae1-11ea-8a2a-197fea6221b5.png)

index.d.ts(258, 5): The expected type comes from property 'views' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<BigCalendar<any, object>> & Readonly<{ children?: ReactNode; }> & Readonly<...>'

**Comment by jquense** [comment]
Follow the instructions in the error, your `views` object is missing keys
