### ISSUE TITLE
Customize event row

### ISSUE THREAD

**Issue by Angelk90** [jquense/react-big-calendar#1698]
#### Do you want to request a _feature_ or report a _bug_?
Not a bug or feature May be a help

#### What's the expected behavior?

@jquense : 
I would like to customize this component, for example put an icon before the title.

![image](https://user-images.githubusercontent.com/20476002/87040442-fe3ddb80-c1f0-11ea-9f7d-8c660a036314.png)

```
const events = result.map((ev, id) => ({
    id,
    title: ev.title,
    allDay: false,
    start: new Date(ev[0].from),
    end: new Date(ev[0].to),
    backgroundColor: `#${(((1 << 24) * Math.random()) | 0).toString(16)}`,
    icon: <DirectionsBoat />
  }));
```

```
      <Calendar
        className="flex flex-1 container"
        components={{
          event: _props => {
            console.log(_props);
            return (
              <>
                {_props.event.icon}
                {_props.title}
              </>
            );
          }
        }}
      />
```

**Comment by vAskitsa** [comment]
You can render html content in event with 'titleAccessor' (http://jquense.github.io/react-big-calendar/examples/index.html).
You can return for example `<div><MyIcon/><p>{ev.title}</p></div>` from 'titleAccessor'.

**Comment by cutterbl** [comment]
For even greater control, you can write a custom override Event component, and even define different ones for different views.
