### ISSUE TITLE
Calendar start time is not accurate

### ISSUE THREAD

**Issue by Wgil** [jquense/react-big-calendar#1701]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?
Event start time is not accurate if the end date is after 23:30.

https://codesandbox.io/s/sweet-sanderson-hkbm7?file=/src/App.js

#### What's the expected behavior?
Event start time should match the event object.

**Comment by vAskitsa** [comment]
I opened related issue in June https://github.com/jquense/react-big-calendar/issues/1674.

You can workaround with setting your step attribute of the calendar to be one minute.

**Comment by Wgil** [comment]
Thanks, although it works, such a big calendar doesn't work for me

**Comment by Wgil** [comment]
@vAskitsa above example gets fixed if I change to 15 minutes steps. Did you find the same issue with  `step > 1`?

**Comment by vAskitsa** [comment]
@Wgil it seems to depended on relation between 'timeslot' and 'step' attributes.

When i have step 15 slot 30 it works but if i have step 15 and slot 45 error appears.
I try to find time to create pull request to fix this. I did't detect reason for this from source yet.

**Comment by sudhamab** [comment]
for us step 15 and timeslots 30 doesn't work either. is there a difference between the slots prop and timeslots?

**Comment by cutterbl** [comment]
The [timeslots](http://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/props--timeslots) prop and the [step](http://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/props--step) prop are two differ things. There is no 'slots' prop.
