### ISSUE TITLE
Event width is 85%

### ISSUE THREAD

**Issue by kamran-afsar** [jquense/react-big-calendar#1704]
#### I have a scenario where i have to show multiple slots on same time but they seems to be overlapping
in my case i have to design slots with some opacity and color. the first event slot appears to be 85% and rest are 50% see attached image
![image](https://user-images.githubusercontent.com/33418636/87636208-d652f880-c759-11ea-8865-d14a5d72d734.png)

**Comment by erkib** [comment]
There seems to be undocumented parameter of the Calendar component: dayLayoutAlgorithm
Found this from src, in Calendar.js:
/**
     * A day event layout(arrangement) algorithm.
     * `overlap` allows events to be overlapped.
     * `no-overlap` resizes events to avoid overlap.
     * or custom `Function(events, minimumStartDifference, slotMetrics, accessors)`
     */
    dayLayoutAlgorithm: DayLayoutAlgorithmPropType,
**/
What you would like to use, is 'no-overlap'.

**Comment by kamran-afsar** [comment]
You are my hero

**Comment by kamran-afsar** [comment]
You are my hero
