### ISSUE TITLE
callback for stoping onSelecting and onEventResize (on press esc or mouseup outside of the calendar)

### ISSUE THREAD

**Issue by mikeyyyzhao** [jquense/react-big-calendar#1705]
#### Do you want to request a _feature_ or report a _bug_?
Request a feature

#### What's the current behavior?
There's a call back for selecting time slots and for creating events from that selection (onSelectSlot). However, there's no way to know if the user exited selecting time slot if they pressed esc or mouseup outside of the calendar. It'd also be nice to have a callback on pressing esc or exiting out of onEventDrop and onEventResize.

#### What's the expected behavior?
There's a call back when the user stops moving/resizing an event or selecting time slots (from drop, onmouseup, or from pressing esc)

**Comment by nitzanmo** [comment]
Did you find a work around?
