### ISSUE TITLE
Not handling empty events list

### ISSUE THREAD

**Issue by javiemgz** [jquense/react-big-calendar#1708]
When no list of event is sent it throws an error.
<Calendar
    localizer={localizer}
    events={[]} //easy fix
    startAccessor="start"
    endAccessor="end"
/>

This should be handled, having the empty list as default.
This bug appears when I was testinting the component for the first time, still not handled my events.

If i can help in something mi mail es javiemgz@gmail.

**Comment by ferencbenko** [comment]
I'm also experiencing this issue with version 0.39.3
