### ISSUE TITLE
Current Time Indicator

### ISSUE THREAD

**Issue by telltokichu** [jquense/react-big-calendar#1709]
#### Do you want to request a _feature_ or report a _bug_?
Feature
#### What's the current behavior?
In Week view
![image](https://user-images.githubusercontent.com/25656723/87898895-1de4c780-ca6d-11ea-8006-f2a333621f8c.png)

#### What's the expected behavior?
How to achieve this ? 
![image](https://user-images.githubusercontent.com/25656723/87898971-5389b080-ca6d-11ea-8ea6-feb71dbafd15.png)

**Comment by dargue3** [comment]
It's already implemented in react-big-calendar, [in the example](http://jquense.github.io/react-big-calendar/examples/index.html#basic), click the `Today` button and you'll see a very thin green line. Style this however you like by targeting the CSS class, `rbc-current-time-indicator`.
