### ISSUE TITLE
Failed to compile while using react-big-calendar

### ISSUE THREAD

**Issue by sunilwgt** [jquense/react-big-calendar#1715]
Im using react big calendar for event , Its giving error.

Error:
Module not found: Error: Can't resolve 'dom-helpers/addClass' in 'E:\tripvalet\memnew\tripvalet-yep-members-e6ce6bf2963f\node_modules\react-big-calendar\dist'

Code:
import React, { useState, FunctionComponent } from 'react';
import './index.css';

import calendarimage from '../../../global/images/calendarimage.png';

import { Calendar, momentLocalizer } from 'react-big-calendar'
import moment from 'moment'

const localizer = momentLocalizer(moment)

const Events = () => {

  return (
    <div>
      <Calendar
        localizer={localizer}
        // events={myEventsList}
        startAccessor="start"
        endAccessor="end"
        style={{ height: 500 }}
      />
    </div>

  )

};

export default Events;

Please Help.

**Comment by brianmwadime** [comment]
>Im using react big calendar for event , Its giving error. ...

@sunilwgt did you manage to find a fix for this?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by brianmwadime** [comment]
> ...

@brianmwadime ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BRHGreen** [comment]
Hey. Did you ever figure this out? I'm having the same issue. Cheers.

**Comment by anandrikka** [comment]
@BRHGreen I'm facing a similar issue, did you resolve the issue? If you resolved it, can you let me know how you did it?
