### ISSUE TITLE
Wrong event display upon timezone change

### ISSUE THREAD

**Issue by kevinRoomies** [jquense/react-big-calendar#1716]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?

When I'm using my local timezone, event is displayed at the correct time.
I changed my local timezone using Change Timezone from the chrome store to check if the event would be displayed with the correct time for this timezone.
Result is that, the event do feature the correct times (6PM-8PM in GMT+2 to 5AM-7AM in GMT+13) but it does not display correctly on the calendar (here stuck in 12AM when in GMT+13).
My start and end are Date object built using ISO 8601 strings including a timezone.
GMT +2 (original timezone, no change)
![image](https://user-images.githubusercontent.com/65670017/88945728-d7079500-d2ea-11ea-8e12-733e233d524e.png)

GMT +13
![image](https://user-images.githubusercontent.com/65670017/88943537-e4d9fd80-d28b-11ea-9e67-067beae046d9.png)

#### What's the expected behavior?

Have my event from 5AM to 7AM display correctly from 5AM to 7AM in the day/week view.

**Comment by jalejandro0211** [comment]
same issue

**Comment by cutterbl** [comment]
[Here was my CodeSandbox](https://codesandbox.io/s/rbc-timezones-91wx3) at doing timezone support. What I found was that, internally, RBC doesn't handle timezone switching due to how it's not using the passed in localizer for date construction building the actual calendar (not events) display itself, but rather only really used for the number, header formatting stuff.

**Comment by cutterbl** [comment]
See documentation on [Dealing with Timezones](http://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/guides-timezones--page)

**Comment by iaminamcom** [comment]
You solved this issue?

**Comment by cutterbl** [comment]
@iaminamcom I did. See that link from May 2022
