### ISSUE TITLE
Issue with local timezone display

### ISSUE THREAD

**Issue by srijakumar** [jquense/react-big-calendar#1720]
Similar to the closeed issue - "Timezone support #118[Issue](https://github.com/jquense/react-big-calendar/issues/118) " the react big calendar when displayed shows a day back due to local time conversion. I have tried the solutions mentioned in #118 but didnt work for me. Any recommendations? Thanks!

`import React from 'react'
import {connect} from 'react-redux'
import {deleteNote} from '../actions/deleteNote'

import { Calendar, momentLocalizer, Views } from 'react-big-calendar';
import moment from 'moment';
import moment_timezone from 'moment-timezone';
import 'react-big-calendar/lib/css/react-big-calendar.css';

const localizer = momentLocalizer(moment)

const Notes = (props) => {
  console.log("this is props in Notes.js", props)
  const handleDelete = (note) => {
    props.deleteNote(note.id, note.tracker_id)
  }
    const updateEvents = (notes) => {
      debugger
      let notesArray = []
      notes.map(noteEditted => {
        let note = {
            title: "X",
            start: noteEditted.date,
            end: noteEditted.date
          }
          notesArray.push(note)
        })
        console.log("This is notesArray", notesArray)
        return notesArray
      }
  return (
    <div className="Notes">
      {props.notes && props.notes.map(note =>
        <li key={note.id}>{note.content} - {note.date} <button className="Button" onClick={() => handleDelete(note)}>Delete</button></li>
      )}
      <br/>
      <div className="app-side-bar">
        <Calendar
          selectable
          localizer={localizer}
          events={updateEvents(props.notes)}
          defaultDate={moment().toDate()}
         />
      </div>
    </div>
  )
}
export default connect(null,{deleteNote})(Notes)`

**Comment by srijakumar** [comment]
This is my return statement - it seems to be formatted weird above due to the li and br tags


return (
    <div className="Notes">
      {props.notes && props.notes.map(note =>
        <li key={note.id}>{note.content} - {note.date} <button className="Button" onClick={() => handleDelete(note)}>Delete</button></li>
      )}
      
      <div className="app-side-bar">
        <Calendar
          selectable
          localizer={localizer}
          events={updateEvents(props.notes)}
          defaultDate={moment().toDate()}
         />
      </div>
    </div>

  )

**Comment by cutterbl** [comment]
See our documentation on [Dealing with Timezones](http://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/guides-timezones--page)
