### ISSUE TITLE
Typescript definition error

### ISSUE THREAD

**Issue by mitsol** [jquense/react-big-calendar#1725]
I think there is an error in the ts-defnition for `withDragAndDropProps`-Interface (file: `@types/react-big-calendar/lib/addons/dragAndDrop.d.ts`)

The following two methods are using `allDay: boolean` as an argument, but it should be `isAllDay: boolean` instead:

```js
onEventDrop?: (args: { event: TEvent, start: stringOrDate, end: stringOrDate, allDay: boolean }) => void;
onEventResize?: (args: { event: TEvent, start: stringOrDate, end: stringOrDate, allDay: boolean }) => void;
```

**Comment by lenehan2** [comment]
@mitsol this is updated in the latest release
```@types/react-big-calendar@0.30.1```
