### ISSUE TITLE
dateFnsLocalizer is not working

### ISSUE THREAD

**Issue by pig800509** [jquense/react-big-calendar#1726]
```jsx
const locales = {
  'zh-TW': require('date-fns/locale/zh-TW'),
}
```
my package.json
```json
"date-fns": "^2.15.0",
"react-big-calendar": "^0.26.0",
"typescript": "~3.7.2"
```
It always show en-US in calendar. It that bug?

**Comment by atomoc** [comment]
I have this same problem

**Comment by efflam** [comment]
You should pass  `culture={"zh-TW"}` as a prop to `<Calendar/>`

**Comment by serrg** [comment]
> @pig800509 You should pass `culture={"zh-TW"}` as a prop to `<Calendar/>`

Does not work, it causes:  `Uncaught RangeError: locale must contain localize property`

```
"react-big-calendar": "^0.28.0",
"date-fns": "^2.16.1",
```

**Comment by MrBlue9** [comment]
Try importing the locale object via namespace import

`import { zhTW } from 'date-fns/locale'`

and then using it like this:

```
const locales = {
  'zh-TW': zhTW
}
```

**Comment by serrg** [comment]
> Try importing the locale object via namespace import

It works now: https://codesandbox.io/s/fast-breeze-ckmf4

**Comment by FeMaffezzolli** [comment]
> Try importing the locale object via namespace import
> 
> `import { zhTW } from 'date-fns/locale'`
> 
> and then using it like this:
> 
> ```
> const locales = {
>   'zh-TW': zhTW
> }
> ```

Thanks @MrBlue9 , it works!

**Comment by cutterbl** [comment]
stale

**Comment by Warmachine13** [comment]
Add this line culture on example on README
