### ISSUE TITLE
Change week view to show by day

### ISSUE THREAD

**Issue by MateusSRocha** [jquense/react-big-calendar#1728]
![image](https://user-images.githubusercontent.com/49770358/90280510-6d869b00-de41-11ea-9186-5b118e26bc53.png)

Do you have any properties to change the week view, to show by day instead of by room?

**Comment by Lunke** [comment]
Hello @MateusSRocha. Did you find a solution to this problem?

**Comment by MateusSRocha** [comment]
Yes, I forked repository and create custom TimeGrid and TimeGridHeader to work week view.
I just inverted the order of TimeGridHeader's content, keeping the same CSS.

**Comment by MateusSRocha** [comment]
![image](https://user-images.githubusercontent.com/49770358/90772711-50335000-e2cb-11ea-87d4-91931a90015e.png)

**Comment by Lunke** [comment]
That is exactly what I am looking for! Would you mind sharing a code example?

**Comment by MateusSRocha** [comment]
You can also use it: https://www.npmjs.com/package/@omnicodesolutions/react-big-calendar
Basically, if you use the work-week view, it will be configured to use days above the rooms. This is contained in the files: WeekTimeGridHeader and WeekTimeGrid

**Comment by Lunke** [comment]
Thank you Mateus! How about creating a pull request though? I think this would be a great feature to have @jquense.

**Comment by MateusSRocha** [comment]
I think it is a good idea, but it is necessary to leave it open to anyone who is going to use the choice between this version and the previous one with rooms over days, and at the moment it is not.
