### ISSUE TITLE
Event appears 1 hour early when event ends in last hour of day (step={60})

### ISSUE THREAD

**Issue by jpacker-rf** [jquense/react-big-calendar#1730]
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?

When I set step (i.e. step={60}) and when I have and event that ends in the last hour of the day (i.e. 11:30) I am noticing some weird behavior in the week view.  The time is displaying correctly but the event block on the calendar shows up 1 hour earlier on the calendar.  For example, if an event starts at 10:30pm and ends at 11:30pm, the event will display on the calendar from 9:30-11:30. 

![Screen Shot 2020-08-19 at 1 02 52 PM](https://user-images.githubusercontent.com/60358126/90678726-4ef71a00-e21c-11ea-8d21-08b16b6bbe72.png)

(see codepen: https://codepen.io/jpacker/pen/VwaKXKP)

We are using react-big-calednar 0.24.6.  Tested in Chrome and Safari

#### What's the expected behavior?

When an event ends in the last hour of the day, it should show up with the correct start time

**Comment by sudhamab** [comment]
this is an issue for us as well. can someone please help with this?

**Comment by jpacker-rf** [comment]
@cutterbl Has this issue been resolved?  Which version fixes this issue?
