### ISSUE TITLE
Change start of work week from Mon to current day

### ISSUE THREAD

**Issue by mikema92** [jquense/react-big-calendar#1737]
I just came across this library and was trying to recreate a workweek view we had when migrating from angular to react. Our work week view started from the current day and ends on the prev day of next week.

So take today 8/25 Tues for example. Ideally we want the view to be 8/25 Tues, 8/26 Wed, 8/27 Thurs, 8/28 Fri, and 8/31 Mon. Do I change this in the localizer with work week view? A code snippet is greatly appreciated.

**Comment by jquense** [comment]
yes you can change this in the localizer. please see past issues for perhaps more context. thanks!

**Comment by KeiShadow** [comment]
If you dont know how, you can do it like this: 
`	};
	const sOfWeek = () => startOfWeek(new Date(), { weekStartsOn: getDay(new Date()) });
	const localizer = dateFnsLocalizer({
		format,
		parse,
		startOfWeek: sOfWeek,
		getDay,
		locales,
	});`
im using it in week view with date fns.
