### ISSUE TITLE
Extra day because fall back time change

### ISSUE THREAD

**Issue by juanruben** [jquense/react-big-calendar#1742]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?
In the Santiago time zone, when the fall back time change occurs, the calendar duplicates the Saturday column.  This causes the entire month to become misaligned.

<img width="961" alt="Screen Shot 2020-09-04 at 14 05 58" src="https://user-images.githubusercontent.com/7572389/92272437-853cc680-eeb7-11ea-86d4-b9f554d7b06e.png">

#### What's the expected behavior?
I would like to disable locale configurations

**Comment by cutterbl** [comment]
resolved
