### ISSUE TITLE
How to change color of the day (rbc-date-cell)

### ISSUE THREAD

**Issue by Fornori** [jquense/react-big-calendar#1744]
#### Do you want to request a _feature_ or report a _bug_?

I want to change the color of the day (rbc-date-cell) to Red for a weekend day. How can I Do this?

**Comment by cutterbl** [comment]
You can use the `eventPropGetter` to conditionally add classes or styles to an event, so you can check the `event.start`, see if it falls on a weekend day, and apply custom styling.
