### ISSUE TITLE
Problem with 1st weekend September Month 

### ISSUE THREAD

**Issue by nakiopls** [jquense/react-big-calendar#1746]
#### Bug

At the beginning of each weekend in September,
it is repeated on Saturday, altering the entire remaining month.
I attach images about it.

Environment in which I am working:

-in ruby ​​ruby-2.5.5

-react 16.03

-react-big-calendar: 0.24.1

![september_2022](https://user-images.githubusercontent.com/29529042/92418400-ae6e8880-f13d-11ea-8432-491b92f8cb7d.png)
![September_2020](https://user-images.githubusercontent.com/29529042/92418402-af9fb580-f13d-11ea-89ae-218d876b9bba.png)
![September_2021](https://user-images.githubusercontent.com/29529042/92418404-b0384c00-f13d-11ea-8f59-110635b70fec.png)

**Comment by SimonSP** [comment]
same problem with September 6th

**Comment by juanruben** [comment]
Same issue.. it is related with time change that day

**Comment by defaphotos** [comment]
Tengo el mismo problema :c

**Comment by vandev23** [comment]
I have the same issue, for September

**Comment by TomasIb** [comment]
i have the same problem ...

**Comment by cutterbl** [comment]
@SimonSP @juanruben @defaphotos @vandev23 @TomasIb I'm looking at mine (I am an RBC user), and I'm not seeing what you're seeing. Two questions I have, 1) are you using latest version (v0.28.0)? (this may have already been resolved), and 2) what is your browser local timezone?

**Comment by vandev23** [comment]
> @SimonSP @juanruben @defaphotos @vandev23 @TomasIb I'm looking at mine (I am an RBC user), and I'm not seeing what you're seeing. Two questions I have, 1) are you using latest version (v0.28.0)? (this may have already been resolved), and 2) what is your browser local timezone?

@cutterbl I have using the latest version (v.0.28.0) And I still have the same issue 2) what is your browser local timezone? es

**Comment by cutterbl** [comment]
@vandev23 I'm unfamiliar with that timezone. Are you using moment-timezone? If so, give me the value returned by `moment.tz.guess()`

**Comment by SimonSP** [comment]
> 
> 
> same problem with September 6th

A couple of days ago i stopped using moment time zone for the app and it works

**Comment by juanruben** [comment]
@cutterbl I am using that version too. In the Santiago time zone, when the fall back time change occurs, the calendar duplicates the Saturday column. This causes the entire month to become misaligned

**Comment by cutterbl** [comment]
@SimonSP What version of moment and moment-timezone were you using, and which moment-timezone `with-data` file were you including? This may have been your culprit

@juanruben I'm unfamiliar with the `dateFnsLocalizer`. This may be some kind of bug within that. I thought the only two localizers supported were Globalize and Moment...

**Comment by cutterbl** [comment]
See documentation on [Dealing with Timezones](http://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/guides-timezones--page)
