### ISSUE TITLE
Hello, I want to know how I can change what appears in the week component's events..it shows time but I only want it to show name of the event. 

### ISSUE THREAD

**Issue by alisrour37** [jquense/react-big-calendar#1747]

**Comment by Tilteee** [comment]
You can style this in a css file or passing a customEvent changing that prop. 
If you do that in your css file: 

```
.rbc-event-label{
    display: none !important;
}

```
now you display only the event name.

**Comment by alisrour37** [comment]
> You can style this in a css file or passing a customEvent changing that prop.
> If you do that in your css file:
> 
> ```
> .rbc-event-label{
>     display: none !important;
> }
> ```
> 
> now you display only the event name.

Thank you for the response. The thing is that I want to only adjust the element in the week view..not both the week view and month view.

**Comment by Tilteee** [comment]
Hey alis, you solved your second problem?

**Comment by alisrour37** [comment]
> Hey alis, you solved your second problem?

Hello, yes it is, but now I want to make the toolbar separated. I.e. make the scrolling back and forth as arrows on the side of the calendar and to make a custom way to select between month and week view ..

**Comment by Tilteee** [comment]
You can style this in css events or create a customToolbar event, you can use my code to see that:
`class CustomToolbar extends React.Component {
    render() {
        let { localizer: { messages }, label } = this.props
        return(
            <div className="rbc-toolbar">
                <span className="rbc-btn-group">
                    <button type="button" onClick={this.navigate.bind(null, navigate.PREVIOUS)}>Semana Anterior</button>
                </span>
                <span className="rbc-toolbar-label">{label}</span>
                <span className="rbc-btn-group">
                    <button type="button" onClick={this.navigate.bind(null, navigate.NEXT)}>Próxima Semana</button>
                </span>
            </div>
        )
    }
    navigate = action => {
        this.props.onNavigate(action)
    }
}`

`components={toolbar: CustomToolbar}`
