### ISSUE TITLE
Events doesn't  drag or resize immediately after mouse click

### ISSUE THREAD

**Issue by Tilteee** [jquense/react-big-calendar#1750]
Do you want to request a feature or report a bug?
Report a bug

What's the current behavior?
i need to intialize an event before start to drag or resizing

What's the expected behavior?
Just click and start

**Comment by cutterbl** [comment]
Only time I've ever had issue with any of the DnD functionality is when trying to do so in IE. IE handles all of the event listeners so poorly it just blows up. We finally stopped supporting our scheduling app (at my company) in IE just for this reason (though it was long overdue).

**Comment by cutterbl** [comment]
And, reading further, what exactly do you mean by "I need to initialize an event before start to drag or resizing"? You've shown no code, and provided very little explanation, so it's very difficult to understand exactly what problem you are having, or what it is you are trying to accomplish.

**Comment by Tilteee** [comment]
My problem is to initialize the event array. I solved that problem passing a start and end event for my array with the actual date, but with that solution, i had a "ghost event" on the actual date.

` {
      id: 'event-now',
      title: '',
      start: new Date(),
      end: new Date(),
      resourceId: 1,
      avaliacao: '',
      pagamento: '',
      hide: true,
    },`

and

`const EventComponent = e => {
 const hideEvent = () => {
    events.map(event => {
        if(event.id == 'event-now'){
            return {style: {display: 'none'}}
        }
    })
  
 }`

without this, my dnd was working only with a click to initialize and a afterclick to resize or use dnd events on the event.

Now, my "ghost event" exists and disrupts the functioning on actual date.

Example: 

![image](https://user-images.githubusercontent.com/42361545/94039576-486d3c80-fd9e-11ea-9c1d-c920fe82897e.png)

and sorry for my bad english.

**Comment by cutterbl** [comment]
I'm sorry, but I still don't understand what you mean by 'initialize event', and really confused by your reference to 'click' and 'afterclick' events. It may help if you share some code, to see exactly how it is you are trying to implement DnD.

**Comment by cutterbl** [comment]
stale
