### ISSUE TITLE
Drag into and from external element

### ISSUE THREAD

**Issue by reefhorvitz** [jquense/react-big-calendar#1751]
I cant seems to find a way to create some sort of - bucket list to the calendar,
i want to have to option to drag into and from that "bucket list" into the calendar.
i tried some stuff i found in React dnd website, and couldn't make it work.

i made a wrapper for my bucket and calendar component - 

 ```
 <DndProvider backend={HTML5Backend}>
                <TripBoard boardId={boardId}/>
                <div className={styles.bucketList}>
                    <BucketList/>
                </div>
            </DndProvider>

```

tried to add console.log for my calendar to check if the drag works correctly like 
`        onDropFromOutside={console.log}
`
and created dragable event
```
import React from 'react';
import { useDrag } from 'react-dnd'
import {GENERIC_EVENT_TYPE} from "../../../Redux/consts";
import TypedActivityBar from "../../../Containers/TypedActivityBar";

const DraggedActivityBar = ({activityId}) => {
    const [collectedProps, drag] = useDrag({
        item: { activityId, type: GENERIC_EVENT_TYPE }
    });

    return (
        <TypedActivityBar innerRef={drag} activityId={activityId} eventType={GENERIC_EVENT_TYPE}/>
    );
};

export default DraggedActivityBar;


```
when i tried to drag it, nothing happend.

**Comment by cutterbl** [comment]
The DnD stuff isn't well documented, but if you read the code from the latest release you'll see there's a `onDropFromOutside` prop now.

```js
const onDropFromOutside = ({start, end, isAllDay}) => do something
```
I do see demo code in the repo as well https://github.com/jquense/react-big-calendar/blob/ac715f8fac0b2aa338b3062d78b344aea2619211/examples/demos/dndOutsideSource.js

**Comment by cutterbl** [comment]
Documentation for [onDropFromOutside](http://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/addons-drag-and-drop-props--on-drop-from-outside)

**Comment by bappyasif** [comment]
> Documentation for [onDropFromOutside](http://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/addons-drag-and-drop-props--on-drop-from-outside)

hello :)  i tried it as you have said, but still same "outcome" not getting any "response" in console

```tsx
    <DragAndDropCalendar
                localizer={localizer}
                events={events}
                selectable
                resizable
                onEventResize={handleResizeEvent}
                onEventDrop={handleMoveEvent}
                defaultView='month'
                defaultDate={new Date(2015, 3, 12)}
                // dragFromOutsideItem={handleDraggedFromOutside}
                // onDropFromOutside={handleDroppedFromOutside}
                onDropFromOutside={function ({ start, end, allDay }) {console.log(start, end, "!!")}}

                style={{
                    height: "40vh"
                }}
            />
```

what or how else i should be looking at it, any suggestions or guidelines is highly appreciated, thanks and happy coding :)

**Comment by cutterbl** [comment]
@bappyasif I'm fairly sure you need to use an arrow function, as the example code shows you.

**Comment by bappyasif** [comment]
> @bappyasif I'm fairly sure you need to use an arrow function, as the example code shows you.

much appreciated your response :) i tried that too beforehand but still same no response in console, i can share with you my github repo link if that helps, thanks :)
