### ISSUE TITLE
Get current displayed Range

### ISSUE THREAD

**Issue by raphaeljoie** [jquense/react-big-calendar#1752]
Hello Community,

I'm enjoying react-big-calendar a lot but I can't find a way to get the current range displayed of the calendar.
It's possible to get it once it's changed, using the parameter of onRangeChange(), but what I want is to be able to get that result using a reference to the Calendar element.

use case is a calendar to display events loaded remotely. I'd refresh the list of event on every onRangeChange() but also when the parent componentDidMount() happened. In that second case, I'd like to get the range displayed by the calendar instead of computing it manually.

**Comment by cutterbl** [comment]
I've requested this in the past myself. Currently the only way to do this is to track the `view` and `date`, as controlled props, and calculate this yourself.

**Comment by gigabo** [comment]
Another workaround option is to wrap the `Toolbar` and emit an initial `onView`.

The `onView` passed to the toolbar is the calendar's `handleViewChange`, which calls `onRangeChange`.

```jsx
import Toolbar from "react-big-calendar/lib/Toolbar";

// The calendar does not provide any way to receive the range of dates that
// are visible except when they change. This is the cleanest way I could find
// to extend it to provide the _initial_ range (`onView` calls `onRangeChange`).
const InitialRangeChangeToolbar = (props) => {
  useEffect(() => {
    props.onView(props.view);
  }, []);
  return <Toolbar {...props} />;
}

...

<Calendar
    components={{toolbar: InitialRangeChangeToolbar}}
    ...

**Comment by cesarpachon** [comment]
hello, the solution mentioned by @gigabo is yet the way to go, or there is another solution to obtain the initial range of the calendar?

**Comment by rinick** [comment]
> ```js
> import Toolbar from "react-big-calendar/lib/Toolbar";
> 
> // The calendar does not provide any way to receive the range of dates that
> // are visible except when they change. This is the cleanest way I could find
> // to extend it to provide the _initial_ range (`onView` calls `onRangeChange`).
> const InitialRangeChangeToolbar = (props) => {
>   useEffect(() => {
>     props.onView(props.view);
>   }, []);
>   return <Toolbar {...props} />;
> }
> ```

since Toolbar is not exported in the root level, this work around won't work if compiler is using esmodule in dist folder
