### ISSUE TITLE
onSelecting is not called on "month" view

### ISSUE THREAD

**Issue by marnixhoh** [jquense/react-big-calendar#1758]
#### Do you want to request a _feature_ or report a _bug_?
Bug
#### What's the current behavior?
When selecting a time slot, the onSelecting callback is only called on week and day views - not on the month view.

#### What's the expected behavior?

I believe onSelecting should also be called on the month view.

**Comment by cutterbl** [comment]
That's true, it is not. Says that it is only called in time based views in the documentation. `onSelectSlot` is though.

**Comment by marnixhoh** [comment]
Oh ok... But the month view is selectable, so shouldn't onSelecting fire there too then?
I am currently running into the following, which I guess would be a pretty common scenario:

- When either a day is clicked or a date slot selected on the month, week or day view, a pop up appears (triggered by the onSelectSlot callback) for the user to create an event, given the "start" and "end" provided by the onSelectSlot event.
- I use onSelecting to control whether or not the selection mentioned above should be allowed (I don't want to allow past dates to be selected)

The only fix/work around I see is to set "selectable" equal to false on the month view, but this would also prevent the clicking of a day to create an event on this view. This is not ideal.

I hope that makes sense...

I am curious to know if there is a reason that onSelecting does not fire on the month view?

Thanks

**Comment by cutterbl** [comment]
I have no idea why the authors don't fire this in the month view, but I'm sure it has something to do with how the listeners are applied.

You can, in `onSelectSlot`, do a check of your `view` (if you control the view), and block there

```js
const onSelectSlot = ({start, end}) => {
  if (view === 'month') { // or some other check
    return;
  }
  // do stuff otherwise
};
```

**Comment by marnixhoh** [comment]
Thank you for the suggestion. I had actually implemented your solution earlier, but then realized that now people can no longer create an event by clicking a day in the month view. And, I do want this functionality to be there. I just don't want them to be able to make a multi-day selection.

I find it odd, how you can make a selection on the month view, just as you can on a week/day view, but on the month view the onSelecting callback does not fire. Anyway...

Thank you so much for your help! I really appreciate it

**Comment by johannesd** [comment]
I have that same issue. Sure, it's possible to check the selection in onSelectSlot to find out if it spans across multiple days. However, it is not possible to disable the gray selection indication. Really, onSelectSlot should be called also in the month view.

**Comment by cutterbl** [comment]
@johannesd `onSelectSlot` is called in the month view. And, `onSelectSlot` and `onSelecting` both receive a `start` and `end`, so it is possible to 'check the selection' to see if it spans across multiple days.

**Comment by johannesd** [comment]
@cutterbl I think there is a misunderstanding. We want to be able to select a single day in the month view, but not multiple ones. I want to be able to prevent the gray selection to appear when I drag the mouse across multiple days. My attempt was to make onSelecting to return false if it spans multiple days, but true, if start and end are on the same day. This is not possible (or please tell me how)

**Comment by cutterbl** [comment]
Allowing on to select (through `onSelectSlot`) multiple days is intentional, as it allows a user to possibly create events that span multiple days from the month view, much like someone marking off their vacation time. If you want to restrict that ability, you would have to write custom functionality into your `onSelectSlot method.
