### ISSUE TITLE
in the event month counts here from 0

### ISSUE THREAD

**Issue by Rubel-hossain** [jquense/react-big-calendar#1759]
in the event month count from 0 to 11, please replace this to 1-12. for example in I give   start: new Date(2020, 1, 9) event will show in 9th February not 9th January

![big_calander](https://user-images.githubusercontent.com/9604162/94226637-e5a0b000-ff19-11ea-8d9a-b9eaeff05c00.png)

**Comment by jquense** [comment]
That's how dates work in Javascript, i don't have any control over it. Months start from 0 https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getMonth
