### ISSUE TITLE
Scrolling in Month Calendar day?

### ISSUE THREAD

**Issue by gtwilliams03** [jquense/react-big-calendar#1762]
#### Do you want to request a _feature_ or report a _bug_?
Report a _bug_

#### What's the current behavior?
If the vertical height of an event in month view expands, it is cut off at the bottom of the day of the month.  I am basically making a calendar which shows which users logged in to our network in a given day and whether they completed a COVID-19 screening before they got to the office (simple red, yellow, green event with the users initials and login time). User account names and avatars were intentionally removed. In my event data, I have set the `start` and `end` dates to be the same.

![image](https://user-images.githubusercontent.com/1564628/94802842-53cff180-03b6-11eb-89c5-b58805aa5cc4.png)

#### What's the expected behavior?
I cannot figure out how to scroll inside of a month day.  Alternatively simply setting the limit of the number of events before the drill down truncated list text appears would also be fine. I have been playing with props for hours and cannot figure this out.  I am sorry if this is the wrong forum for this! :)

**Comment by bennyfink** [comment]
This has been discussed in a lot of other threads. RBC isn't really made to handle different size events, but I've posted a workaround here #1213

**Comment by cutterbl** [comment]
You can do this with the [showAllEvents](http://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/props--show-all-events) prop
