### ISSUE TITLE
Is there a rbc-current-time-indicator wrapper?

### ISSUE THREAD

**Issue by JewNinja** [jquense/react-big-calendar#1771]
I want to style the indicator and pass the current time to it. How can this be done?

![image](https://user-images.githubusercontent.com/60292216/95564932-26272000-0a28-11eb-95f9-19bc33ec041d.png)

Now div is used there.
<pre><code>
{isNow && this.intervalTriggered && (
  <div
  className="rbc-current-time-indicator"
  style={{ top: ${this.state.timeIndicatorPosition}% }}
  />
)}
</code></pre>

You can replace it with a component or render function!

https://github.com/jquense/react-big-calendar/blob/5f155f71d6ea5b9d05cdf4bb8e7d21684c6a3ce7/src/DayColumn.js

**Comment by Abderahman88** [comment]
With some changes in the code/css, it will be possible.

![indictorTime](https://user-images.githubusercontent.com/36161889/96600802-a33c7a00-12f1-11eb-8cc5-654835f48a7f.PNG)

**Comment by JewNinja** [comment]
> With some changes in the code/css, it will be possible.
> 
> ![indictorTime](https://user-images.githubusercontent.com/36161889/96600802-a33c7a00-12f1-11eb-8cc5-654835f48a7f.PNG)

Hi! Please tell me how you passed the time!?
My best idea is to pass it to "date-", but how?

**Comment by Abderahman88** [comment]
Hi @JewNinja ,

I changed 2 files :

**DayColumn.js**
![code1](https://user-images.githubusercontent.com/36161889/97371748-4b35e280-18b2-11eb-8bc8-b4cae2833a14.PNG)

**time-grid.scss**
![code2](https://user-images.githubusercontent.com/36161889/97371779-5db01c00-18b2-11eb-931f-ebdcb965416f.PNG)

Hope this is usefull to you.

**Comment by JewNinja** [comment]
Thx you very much, but i not wait your answer and realize my intricate variant. I use wrapper TimeSlot. Сalculated the required one and drawn a line there..

**Comment by JewNinja** [comment]
I pass to
<pre><code>
components={{
  timeSlotWrapper: (props) => TimeSlot(props, step, currentDay, isRender)
}}
</pre></code>
step - time amount of one time slot
currentDay - currentView === 'week' ? moment().isoWeekday() : resource === null ? resources.data.length : 1
(currentDay for 'week' or 1 for single day calendar)
isRender - it is needed for indicate necessary resource

content of my TimeSlot.ts is something like this
<pre><code>
function TimeSlot(props, step, day, isRender) {
  const differenceMs = moment() - moment(props.value)
  const isCurrentTimeSlot = (differenceMs / (60 * 1000)) > 0 && (differenceMs / (60 * 1000)) < step

  let timeIndicator = {}
  let addStyle = {}

  if (isCurrentTimeSlot && isRender) {
    timeIndicator.children = (
      <div
        className="custom-time-indicator"
        style={{ // минус в конце просто для соответствия линии с оригинальной линией
          top: `${Math.round((differenceMs / (60 * 1000)) / step * 100) - 14}%`,
          width: `calc(${day * 100}% + ${(day + 2)}px)`,
          left: `calc(${-(day - 1) * 100}% + ${-day - 2}px)`,
        }}
        data-time={moment().format('HH:mm')}
      />
    )
    addStyle = { zIndex: 'inherit' }
  }


  return React.cloneElement(
    props.children,
    {
      style: { ...addStyle },
      'data-time': moment(props.value).format('HH:mm'),
      ...timeIndicator
    })
}

export default TimeSlot
</pre></code>

styles:
<pre><code>
.custom-time-indicator {
  height: 2px;
  background: #F74969;
  position: relative;
  z-index: 10;
  left: -202%;
  width: 303%;

  &::before {
    content: attr(data-time);
    position: absolute;
    top: -11px;
    left: -42px;
    height: 24px;
    width: 42px;
    padding: 1px 4px;
    border: 2px solid #F74969;
    border-radius: 13px;
    font-size: 12px;
    word-wrap: normal;
    font-weight: bold;
    color: #F74969;
    background: white;
    box-shadow: 0px 0px 6px 1px white;
  }
}

.rbc-current-time-indicator {
  display: none;
}
</pre></code>

PAY ATTENTION TO MY OTHER ISSUE:
https://github.com/jquense/react-big-calendar/issues/1797

and use arguments of function like this.props. or this.state.
or destructuring inside () => { const { } = this...... TimeSlot()}
<pre><code>
components={{
  timeSlotWrapper: (props) => {
    const { step, day, isRender } = this.props (or this.state)
    return TimeSlot(props, step, day, isRender)
  },
}}
</pre></code>

ps: I hope I haven't forgotten anything..

**Comment by gautam-meena-learngarm-ai** [comment]
@JewNinja I am able to render customized time indicator line but it is not rendering at correct time

green one is default one and blue one is customized.

![image](https://user-images.githubusercontent.com/77267345/121327826-6df0a500-c931-11eb-816c-59d94ebf8822.png)

**Comment by fly2mk** [comment]
@JewNinja I want to style the indicator and pass the current time to it. Could you please share your code in codesandbox. I'm trying that for past 2 days, nothing works.

**Comment by Asrafur25** [comment]
/* Add this CSS to your stylesheet */
.custom-calendar .rbc-current-time-indicator {
  background-color: red; /* Set your preferred background color */
  width: 2px; /* Set the width of the indicator */
  position: absolute;
  left: 0;
  right: 0;
  z-index: 1000; /* Ensure it appears above other elements */
}

**Comment by AdeelSaleem** [comment]
> I pass to
> 
> ```
> 
> components={{
>   timeSlotWrapper: (props) => TimeSlot(props, step, currentDay, isRender)
> }}
> ```
> 
> step - time amount of one time slot currentDay - currentView === 'week' ? moment().isoWeekday() : resource === null ? resources.data.length : 1 (currentDay for 'week' or 1 for single day calendar) isRender - it is needed for indicate necessary resource
> 
> content of my TimeSlot.ts is something like this
> 
> ```
> 
> function TimeSlot(props, step, day, isRender) {
>   const differenceMs = moment() - moment(props.value)
>   const isCurrentTimeSlot = (differenceMs / (60 * 1000)) > 0 && (differenceMs / (60 * 1000)) < step
> 
>   let timeIndicator = {}
>   let addStyle = {}
> 
>   if (isCurrentTimeSlot && isRender) {
>     timeIndicator.children = (
>       
>     )
>     addStyle = { zIndex: 'inherit' }
>   }
> 
> 
>   return React.cloneElement(
>     props.children,
>     {
>       style: { ...addStyle },
>       'data-time': moment(props.value).format('HH:mm'),
>       ...timeIndicator
>     })
> }
> 
> export default TimeSlot
> ```
> 
> styles:
> 
> ```
> 
> .custom-time-indicator {
>   height: 2px;
>   background: #F74969;
>   position: relative;
>   z-index: 10;
>   left: -202%;
>   width: 303%;
> 
>   &::before {
>     content: attr(data-time);
>     position: absolute;
>     top: -11px;
>     left: -42px;
>     height: 24px;
>     width: 42px;
>     padding: 1px 4px;
>     border: 2px solid #F74969;
>     border-radius: 13px;
>     font-size: 12px;
>     word-wrap: normal;
>     font-weight: bold;
>     color: #F74969;
>     background: white;
>     box-shadow: 0px 0px 6px 1px white;
>   }
> }
> 
> .rbc-current-time-indicator {
>   display: none;
> }
> ```
> 
> PAY ATTENTION TO MY OTHER ISSUE: #1797
> 
> and ( if you used withDragAndDrop() ) use arguments of function like this.props. or this.state. or destructuring inside () => { const { } = this...... TimeSlot()}
> 
> ```
> 
> components={{
>   timeSlotWrapper: (props) => {
>     const { step, day, isRender } = this.props (or this.state)
>     return TimeSlot(props, step, day, isRender)
>   },
> }}
> ```
> 
> ps: I hope I haven't forgotten anything..

can you please provide me your custom-time-indicator code

**Comment by gentrith44belt** [comment]
This is what I'm doing as a workaround, to render a custom component. Maybe it might be helpful to someone. Even though it would be nice to have a custom function for this like for the other items.


`typescript
	useEffect(() => {
		const timeoutId = setTimeout(() => {
			const element = document.querySelectorAll(".rbc-current-time-indicator")[0];
			// eslint-disable-next-line @typescript-eslint/no-unnecessary-condition
			if (element) {
				element.scrollIntoView({ block: "center" });

				const timeNode = document.createElement("div");
				element.appendChild(timeNode);

				const root = createRoot(timeNode);
				root.render(
					<CurrentTimeDivider
						sx={{ left: -57, gap: "13px", margin: 0, width: "calc(100% + 56px)" }}
					/>
				);
			}
		}, 100);

		return () => clearTimeout(timeoutId);
	}, []);
`



`css
".rbc-current-time-indicator": {
		backgroundColor: "transparent",
	},
`
