### ISSUE TITLE
Problem when updating component with new/deleted events

### ISSUE THREAD

**Issue by 4ur3-zut** [jquense/react-big-calendar#1772]
#### Do you want to request a _feature_ or report a _bug_?

bug
#### What's the current behavior?

When updating the calendar component with new events or when deleting events from it, events in the same div.rbc-row, or belonging to the same day are mixed/replaced with their neighbor.

An item that was removed would replace its neighbor.

An item that was added would become its neighbor.

initial state:
![beforeDelete](https://user-images.githubusercontent.com/11538079/95581900-131d4b80-0a3a-11eb-8fa3-8fb87157ca5b.PNG)

after deleting the event **123**:
![afterDelete123](https://user-images.githubusercontent.com/11538079/95581942-26301b80-0a3a-11eb-9623-d76e8050da69.PNG)
(see how 'other row' become '123' and 'other row 2' becomes 'other row')

after refreshing the page (expected result):
![afterDeleteRefresh](https://user-images.githubusercontent.com/11538079/95582001-4233bd00-0a3a-11eb-919d-48316e3c94f8.PNG)

I use a state to define events, and I have checked that my items were correct in the render method.

My project is fairly large but I haven't messed with the calendar component.

As a workaround, I pass an empty array as events and wait for the update to complete before passing my actual event data.

#### What's the expected behavior?

The component should update correctly without the need for a reset.

**Comment by cutterbl** [comment]
stale
