### ISSUE TITLE
d[("get" + method)] is not a function when select week or day view.

### ISSUE THREAD

**Issue by LuisAPPDev** [jquense/react-big-calendar#1781]
Hello,

I have a calendar and i create some events taking the info from firebase, in firebase the date is a string with this format:

2020-10-09T11:00:00.000Z

To create the events i have this function:

 const events = partnerBookings.map((elm) => {
      const tour = partnerTours.find((x) => x.id === elm.Product);

      if (new Date(elm.tourDate) instanceof Date) {
        console.log('yes');
      } else console.log('no');
      return {
        title: `${tour.title}`,
        start: new Date(elm.tourDate),
        end: new Date(elm.tourDate),
        infoBooking: elm,
        infoTour: tour
      };
    });

In the view of all month and in the agenda works well and show all events but when i try to select a day or a week which contains any event it crash.

I've read that is possible if you use a string or something different to an object date, for that reason i put this :

 if (new Date(elm.tourDate) instanceof Date) {
        console.log('yes');
      } else console.log('no');

And always return "yes" so i guess that new Date(elm.tourDate) is a date object.

I dont know how to solve this, i try so many thing but nothing works to me.

Hope you can help me.

Thanks in advance.

This is the full crash:

> Unhandled Runtime Error
TypeError: d[("get" + method)] is not a function

Call Stack
eval
node_modules/react-big-calendar/node_modules/date-arithmetic/index.js (282:0)
isJustDate
node_modules/react-big-calendar/dist/react-big-calendar.esm.js (219:14)
eval
node_modules/react-big-calendar/dist/react-big-calendar.esm.js (3768:0)
Array.forEach
<anonymous>
TimeGrid.render
node_modules/react-big-calendar/dist/react-big-calendar.esm.js (3763:0)
finishClassComponent
node_modules/react-dom/cjs/react-dom.development.js (17160:0)
updateClassComponent
node_modules/react-dom/cjs/react-dom.development.js (17110:0)
beginWork
node_modules/react-dom/cjs/react-dom.development.js (18620:0)
HTMLUnknownElement.callCallback
node_modules/react-dom/cjs/react-dom.development.js (188:0)
Object.invokeGuardedCallbackDev
node_modules/react-dom/cjs/react-dom.development.js (237:0)
invokeGuardedCallback
node_modules/react-dom/cjs/react-dom.development.js (292:0)
beginWork$1
node_modules/react-dom/cjs/react-dom.development.js (23203:0)
performUnitOfWork
node_modules/react-dom/cjs/react-dom.development.js (22154:0)
workLoopSync
node_modules/react-dom/cjs/react-dom.development.js (22130:0)
performSyncWorkOnRoot
node_modules/react-dom/cjs/react-dom.development.js (21756:0)
eval
node_modules/react-dom/cjs/react-dom.development.js (11089:0)
unstable_runWithPriority
node_modules/scheduler/cjs/scheduler.development.js (653:0)
runWithPriority$1
node_modules/react-dom/cjs/react-dom.development.js (11039:0)
flushSyncCallbackQueueImpl
node_modules/react-dom/cjs/react-dom.development.js (11084:0)
flushSyncCallbackQueue
node_modules/react-dom/cjs/react-dom.development.js (11072:0)
discreteUpdates$1
node_modules/react-dom/cjs/react-dom.development.js (21893:0)
discreteUpdates
node_modules/react-dom/cjs/react-dom.development.js (806:0)
dispatchDiscreteEvent
node_modules/react-dom/cjs/react-dom.development.js (4168:0)

**Comment by bladerunner2020** [comment]
I encountered the same error. So I converted start and end to Date object.
```js
const events = originalEvents.map(({start, end, ...rest}) =>
{
      start: new Date(Date.parse(start)),
      end: new Date(Date.parse(end)),
      ...rest
});
```

it helped.

**Comment by LuisAPPDev** [comment]
> I encountered the same error. So I converted start and end to Date object.
> 
> ```js
> const events = originalEvents.map(({start, end, ...rest}) =>
> {
>       start: new Date(Date.parse(start)),
>       end: new Date(Date.parse(end)),
>       ...rest
> });
> ```
> 
> it helped.

Hi! 

I tried this:

start: Date.parse(elm.tourDate),
end: Date.parse(elm.tourDate),

this:

start: Date.parse(new Date(elm.tourDate)),
end: Date.parse(new Date(elm.tourDate)),

and also: 

start: new Date(Date.parse(elm.tourDate)),
end: new Date(Date.parse(elm.tourDate)),

With all i can see the events in the calendar but in the week or day view it crash with the same error: 

d[("get" + method)] is not a function

elm.tourdate is a string with this: 2020-10-09T11:00:00.000Z


But i dont know it doesnt recognize that is a Date Object because with this console log always return Yes

 if (new Date(elm.tourDate) instanceof Date) {
        console.log('yes');
      } else console.log('no');

In which format is your date in the ddbb?

Thanks for your help.

**Comment by bladerunner2020** [comment]
> In which format is your date in the ddbb?

The initially I have dates in the iso string format (the same format as you have).
In fact both  new Date(Date.parse(elm.tourDate)) and Date(elm.tourDate) should work.
But if you path invalid string or object, you would get Invalid Date object which is instance of Date.

so for example: `new Date({}) instanceof Date`  will result in *true*.

**Comment by LuisAPPDev** [comment]
> > In which format is your date in the ddbb?
> 
> The initially I have dates in the iso string format (the same format as you have).
> In fact both new Date(Date.parse(elm.tourDate)) and Date(elm.tourDate) should work.
> But if you path invalid string or object, you would get Invalid Date object which is instance of Date.
> 
> so for example: `new Date({}) instanceof Date` will result in _true_.

So i dont know why it doesnt work, here you can see that i put the end and start as you told me.
<img width="543" alt="Captura de pantalla 2020-10-25 a las 22 31 28" src="https://user-images.githubusercontent.com/58700212/97119715-4cc8a480-1712-11eb-9cc3-9f8fb57b9b55.png">

And here maybe there is a problem, look at the console.log, the end and start values seem to be a string but i dont know why.

<img width="1262" alt="Captura de pantalla 2020-10-25 a las 22 31 47" src="https://user-images.githubusercontent.com/58700212/97119723-52be8580-1712-11eb-9d76-c9c5cc6d376a.png">

Thanks again.

**Comment by johnnyboi91** [comment]
I had the same problem, but resolved it with 'moment' library, like:
`{
  ...,
  start: moment('2020-11-19 20:00').toDate(),
  end: moment('2020-11-19 20:00').toDate(),
  ...
}`

hope this helps!

**Comment by shallonkobusinge** [comment]
**Make sure that you have the correct values for start and end keys in your event object, your event object should be like :**

```
data = [
  {
    title: "My event",
    allDay: false,
    start: new Date(2020, 10, 25, 10, 0), // 10.00 AM
    end: new Date(2020, 10, 25, 11, 0), // 2.00 PM
  }
  ]
```
