### ISSUE TITLE
Slot select not working

### ISSUE THREAD

**Issue by alxvallejo** [jquense/react-big-calendar#1784]
I don't know what the issue is, but my handler for selectSlot isn't always being called and it seems like I have to be lucky for it to trigger. I'm not really sure what the significance of the longPressThreshold is but setting it to 1 doesn't help, and setting it to 1000 doesn't either.

```     
         <Calendar
          localizer={localizer}
          events={[]}
          style={{ height: "50vh" }}
          selectable={true}
          onSelectSlot={(slot) => {
            console.log("slot select: ", slot);
            selectDayMobile(slot);
          }}
          views={{ month: true }}
          components={{
            toolbar: Toolbar,
          }}
          formats={
            {weekdayFormat: 'dd'}
          }
          longPressThreshold={5}
        />
```

I'm testing on Chrome (mobile view) since that's where I need the selectSlot to function. 

Another interesting thing is that the class of the selected slot changes to have a class of "rbc-date-cell rbc-current", but still my onSelectSlot doesn't console log. Any help?

**Comment by andrey-furman** [comment]
The same issue. library version: "react-big-calendar": "^0.30.0"
Here's the [screen of usage](http://joxi.ru/V2VEORLUkeENlm).
Node version: 12.18.4
On switching to current node lts version: 14.15.4 -> the issue is the same.

As for browsers: tried in chrome 87.0.*, safari 14.0.1, firefox 73.0.1. The issue in all of them is actual.

**Comment by andrey-furman** [comment]
Actually, [adding selectable property](http://joxi.ru/1A5voQxcbWOnEr) has resolved the issue in my case.

**Comment by mPooja-15** [comment]
I have just added  ***        longPressThreshold={10} 
*** into the
         <Calendar
          localizer={localizer}
          events={[]}
          style={{ height: "50vh" }}
          selectable={true}
          onSelectSlot={(slot) => {
            console.log("slot select: ", slot);
            selectDayMobile(slot);
          }}
      
       ......
       .....
       longPressThreshold={20} 
        />
and it's working well into the iPad & mobile

**Comment by josiaharkson** [comment]
> selectable={true}

Actually this worked for me! thanks @andrey-furman

**Comment by Hamjaster** [comment]
> Actually, [adding selectable property](http://joxi.ru/1A5voQxcbWOnEr) has resolved the issue in my case. Just add selectable={true} prop onto the component.

Very thkns, that solved IT

**Comment by Berchez** [comment]
> I have just added *** longPressThreshold={10} *** into the <Calendar localizer={localizer} events={[]} style={{ height: "50vh" }} selectable={true} onSelectSlot={(slot) => { console.log("slot select: ", slot); selectDayMobile(slot); }}
> 
> ```
>    ......
>    .....
>    longPressThreshold={20} 
>     />
> ```
> 
> and it's working well into the iPad & mobile

it should be 0. But 0 doesnt work
