### ISSUE TITLE
React Dom 17+ Breaks Resizing

### ISSUE THREAD

**Issue by KevinMulhern** [jquense/react-big-calendar#1785]
#### Do you want to request a _feature_ or report a _bug_?
Bug
#### What's the current behavior?
Resizing doesn't work when using react-dom 17+

[Codesandbox Link](https://codesandbox.io/s/confident-dawn-k5nsr?file=/src/App.js) - changing react-dom version to 16.XX makes resizing work as expected.

#### What's the expected behavior?
Resizing should work

**Comment by Angush** [comment]
Same problem here. Spent far too long trying to get it working until I found this issue. 😔 Thanks for the fix.

**Comment by seanpmaxwell** [comment]
spent 3 hours trying to figure this out, thx for the post, will revert my react version for now

**Comment by LunaticPoring** [comment]
From what I saw (after spending time trying to understand what I did wrong),
`handleInteractionEnd` is never called when the action is `resize`, therefore, never calling `onEventResize`

`handleInteractionEnd`  is supposed to be called on selector events (select, selecting, beforeSelect) etc, but it's never called when dragging on the `rbc-addons-dnd-resize`  div. 

Wild guess is the  `rbc-addons-dnd-resize`  div is added afterwards through `renderAnchor `method and doesn't handle any drag event.

Anyway +1 for this issue !

**Comment by francescovenica** [comment]
any update on this problem?

**Comment by tanghuan** [comment]
thanks

**Comment by thanhlmm** [comment]
I have made a PR to fix it. Hope it help :)

**Comment by ralexandr** [comment]
Faced same issue :(
Any plans to merge fix into the next version of the package?

**Comment by gianpieropa** [comment]
Any updates on this ?

**Comment by croustibat222** [comment]
Hello, could someone say if this will be implemented or not? Just to know if we should wait or find a work around. Thx

**Comment by croustibat222** [comment]
it works with the last version...
