### ISSUE TITLE
React-big-calendar displays 12h time format instead of 24h

### ISSUE THREAD

**Issue by sSwiergosz** [jquense/react-big-calendar#1792]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?
React-big-calendar displays 24h time format as if it was 12h time format (with proper localizer)

Here is my stackoverflow post - https://stackoverflow.com/questions/64665520/react-big-calendar-incorrect-time-display

**Comment by sSwiergosz** [comment]
Hi @jquense - could you take a look at my example?

**Comment by jquense** [comment]
not sure, seems like it might be an issue with the date-fn localizer (which i don't use so hard to provide support for). You can manually override all the formatting, to be how you'd like. It may just be the formats are hardcoded to 12hr in some places accidently?

**Comment by sSwiergosz** [comment]
I don't think they are hardcoded to 12hr. I was trying with the `moment` library, but the result was exactly the same. So I think that it's not an issue with a localizer itself.

**Comment by jquense** [comment]
the localizer is the thing that handles all date formatting, it have to be related to it. Each localizer will handle formats differently depending on how you've configured the underlying library, e.g. you need to set the locale in moment, _and_ the locale data needs to specify if the clock style

**Comment by sSwiergosz** [comment]
When it comes to setting the locale with `date-fns/moment`:
https://github.com/sSwiergosz/fitness-platform/blob/develop/frontend/components/Calendar.js#L12

I'm also passing datetime like this:
https://github.com/sSwiergosz/fitness-platform/blob/develop/frontend/components/Calendar.js#L54

So the events are passing to the react-big-calendar in the local time. I also set the `culture` prop, but none of it works for me.

**Comment by cutterbl** [comment]
You can change this by adjusting any of the [formats](http://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/props--formats)

**Comment by IzaanAnwar** [comment]
How can we display the events in 24 hours format?

**Comment by cutterbl** [comment]
@IzaanAnwar by adjusting the various 'format' props. See documentation for more details.
