### ISSUE TITLE
Race condition

### ISSUE THREAD

**Issue by josipNPseudocode** [jquense/react-big-calendar#1793]
Hello, first of all I thank you for your wonderful component ! 👍 
I have been using it for a few months now and It has been a huge help for my business application.

That being said I have the following issue. 

I am using your onRangeChange={onRangeChange} event, from what I notice there is a race condition happening when executing the following steps: 
-  Go to monthly view 
-  Have a day of month with 5 + events (just enough to show the  .rbc-show-more + )
-  Click on the Show more +

When inspecting on onRangeChange event I see that in this case the method is being called twice.
- The first time the range parameter contains an array with only a single element range[0] = Date object containing the day you clicked on 
- The second time the range parameter contains { end, start } which are the start and the end of the month for the clicked event

Any feedback would be appreciated :)

**Comment by cooljser** [comment]
I have the same question
