### ISSUE TITLE
Strange behaviour of withDragAndDrop

### ISSUE THREAD

**Issue by JewNinja** [jquense/react-big-calendar#1797]
When i wrapping:
  const DragAndDropCalendar = withDragAndDrop(Calendar):

I need pass "periods" to timeSlotWrapper.
For this i pass function in components={{ }}

<pre><code>
components={{
  timeSlotWrapper: (props) => {
    return TimeSlot(props, periods)
  },
}}
</code></pre>

When i destructuring periods before return (
<pre><code>
render() {
    const { periods } = this.props

    return (
      DragAndDropCalendar
        selectable
        localizer={localizer}
        events={this.state.events}
        onEventDrop={this.moveEvent}
        resizable
        onEventResize={this.resizeEvent}
        onSelectSlot={this.newEvent}
        onDragStart={console.log}
        defaultView={Views.MONTH}
        defaultDate={new Date(2015, 3, 12)}
        popup={true}
        dragFromOutsideItem={
          this.state.displayDragItemInCell ? this.dragFromOutsideItem : null
        }
        onDropFromOutside={this.onDropFromOutside}
        handleDragStart={this.handleDragStart}
        components={{
          timeSlotWrapper: (props) => TimeSlot(props, periods),
        }}
      />
    )
  }
</code></pre>
periods in timeSlotWrapper empty ([ ].length === 0) (probably because this is old value. remaining from the previous render)

When i NOT destructuring, and get this in components={{ }} by this.props (or this.state, it does not matter)..
<pre><code>
render() {
    return (
      DragAndDropCalendar
        selectable
        localizer={localizer}
        events={this.state.events}
        onEventDrop={this.moveEvent}
        resizable
        onEventResize={this.resizeEvent}
        onSelectSlot={this.newEvent}
        onDragStart={console.log}
        defaultView={Views.MONTH}
        defaultDate={new Date(2015, 3, 12)}
        popup={true}
        dragFromOutsideItem={
          this.state.displayDragItemInCell ? this.dragFromOutsideItem : null
        }
        onDropFromOutside={this.onDropFromOutside}
        handleDragStart={this.handleDragStart}
        components={{
          timeSlotWrapper: (props) => TimeSlot(props, this.props.periods),
        }}
      />
    )
  }
</code></pre>
periods value is NOT empty ([{ }, { }].length > 0) (this is actual values)

When i DON'T wrapping:
  const DragAndDropCalendar = withDragAndDrop(Calendar):

periods value is always actual!

I check this in ours project, and in new project, when i use react-big-calendar example:
https://github.com/jquense/react-big-calendar/blob/558ee2d86bd06c4d84a13b1f7976825c2002d444/examples/demos/dnd.js

In both cases, i observed equal behaviour!

**Comment by JewNinja** [comment]
* DragAndDropCalendar without <, because with not correct formating

**Comment by cutterbl** [comment]
stale
