### ISSUE TITLE
Height of the column is broken from version v0.28.2 (WEEK view)

### ISSUE THREAD

**Issue by licia03** [jquense/react-big-calendar#1802]
#### Do you want to request a _feature_ or report a _bug_?
a bug

#### What's the current behavior?
The height of the column `.rbc-time-column` is broken within 'WEEK' view.

- reproducible from version 0.28.2 
- browser: Chrome, Firefox, Safari 

See [CodeSandbox](https://codesandbox.io/s/cocky-mcnulty-sy7tf?file=/src/index.js)

I found this PR that probably have introduced this new bug [#1789 ](https://github.com/jquense/react-big-calendar/pull/1789)

**Comment by jason-krypton** [comment]
This is also broken on `DAY` view.
