### ISSUE TITLE
Incorrect rendering of events when setting height of container starting version 0.28.2

### ISSUE THREAD

**Issue by swiftanthony** [jquense/react-big-calendar#1806]
**Do you want to request a feature or report a bug?**

a bug

See sandbox https://codesandbox.io/s/react-big-calendar-example-forked-pv3k0

* `react-big-calendar` version is `0.28.1`
* Now switch `react-big-calendar` version to `0.28.2`

**Bug**: event on `10 Fri` will be rendered at incorrect slot

**Comment by licia03** [comment]
It seems the same bug reported here [#1802 ](https://github.com/jquense/react-big-calendar/issues/1802) and the fix has been applied from v0.28.6

**Comment by swiftanthony** [comment]
> It seems the same bug reported here [#1802 ](https://github.com/jquense/react-big-calendar/issues/1802) and the fix has been applied from v0.28.6

Confirmed
