### ISSUE TITLE
'BigCalendar' is not exported from 'react-big-calendar'

### ISSUE THREAD

**Issue by liliangiraudo5** [jquense/react-big-calendar#1811]
#### 'BigCalendar' is not exported from 'react-big-calendar'.

I try to set up BigCalendar on my React application but I get the following error message: 

**Attempted import error: 'BigCalendar' is not exported from 'react-big-calendar'.**

How is this possible? I've done some tests on react-big-calendar examples and it's all good.

I am using the version **0.28.6**

**Comment by s7dhansh** [comment]
Please check the README. The modular export is `Calendar`.
```
import { Calendar } from 'react-big-calendar'
```

**Comment by hotstone** [comment]
Unless I'm missing something, the first paragraph of the README has a link titled "DEMO and Docs", the first section of which - Getting Started - says to `import BigCalendar from 'react-big-calendar'`:
http://jquense.github.io/react-big-calendar/examples/index.html

Something out of sync here?

**Comment by s7dhansh** [comment]
I guess it's not updated for the latest version.

Check the README. https://github.com/jquense/react-big-calendar

**Comment by cutterbl** [comment]
You may not be using our latest version, of the package or the [docs](http://jquense.github.io/react-big-calendar)
