### ISSUE TITLE
Show more popup not working on react 17

### ISSUE THREAD

**Issue by tziocy** [jquense/react-big-calendar#1813]
#### Show more popup is not working when using react 17

See sandbox below:
[https://codesandbox.io/s/broken-frost-qpgmv
](url)
#### What's the expected behavior?

Popup to work

**Comment by madhavVividunity** [comment]
getting same issue

**Comment by kpheasey** [comment]
Show more and resizble doesn't work

**Comment by mstrokin** [comment]
Seems to work fine with updated react-overlays
