### ISSUE TITLE
Changing the selected day in week view by clicking anywhere.

### ISSUE THREAD

**Issue by justdvl** [jquense/react-big-calendar#1814]
Hello!
Using a week view, I want to be able to select a day by clicking on that day anywhere (not only limited to header). 
While in month view providing a custom component dateCellWrapper does the job, in week view it does not work.
I noticed in week view, the cells are owerlapped by another component - eventContainerWrapper.
So I had to customize this component:

```
<Calendar
  onDrillDown={onDrillDown}
  components={{
        eventContainerWrapper: EventContainerWrapper
  }}
...
```
    const EventContainerWrapper = ({ children, ...props }) => {
        return (
            React.cloneElement(React.Children.only(children), {
                onClick: () => {
                    onDrillDown(props.slotMetrics.groups[0][1])
                },
                
            })
            )
        }

```
  const onDrillDown = (x) => {
    setSelectedDate(moment(x));
  };
```

I wonder if there is a better solution to my need. If not, at least in EventContainerWrapper, is there a better way to get information about what is the date of day I clicked into, than how I'm getting it now?

**Comment by bilobom** [comment]
The is `selectable` prop for that. [ prop explanation in doc](http://jquense.github.io/react-big-calendar/examples/index.html#prop-selectable)
Whenever a slot is selected on any views the [onSelectSlot](http://jquense.github.io/react-big-calendar/examples/index.html#prop-onSelectSlot) is fired.

somthing like this

```jsx
<Calendar
    selectable={true}
    onSelectSlot={(SlotInfo) => {
        /**
         slotInfo : {
            start: Date,
            end: Date,
            slots: Array < Date >,
            action: "select" | "click" | "doubleClick",
            bounds: ? { // For "select" action
                x: number,
                y: number,
                top: number,
                right: number,
                left: number,
                bottom: number,
            },
            box: ? { // For "click" or "doubleClick" actions
                clientX: number,
                clientY: number,
                x: number,
                y: number,
            },
        }
            */
        setSelectedDate(SlotInfo.bounds.x);
    }}
/>
```
