### ISSUE TITLE
Month view not showing up

### ISSUE THREAD

**Issue by chramos** [jquense/react-big-calendar#1817]
#### Do you want to request a _feature_ or report a _bug_?
Bug
#### What's the current behavior?
The month view are not showing up

#### What's the expected behavior?
I wanna see the calendar in the month view... but I can't

I create a simple example in codesand box to show the issue:
https://codesandbox.io/s/brave-ellis-57q37?file=/src/App.js

**Comment by bilobom** [comment]
Set the height for the elements wrapping the Calendar 
```css
html,
body,
#root,
.App {
  height: 100%;
}
```

**Comment by chramos** [comment]
Yeah! works perfectly
