### ISSUE TITLE
`component` prop cause re-mount on each Calendar re-redender

### ISSUE THREAD

**Issue by bilobom** [jquense/react-big-calendar#1818]
#### Do you want to request a _feature_ or report a _bug_?
Bug
#### What's the current behavior?
custom components passed to `components` props are being re-mounted each time the Calendar re-render

Here is a [codesandbox example](https://codesandbox.io/s/rbigcal-components-remounting-eth14).Where foo is a boolean state variable being toggled by Calnedar, you'll see in the console that CustomToolbar is re-mounted each time foo is updated.
```jsx
const CustomToolBar = (props) => {
  useEffect(() => {
    console.log("mounted");
  }, []);
  return <div>Foo is {String(props.foo)}</div>;
};

const MyCalendar = (props) => {
  const [foo, setFoo] = useState(false);
  return (
    <div>
      <button onClick={() => setFoo(!foo)}>fooooo</button>

      <Calendar
        localizer={localizer}
        events={events}
        style={{ height: 500 }}
        components={{
          toolbar: (props) => <CustomToolBar {...props} foo={foo} />
        }}
      />
    </div>
  );
};
```
ScreenShot:
![re-mounting](https://i.suar.me/eXVA9)
#### What's the expected behavior?
Re-rendering calendar shouldn't remount custom components passed to `components` props

**Comment by evedes** [comment]
Have you tried to memoize it with useCallback or useMemo?!?

**Comment by bilobom** [comment]
@evedes That's what i ended up doing to reduce re-mounting each render, but that doesn't prevent it from re-mounting when the dependency array changes in these hooks

**Comment by evedes** [comment]
That's not how React works? Each time your MyCalendar re-renders the toolbar function gets garbage collected so naturally is mounted again? 🤔  I'm learning in public, I might be wrong. ⚠️

**Comment by bilobom** [comment]
@evedes That'll be the case if `CustomToolBar` was declared inside `MyCalendar`. 

- To further proove my point I created a `FakeCalendar` that accept `components` props like so [codesandbox link](https://codesandbox.io/s/fakecalendar-components-remounts-ek42i)
``` jsx
const FakeCalendar = (props) => {
  return (
    <div>
      {props.components.toolbar}
      <br />
      <div className={"fakeCalendar"}>
        hello I'm fake calendar. Above me, is the custom toolbar
      </div>
    </div>
  );
};

const CustomToolBar = (props) => {
  useEffect(() => {
    console.log("mounted");
  }, []);
  return <div>Foo is {String(props.foo)}</div>;
};

const MyCalendar = (props) => {
  const [foo, setFoo] = useState(false);
  return (
    <div>
      <button onClick={() => setFoo(!foo)}>fooooo</button>

      {/*"Calendar replaced here by a fake one"*/}

      <FakeCalendar
        components={{
          toolbar: <CustomToolBar {...props} foo={foo} />
        }}
      ></FakeCalendar>
    </div>
  );
};
```

- if you see the console, the `CustomToolbar` will not get re-mounted each time `MyCalendar` re-renders (that is when `foo` toggles)

**Comment by Nmarinsiruela** [comment]
I can confirm this keeps happening. On our side, we were working on an accessibility issue regarding a modal; it turned out that the issue comes because the modal springs once you click inside of our custom Toolbar; as the component is lost and re-created, the previous focus goes out of the window.

So far, we've been unable to stop the unmounting at all. It's a pity, because we certainly appreciate the great job on this library!

**Comment by alizaidi606** [comment]
Did anyone find any workaround? This is impacting page performance drastically...

**Comment by michaelminhvo** [comment]
Some initial investigation shows that the issue is because the whole calendar context is re-calculated and reset on any re-render cycle, even if the props haven't changed. This causes any custom components to be re-computed, which will un-mount and re-mount. See:

https://github.com/jquense/react-big-calendar/blob/8e6c84db5241727548e065e4af83ef45caa734cb/src/Calendar.js#L824

Will do some more investigation, this line not be needed in most cases.

**Comment by strike9906** [comment]
The problem really exists and it manifests itself very well when you have 100+ events (or even more) in your calendar, any change inside any component or change in data within 1 event, the re-renderer of the entire calendar is triggered completely, which causes serious lags. Can you give any recommendations about optimizing it all? how can I change events inside the calendar without affecting the resource-intensive process of recomputing the calendar??

**Comment by latusdenis** [comment]
@michaelminhvo Any updates on your research? Seems like the issue is pretty critical for huge datasets. Thank you!

**Comment by michaelminhvo** [comment]
> @michaelminhvo Any updates on your research? Seems like the issue is pretty critical for huge datasets. Thank you!

I stopped investigating after finding a temporary solution. 

At the moment I'm wrapping the component, say MyCalendar that holds `calendar` component in a `React.memo` call. So as long as those props never change, re-renders don't happen. Then in the prop `components` for `calendar` you can have state and make changes with no issues. If you do make api calls that affect the state of the calendar then you can modify the state from `MyCalendar` which does trigger re-renders. 

This affects how you design the UX interactions. You can visualize it as do everything you want in modals or anything that is modifying data, and then you save to the DB, and on success everything is re-rendered.

**Comment by bheklilr** [comment]
@michaelminhvo Could you provide a MVP example that makes this work?  I'm trying to work around this myself but haven't had any luck so far.  When I profile it with the react dev tools I see that it's MonthView that is taking the most amount of time to render
![image](https://user-images.githubusercontent.com/1035817/127327387-82e04abd-23eb-490f-a822-54ed4fb95866.png)
This is without even hooking up onSelectEvent, just clicking an event with no callback is enough to cause the entire calendar to rerender.

I'm fine with the toolbar taking an extra 8ms to render, but the MonthView takes 214 of 314ms, resulting in a very noticeable lag.  It's even worse if I hook up onSelectEvent, taking a total of about 450ms total, and MonthView taking 280ms.  Even if I can just halve that render time it'd make my UI feel much more responsive.

**Comment by michaelminhvo** [comment]
> @michaelminhvo Could you provide a MVP example that makes this work? I'm trying to work around this myself but haven't had any luck so far. When I profile it with the react dev tools I see that it's MonthView that is taking the most amount of time to render
> ![image](https://user-images.githubusercontent.com/1035817/127327387-82e04abd-23eb-490f-a822-54ed4fb95866.png)
> This is without even hooking up onSelectEvent, just clicking an event with no callback is enough to cause the entire calendar to rerender.
> 
> I'm fine with the toolbar taking an extra 8ms to render, but the MonthView takes 214 of 314ms, resulting in a very noticeable lag. It's even worse if I hook up onSelectEvent, taking a total of about 450ms total, and MonthView taking 280ms. Even if I can just halve that render time it'd make my UI feel much more responsive.

All I did was put 

```
const Index = React.memo((props: Props) => {
...
<Calendar />
```

I wouldn't recommend this library but there's no better alternative that I can see.

**Comment by mikeyyyzhao** [comment]
if you declare the components outside and reference it, it does it remount on every render

```
const CALENDAR_COMPONENTS = {
  toolbar: CalendarToolbar,
  event: CustomEvent,
  day: {
    header: CustomDayHeader
  },
  timeSlotWrapper: TimeSlotWrapper,
  timeGutterHeader: TimeGutterHeader,
};

export default function WeekCalendar() {
  return <Calendar components={CALENDAR_COMPONENTS}/>
}
```

**Comment by jhnns** [comment]
That's how React works: as soon as the identity of the function component changes, the old function component will be unmounted and the new one will be mounted. React.memo won't change this since the whole function component is replaced. I've done the same mistake 😁. @mikeyyyzhao showed how this can be avoided.

I think this issue can be closed since there is nothing react-big-calendar can do about this. You could only add a note to the README.
