### ISSUE TITLE
drag and drop on react big calendar does not work in an iframe (onSelectSlot not getting called)

### ISSUE THREAD

**Issue by mikeyyyzhao** [jquense/react-big-calendar#1822]
#### Do you want to request a _feature_ or report a _bug_? Bug
It does not look like drag and drop on react-big-calendar work in an iframe. With an iframe, it doesn't look like rbc picks up the select slot event (onSelectSlot). Everything else seems to work fine. 

#### What's the current behavior?
dragging on empty slots does nothing.

#### What's the expected behavior?
Rbc works similar in an iframe as out of it.

**Comment by cutterbl** [comment]
stale
