### ISSUE TITLE
TypeError: d['get' + method] is not a function.

### ISSUE THREAD

**Issue by daveteu** [jquense/react-big-calendar#1825]
I used the very basic codes 

```
import { Calendar, momentLocalizer } from 'react-big-calendar'
import moment from 'moment'

const localizer = momentLocalizer(moment)

const MyCalendar = props => (
  <div>
    <Calendar
      localizer={localizer}
      events={myEventsList}
      startAccessor="start"
      endAccessor="end"
      style={{ height: 500 }}
    />
  </div>
)
```

The calendar displays well on-load, together with my events. However, when I click on Month/Week/Days view button on the top right, I get this error.

<img width="1187" alt="image" src="https://user-images.githubusercontent.com/18649392/101867498-40ab8000-3bb6-11eb-88b3-fb5c4bd8a99d.png">

```
The above error occurred in the <TimeGrid> component:
    in TimeGrid (created by Week)
    in Week (created by Calendar)
    in div (created by Calendar)
    in Calendar (created by Uncontrolled(Calendar))
    in Uncontrolled(Calendar) (created by ForwardRef)
    in ForwardRef (at Calendar.js:20)
    in div (at Calendar.js:19)
    in Calendar (at calendar.js:11)
    in CalendarPage (at _app.js:37)
```
The TimeGrid component is part of the Calendar component right? How do I correct this error?

**Comment by natramov** [comment]
Please show the `myEventsList`

**Comment by jquense** [comment]
the error means your event list does not have actual JS Date objects for start/end times

**Comment by Bobur96** [comment]
data.forEach(el => { 
  el.start = new Date(el.start);
  el.end = new Date(el.end);
})

**Comment by Bobur96** [comment]
{
  id: 8,
  title: "Meeting",
  start: new Date("2022-05-12T08:00:00.000Z"),
  end: new Date("2022-05-12T09:00:00.000Z")
}
