### ISSUE TITLE
Custom view with custom layout

### ISSUE THREAD

**Issue by aleksays** [jquense/react-big-calendar#1826]
#### What's the current behavior?
Views layout is not flexible. For example, TimeGrid component using layout where Resources placed on top, and times on left, and DayColumn component as a columns.

#### What's the expected behavior?
![Big calendar](https://user-images.githubusercontent.com/9671780/101901727-8bcb9000-3bc2-11eb-8a22-f2988a04f3f7.jpg)
There is no easy way to implement layout like this.
Maybe someone help me with this question?

**Comment by aftabnaveed** [comment]
@aleksays did you find any solution to that? Looks like you already closed the issue.

**Comment by shalawfatah** [comment]
@aleksays I need something exactly like that, any solutions? Is there some implementation in another library? I don't want to go full custom for this if it can be done.
