### ISSUE TITLE
Testing Dnd with Cypress

### ISSUE THREAD

**Issue by rockandbit** [jquense/react-big-calendar#1841]
Hi everyone,

Someone has tried testing the feature "drag and drop" with Cypress?.
I cannot move an event. I have tried several options but not success.
For example:
`cy.get('.rbc-addons-dnd-resizable > .rbc-event-content')
      .trigger('mousedown', { which: 1 })
      .trigger('mousemove', { clientX: 200, clientY: 300 })
      .trigger('mouseup', { force: true });`

Thanks in advance.
Greetings

**Comment by nitzanmo** [comment]
Any luck?

**Comment by martin-trajanovski** [comment]
@rockandbit I am testing it using something like this:
`
  cy.get('.rbc-event').trigger('dragstart');
  cy.get('[find the timeslot where you want to drop something like .rbc-time-slot]').trigger('drop', {
          force: true,
        });
`
So for your specific case you need to adjust the selectors but I think you will get the point how to test using dragstart and drop events.

**Comment by dengue8830** [comment]
I can't create an event with DnD. I'm only able to create an event by triggering a 'click' event

what I tried:
- https://youtu.be/hvwYBlKLz6U?t=232
- https://github.com/4teamwork/cypress-drag-drop
- `.trigger('dragstart')` and `.trigger('drop', { force: true, })`

**Comment by dengue8830** [comment]
found a solution, pretty obvious, the trick was: use 'mousemove' on the target selector instead of the source selector

here a simple example: a 3hs event

```
cy.get('.rbc-day-slot .rbc-time-slot').first().trigger('mousedown', { force: true });
cy.get('.rbc-day-slot .rbc-timeslot-group:nth-child(3) .rbc-time-slot:nth-child(2)')
  .last()
  .trigger('mousemove', { force: true })
  .trigger('mouseup', { force: true });
```

`.rbc-timeslot-group` is the hour block and `.rbc-time-slot:nth-child` the half hour block inside that hour block
