### ISSUE TITLE
  Type 'typeof Calendar' is not assignable to type 'ComponentClass<CalendarProps<object, object>, any>'

### ISSUE THREAD

**Issue by furmanServices** [jquense/react-big-calendar#1842]
#### Error on initialization calendar on tsx:
**Versions:**
node: 12.18.4
"react-big-calendar": "^0.30.0",
"@types/react-big-calendar": "^0.24.8",

Error occures on `tsc` compiliation command execution:

`const DragAndDropCalendar = withDragAndDrop(Calendar)`

#### Current behavior
Argument of type 'typeof Calendar' is not assignable to parameter of type 'ComponentType<CalendarProps<object, object>>'.
  Type 'typeof Calendar' is not assignable to type 'ComponentClass<CalendarProps<object, object>, any>'.
    Construct signature return types 'Calendar<any, any>' and 'Component<CalendarProps<object, object>, any, any>' are incompatible.

#### What's the expected behaviour?
Also tried to bring to latest common versions of react-big-calendar and @types/react-big-calendar: 0.24.6 - the result the same.

**Comment by furmanServices** [comment]
I don't think that this may influence the issue, by the way, here's my tsconfig.json file content:
`
{
  "compilerOptions": {
    "module": "commonjs",
    "esModuleInterop": true,
    "removeComments": true,
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es6",
    "rootDir": ".",
    "sourceMap": false,
    "baseUrl": "./",
    "types": ["node"],
    "paths": {
      "@vendor": [
        "vendor"
      ],
      "@vendor/*": [
        "vendor/*"
      ],
      "@services": [
        "services"
      ],
      "@services/*": [
        "services/*"
      ]
    },
    "jsx": "react"
  },
  "exclude": ["node_modules"]
}
`

**Comment by jquense** [comment]
I don't mantain the DT types for RBC sorry!

**Comment by marcelodosko** [comment]
const DragAndDropCalendar = withDragAndDrop(Calendar as any);
