### ISSUE TITLE
Bug: TimeGrid Import Error

### ISSUE THREAD

**Issue by jacortiz** [jquense/react-big-calendar#1856]
#### Do you want to request a _feature_ or report a _bug_?
**Bug Report**
#### What's the current behavior?

react-big-calendar: 0.31
type version: @types/react-big-calendar: 0.24.8

Basically, i just followed what's on the demo code of the custom week _(pease see: https://github.com/jquense/react-big-calendar/blob/master/examples/demos/customView.js)_

<img width="792" alt="Screen Shot 2021-02-03 at 2 44 14 PM" src="https://user-images.githubusercontent.com/58540624/106709143-0945d680-662f-11eb-91cf-8492cbae4eef.png">

please see codes below:
<img width="710" alt="Screen Shot 2021-02-03 at 2 45 45 PM" src="https://user-images.githubusercontent.com/58540624/106709188-195db600-662f-11eb-80ea-6358e32fca32.png">

**PS: upon checking the react-big-calendar documentation, seems the the "TimeGrid" is missing from the docs**
<img width="2023" alt="Screen Shot 2021-02-03 at 2 54 38 PM" src="https://user-images.githubusercontent.com/58540624/106709641-d223f500-662f-11eb-924d-91c96ef39697.png">

#### What's the expected behavior?

- TimeGrid should be properly imported.

**Comment by ingatrifan** [comment]
I have the same issue now, have you found a solution?

**Comment by willyxiao** [comment]
Any updates on this? I'm getting the same weird error and am defaulting to:

`const TimeGrid = require('react-big-calendar/lib/TimeGrid');`

To make this work.

**Comment by jacortiz** [comment]
nice. thanks will try this. but the feature on my project for this is currently on hold :)
