### ISSUE TITLE
Is it possible to access culture in utils/dates?

### ISSUE THREAD

**Issue by sepehrooo** [jquense/react-big-calendar#1858]
#### Do you want to request a _feature_ or report a _bug_?
Feature
#### What's the current behavior?
React big calendar is not supporting other types of calendars and only supports Gregorian Calendar.

#### What's the expected behavior?

I want to add a pull request so that the calendar can support other types of calendars (Jalali/Hijri/Chinese/...)
Is it possible to access culture inside utils/dates to be able to manipulate some functions in dates.js based on the culture?

**Comment by huzeifajaha** [comment]
did u find the support for this
