### ISSUE TITLE
Drag event between resources

### ISSUE THREAD

**Issue by teundev** [jquense/react-big-calendar#1862]
#### Do you want to request a _feature_ or report a _bug_?
Actually I want to ask a question about React Big Calendar with DnN addon.

#### What's the current behavior?
Can't seem to get Drag and Drop between different resources to work. I can't find any trigger on the React-Big-Calendar with DnN which adds the target resource column as argument. All I found regarding this issue is the following: 
https://github.com/jquense/react-big-calendar/pull/873

#### What's the expected behavior?
In addition to arguments start and end, I expected several triggers (like onDropEvent, onEventResize) to include resource as argument. 

![image](https://user-images.githubusercontent.com/63717506/107759586-cec3f400-6d28-11eb-8d74-92ae535acc85.png)

Does anyone perhaps have a solution for this?

**Comment by nlevchuk** [comment]
@teundev Hi. Seems the [demo](https://github.com/jquense/react-big-calendar/pull/873/files#diff-dafea9a52abfd226c2f2e7bd516dece2e7cb8f2147809cb63685b0b9514b49a4) should work for you. There is `onEventDrop` callback which takes an object parameter with [`resourceId`](https://github.com/jquense/react-big-calendar/pull/873/files#diff-dafea9a52abfd226c2f2e7bd516dece2e7cb8f2147809cb63685b0b9514b49a4R60) key. This is actual ID of a resource which you drop event on

**Comment by teundev** [comment]
@nlevchuk Hi, it seems to work now. I am using TypeScript and had wrongly defined the type. Thanks.

**Comment by gdeggau** [comment]
> @nlevchuk Hi, it seems to work now. I am using TypeScript and had wrongly defined the type. Thanks.

Hey man, could you share your solution? I'm struggled with same problem ah you had.

**Comment by cutterbl** [comment]
There is an [example of this in the docs](https://jquense.github.io/react-big-calendar/examples/index.html?path=/story/addons-drag-and-drop--example-2).
