### ISSUE TITLE
momentLocalizer is not a function

### ISSUE THREAD

**Issue by saadansari11** [jquense/react-big-calendar#1866]
#### Do you want to request a _feature_ or report a _bug_?
A bug
#### What's the current behavior?
Not working

**Comment by Lipemenezes** [comment]
@saadansari11 just started a new component using it and it's working as expected for me:

`

import React from 'react'

import { Calendar, momentLocalizer } from 'react-big-calendar'

import moment from 'moment'

const localizer = momentLocalizer(moment)

`

**Comment by saadansari11** [comment]
@Lipemenezes I used FullCalendar component instead of react-big-calendar

**Comment by cutterbl** [comment]
stale
