### ISSUE TITLE
DragAndDrop calendar clicking on empty time slot raises Cannot read property 'getBoundingClientRect' of null error

### ISSUE THREAD

**Issue by luksari** [jquense/react-big-calendar#1878]
#### Do you want to request a _feature_ or report a _bug_?
Report a bug

#### What's the current behavior?

- When user clicks empty time slot in the calendar
- And calendar is combined with drag & drop functionality
- Then error `Cannot read property 'getBoundingClientRect' of null` appears

[Codesandbox](https://codesandbox.io/s/react-big-calendar-drag-and-drop-events-between-months-forked-8khs6)
[Gif](https://recordit.co/g7bx9g18Zi)

Versions:
- React: 17.0.1
- react-dom: 17.0.1
- react-big-calendar: 0.33.0

#### What's the expected behavior?

The event should be fired correctly for given selection without raising an error

**Comment by jquense** [comment]
@ehahn9 I think this may be you?

**Comment by ehahn9** [comment]
sounds like it :-( I'll take a look shortly.

**Comment by ehahn9** [comment]
apologies for the regression. This case worked in my storybook story, but not in the compiled examples. Alas, the DnD is showing its age and is tough to work on and even tougher to unit test :-( - really could use a rewrite. In the meantime, apologies for introducing this regression!

**Comment by luksari** [comment]
Thank you guys for quickly solving this issue, great job 🎉
