### ISSUE TITLE
calendar fails on render march 2021

### ISSUE THREAD

**Issue by FrankSiret** [jquense/react-big-calendar#1885]
#### Do you want to request a _feature_ or report a _bug_?
> Report a _bug_
#### What's the current behavior?
> The calendar fail on render March 2021

Day 13 is duplicate and all consecutive days are in the wrong position, see the picture below. And then look at the April 3 to see how it render out of the calendar area

![image](https://user-images.githubusercontent.com/53590759/111088410-6cb00780-84fd-11eb-88ac-8492ffa89d7e.png)

**Comment by FrankSiret** [comment]
I be checking other months, and I figure out that all March for every Years fail on the render, inclusive some time the day of the week fails render too, see in the below picture
![image](https://user-images.githubusercontent.com/53590759/111089855-f19e1f80-8503-11eb-8a88-7fd5253de4ac.png)

**Comment by cutterbl** [comment]
resolved
