### ISSUE TITLE
Drag and Drop and resize bugs on month view

### ISSUE THREAD

**Issue by darkcattz** [jquense/react-big-calendar#1886]
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?

Hello, 

Since 0.33.2 version, Drag and drop is unusable on month view. : The dragged Dom element is not under the cursor during the drag.
Same problem with right resize. The resized dom element size one more day (eg: 3 days instead of 2) 

No problems on 0.32 version for the drag and drop. But the resize was not functional on 0.32

No problems on week views, just on month view.

Version of React 17.01
Browser : Google Chrome 89

#### What's the expected behavior?

Same DD has 0.32 version.

**Comment by FedeLacabaratz** [comment]
Hi guys! same issue over here, is there any fix available? somebody?

It would be highly appreciated.

Thanks in advance

**Comment by tiwatson** [comment]
> somebody? 

Source is available for anyone to edit. It appears this should do the trick: 
https://github.com/jquense/react-big-calendar/pull/1892/files

**Comment by Virthuss** [comment]
There is a similar issue on the week view when extending all-day events. Because of the offset it's often impossible to extend events until Sunday.

**Comment by nabati** [comment]
I wonder if this is a related issue;

See the erratic behavior here in week view.

![recording (19)](https://user-images.githubusercontent.com/1499050/112758582-75b9d200-8fef-11eb-80a0-22436508d2a3.gif)

**Comment by tiwatson** [comment]
https://github.com/jquense/react-big-calendar/pull/1892 was merged and `0.33.3` was released.

This issue can be closed.

**Comment by DanielBailey-web** [comment]
Is anyone else having problems with this in 0.33.6?

**Comment by stoqel33** [comment]
> Is anyone else having problems with this in 0.33.6?

Yes, I have the same problem
