### ISSUE TITLE
How to hide night hours from day / week views?

### ISSUE THREAD

**Issue by ciocan** [jquense/react-big-calendar#1890]
How do I change the layout of the da / week view?

In my case, the night hours take unnecessary space because events are in daytime only.

![Screenshot 2021-03-19 at 07 49 09](https://user-images.githubusercontent.com/4984377/111748322-4a651380-8888-11eb-95a4-85f73eeef2ae.png)

**Comment by AustinRobinson** [comment]
You can specify min and max props to your calendar like this:
```js
min={moment('8:00am', 'h:mma').toDate()}
max={moment('9:00pm', 'h:mma').toDate()}
```

Hope this helps.

**Comment by Israel-Dev** [comment]
@AustinRobinson , you my friend, just saved a lot of time 👏👏👏👏

**Comment by utkarshsystem** [comment]
I want to hide all rows where I do not see any events.

**Comment by cutterbl** [comment]
@utkarshsystem Sounds like you actually want the Agenda view then. That really wouldn't work in a 'week' view...
