### ISSUE TITLE
Layout break at events

### ISSUE THREAD

**Issue by jahncarlos125** [jquense/react-big-calendar#1895]
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?

When having two events where the second event starts at the same ending time as the first event, the layout breaks down below

![image](https://user-images.githubusercontent.com/19418662/112207224-9fd95180-8bf5-11eb-8ef8-58bc607df344.png)

It was observed that this break only occurs when the two events are within the same time slot

#### What's the expected behavior?
They should be one below the other as mentioned here

I want this:
![image](https://user-images.githubusercontent.com/1014326/44469392-c24dfd00-a5fd-11e8-89d3-831debeaae3e.png)

_Originally posted by @LucasBassetti in https://github.com/jquense/react-big-calendar/issues/378#issuecomment-415050193_

**Comment by developerkam** [comment]
I faced the same problem. I think, there is precision error while calculating top position at TimeSlots.getRange function.

**Comment by cutterbl** [comment]
It looks as if you do not have your [step](http://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/props--step) and [timeslot](http://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/props--timeslots) props configured correctly
