### ISSUE TITLE
Add Language on Navigate & Views

### ISSUE THREAD

**Issue by yagiz-aydin** [jquense/react-big-calendar#1896]
#### Do you want to request a _feature_ or report a _bug_?
Feature
Can you assign to me, I want to make tihs feature

#### What's the current behavior?
Interfaces gives static string,
```

export interface Navigate {
    PREVIOUS: 'PREV';
    NEXT: 'NEXT';
    TODAY: 'TODAY';
    DATE: 'DATE';
}
export interface Views {
    MONTH: 'month';
    WEEK: 'week';
    WORK_WEEK: 'work_week';
    DAY: 'day';
    AGENDA: 'agenda';
}
```

#### What's the expected behavior?
Adding Language props on HOC to change Navigation and Views 
`<Calendar language='tr / en / es' String />`

![Adsız](https://user-images.githubusercontent.com/47862703/112616756-27f96a00-8e35-11eb-8b4c-e5c1c1960c1f.png)
bar

**Comment by gaspetcan** [comment]
```
messages= {
    allDay:"",
    previous:"",
    next: "",
    today: "",
    month:"",
    week: "",
    day: "",
    agenda: "",
    date: "",,
    time:"",
    event:"",
    showMore: (total) => `+ ${total} 
}
```
Solved 👍

**Comment by vsla** [comment]
Tanks!

Have to close this issue!

**Comment by Alta1re** [comment]
Is there a way to modify language of shown month, too?
(January, February, March, .....)

**Comment by guinduarte** [comment]
> Is there a way to modify language of shown month, too?
> (January, February, March, .....)

You can use `culture` props.

```
        <Calendar
          localizer={localizer}
          events={events}
          culture="pt"
          startAccessor="start"
          endAccessor="end"
          style={{ height: 500 }}
        />
```

**Comment by Alta1re** [comment]
> > Is there a way to modify language of shown month, too?
> > (January, February, March, .....)
> 
> You can use `culture` props.
> 
> ```
>         <Calendar
>           localizer={localizer}
>           events={events}
>           culture="pt"
>           startAccessor="start"
>           endAccessor="end"
>           style={{ height: 500 }}
>         />
> ```

Thank you, but, unfortunately, nothing change! The names of months and days keep english.
