### ISSUE TITLE
Tooltip takes a lot to show up

### ISSUE THREAD

**Issue by edymerchk** [jquense/react-big-calendar#1906]
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?

Tooltip takes a lot to show up on google chrome, tested on Version 89.0.4389.114
![Screen Recording 2021-04-05 at 02 35 PM](https://user-images.githubusercontent.com/561157/113617750-58eb5300-961c-11eb-9d62-ae7a272436c4.gif)

#### What's the expected behavior?

Be faster?

I also tested this on Firefox and looks like is faster, Safari looks really slow as well.

Thank you for this project <3

**Comment by edymerchk** [comment]
for now I just decided to implement my custom tooltip using react-bootstrap, in case this is helpful for someone else:

```js
import OverlayTrigger from "react-bootstrap/OverlayTrigger";
import Tooltip from "react-bootstrap/Tooltip";

const customEvent = ({ event }) => {
return (
  <OverlayTrigger
    placement={"right"}
    overlay={<Tooltip>{event.name}</Tooltip>}
  >
      <span>{event.name}</span>
  </OverlayTrigger>
  );
};

<Calendar
  ...
  components={{
    event: customEvent,
  }}
/>
```

**Comment by jquense** [comment]
the delay is controlled by the browser, so yeah i custom tooltip is the way to go if want to change this.

**Comment by yash-zorp** [comment]
The custom tooltip works only when you hover on the text in the event slot. I am not getting how to get a custom tooltip on hovering on the whole event slot.
