### ISSUE TITLE
I'm tiring to use it but, I'm not able to use big calendar, please tell me 

### ISSUE THREAD

**Issue by sikandar-kritivity** [jquense/react-big-calendar#1907]
TypeError: Cannot read property 'filter' of undefined
eventsForWeek
F:/test/node_modules/react-big-calendar/dist/react-big-calendar.esm.js:1867
  1864 | } : {};
  1865 | 
  1866 | var eventsForWeek = function eventsForWeek(evts, start, end, accessors) {
> 1867 |   return evts.filter(function (e) {
  1868 |     return inRange(e, start, end, accessors);
  1869 |   });
  1870 | };
View compiled
MonthView._this.renderWeek
F:/test/node_modules/react-big-calendar/dist/react-big-calendar.esm.js:1906
  1903 | var _this$state = _this.state,
  1904 |     needLimitMeasure = _this$state.needLimitMeasure,
  1905 |     rowLimit = _this$state.rowLimit;
> 1906 | events = eventsForWeek(events, week[0], week[week.length - 1], accessors);
       | ^  1907 | events.sort(function (a, b) {
  1908 |   return sortEvents(a, b, accessors);
  1909 | });
View compiled
MonthView.render
F:/test/node_modules/react-big-calendar/dist/react-big-calendar.esm.js:2105
  2102 |   className: clsx('rbc-month-view', className),
  2103 |   role: "table",
  2104 |   "aria-label": "Month View"
> 2105 | }, React.createElement("div", {
       | ^  2106 |   className: "rbc-row rbc-month-header",
  2107 |   role: "row"
  2108 | }, this.renderHeaders(weeks[0])), weeks.map(this.renderWeek), this.props.popup && this.renderOverlay());

**Comment by paweljaneczek** [comment]
Hey @jquense, I have same issue. Why this thread has been closed?

**Comment by paweljaneczek** [comment]
Ok, I know what's the problem. Problem is that events field is undefined. If someone have same issue just set `events={[]}`
