### ISSUE TITLE
Quisiera saber como configurar  react-big-calendar para que mi calendario comience el día de la fecha actual y solo muestre desde la fecha actual en adelante

### ISSUE THREAD

**Issue by villadasonia** [jquense/react-big-calendar#1912]
quisiera poder mostrar solo fechas desde la actual en adelante ,

**Comment by GOI17** [comment]
No se si tenga alguna prop que le puedas pasar para validar esa accion que necesitas, pero lo que puedes hacer es agregarla tu manualmente, modifica el comportamiento por defecto del boton de navegar hacia atras.

const handleOnNavigateBack = params => {
    if (!isNavigationDateBeforeCurrent) navigate();
