### ISSUE TITLE
How to display both resources and events from api on calendar?

### ISSUE THREAD

**Issue by skywalkeryin** [jquense/react-big-calendar#1916]
#### Do you want to request a _feature_ or report a _bug_?
 When load calendar, the page make two api request, one for resource list, one for events, but only the resource header show up, the events didn't display. If I hard code the resource list, the events can display.

**Comment by cutterbl** [comment]
You do this by controlling both your [resources](http://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/props--resources) and [events](http://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/props--events) props via state
