### ISSUE TITLE
Problem at agenda

### ISSUE THREAD

**Issue by rodrigogaraujo** [jquense/react-big-calendar#1924]
#### Do you want to request a _feature_ or report a _bug_?
Bug

Calendar event show at week and don't show at agenda
Can somebody help me?

The prints:
https://github.com/rodrigogaraujo/web_gobarber/blob/master/Screenshot%20from%202021-05-07%2012-23-27.png
https://github.com/rodrigogaraujo/web_gobarber/blob/master/Screenshot%20from%202021-05-07%2012-23-35.png

**Comment by daniloster** [comment]
Hi @rodrigogaraujo , I am facing the same issue. Have you found out what was causing it? I am suspecting there is a range of time that is visible at the agenda view. But, I don't know how to redefine it. I could not see it in the docs.

**Comment by rodrigogaraujo** [comment]
Same issue here

**Comment by daniloster** [comment]
I think I found the filter taking out our events: https://github.com/jquense/react-big-calendar/blob/master/src/Agenda.js#L36-L38

**Comment by daniloster** [comment]
Actually, here is the problem.
https://github.com/jquense/react-big-calendar/blob/master/src/Agenda.js#L150

I am going to add a fix.
```
events = events.filter(event => inRange(event, dates.startOf(date, 'day'), dates.endOf(end, 'day'), accessors))
```

**Comment by daniloster** [comment]
@rodrigogaraujo , it seems the project is not maintained anymore. I will leave a tip here.

- Checkout this project (or download)
- Rename this project `src` folder to `react-big-calendar`
- Copy the folder renamed into your own project at `src/__external__/react-big-calendar`
![Screenshot 2021-05-29 at 12 35 00](https://user-images.githubusercontent.com/1067763/120068892-de1e4180-c07a-11eb-916b-002a010b60c5.png)

- Open your webpack config
- Add the entry `resolve` to your webpack config
```
{
  resolve: {
    alias: {
      'react-big-calendar': [
        __dirname,
        /* relative path from webpack config to new folder copied */ 
        '../../src/__external__/react-big-calendar',
      ].join('/')
    },
  },
  // ... your rest of webpack config
}
```

It should make your webpack look after the package in your source code.

**Comment by pietrofxq** [comment]
@daniloster @rodrigogaraujo the project is still maintaned. Please create PR and we will merge
