### ISSUE TITLE
How to add custom view (start and end date)

### ISSUE THREAD

**Issue by kparkitny** [jquense/react-big-calendar#1930]
Hi there,

I'm looking for some solution to get custom view on react-big-calendar. I saw few examples including view of year (https://github.com/jquense/react-big-calendar/issues/1694) but is there any chance to render custom view using start and end date in this library? 

Many thanks, Chris

**Comment by BillOTei** [comment]
on the same boat, is there a way to pass props to a CustomView?

**Comment by Sergyus** [comment]
https://jquense.github.io/react-big-calendar/examples/index.html#customView
