### ISSUE TITLE
dart-sass or apple silicon support?

### ISSUE THREAD

**Issue by willyxiao** [jquense/react-big-calendar#1933]
#### Do you want to request a _feature_ or report a _bug_?
Request a feature.

#### Requested Feature
I don't believe node-sass supports apple silicon (and won't plan on it), so dart-sass is preferred. I might be totally misunderstanding something here but is there a way of doing custom stylizing with dart-sass instead of node-sass so that it works for node v16 and M1 macbooks?

Thanks!

**Comment by jquense** [comment]
You can just use dart sass if your compiling the sass files yourself

**Comment by Slumber86** [comment]
node-sass is deprecated and only in maintenence mode, so new feature won't be added. 
Also deprecations won't apply lke the new breaking changes like the deprecations of "/" operator.
