### ISSUE TITLE
Feature: Localizer Support in Date Utils

### ISSUE THREAD

**Issue by lenehan2** [jquense/react-big-calendar#1939]
#### Do you want to request a _feature_ or report a _bug_?

Feature

#### What's the current behavior?

Currently, much of the datetime math is handled using the browsers datetime via [date-math](https://github.com/jquense/date-math).

When a timezone other than the user's browser is used, this causes a few unavoidable problems (at least unavoidable to the best of my knowledge).  For instance in the `Week` view, the time will not start at 12:00 am.

Relevant issues: 

https://github.com/jquense/react-big-calendar/issues/1478 (specifically [this comment](https://github.com/jquense/react-big-calendar/issues/1478#issuecomment-770985148))
https://github.com/jquense/react-big-calendar/issues/118

#### What's the expected behavior?

When supplying a timezone/localizer, this timezone should be taken into consideration when making core date arithmetic.

**Comment by cutterbl** [comment]
@lenehan2  React-Big-Calendar now has full timezone support when using either the momentLocalizer or the new luxonLocalizer. The public documentation site is not yet up to date, but if you clone the repo you can run the 'examples' locally, giving you all of the details.
