### ISSUE TITLE
There is not Event Handler for the events 

### ISSUE THREAD

**Issue by phoenixpinpoint** [jquense/react-big-calendar#1946]
#### Do you want to request a _feature_ or report a _bug_?
Request a Feature

#### What's the current behavior?
No event handling for onclick for the events

#### What's the expected behavior?
Event handling function in React.

**Comment by phoenixpinpoint** [comment]
In the mean time you can manually grab each event element and add an onclick with an arrow function to your react function. 
elements[i].onclick=() => this.onEventClick(elements[i]);

**Comment by pietrofxq** [comment]
@phoenixpinpoint have you tried to use the prop `onSelectEvent` ?

**Comment by phoenixpinpoint** [comment]
I had not. I must of missed that option on the API docs. We can mark that down as an ID10-T Error on my part lol.
