### ISSUE TITLE
Vertical display of the days in the week view for each resource

### ISSUE THREAD

**Issue by rawadnasr** [jquense/react-big-calendar#1947]
#### Do you want to request a _feature_ or report a _bug_?
Feature

#### What's the current behavior?
The days for each resource is displayed horizontally in the week view

#### What's the expected behavior?
Customize the week view or create a custom view that displays the days of the week for each resource in a vertical way with a timeline

**Comment by mleister97** [comment]
Any updates?

**Comment by cutterbl** [comment]
Closing as long standing duplicate request.
