### ISSUE TITLE
Time Gutter Element not always sticky

### ISSUE THREAD

**Issue by Sureddy08** [jquense/react-big-calendar#1954]
#### Do you want to request a _feature_ or report a _bug_?
Report a bug

#### What's the current behavior?
Time Gutter element not sticky to left always in Safari 
![image](https://user-images.githubusercontent.com/16860936/120850340-ea077900-c53c-11eb-8bde-18fff9c579ee.png)

You can see the issue by opening this demo link http://jquense.github.io/react-big-calendar/examples/index.html#resource in Safari.

#### What's the expected behavior?
![image](https://user-images.githubusercontent.com/16860936/120850496-2509ac80-c53d-11eb-8d8e-174e30a86186.png)

Looks like If the parent/ancestor of the sticky element has any of the following overflow properties set, position: sticky won't work:

overflow: hidden
overflow: scroll
overflow: auto

**Comment by Sureddy08** [comment]
@pietrofxq Have you came across this issue on your local usage? could you please let us know if any workaround for safari browser. Sticky doesn't work well in other browsers as it did in chrome.

**Comment by cutterbl** [comment]
resolved

**Comment by yrsluv** [comment]
same issue any solutions?
