### ISSUE TITLE
TypeError: e.target.className.includes is not a function

### ISSUE THREAD

**Issue by usmanbinnaeem** [jquense/react-big-calendar#1957]
#### My code:

 const smooth = e => {
      if (e.target.className && e.target.className.includes('SliderContent')) {
        transitionRef.current()
      }
    }

#### error

TypeError: e.target.className.includes is not a function
smooth
http://localhost:3000/static/js/main.chunk.js:1910:52
  1907 | 
  1908 | Object(react__WEBPACK_IMPORTED_MODULE_0__["useEffect"])(() => {
  1909 |   const smooth = e => {
> 1910 |     if (e.target.className.includes('SliderContent')) {
       |                                                  ^  1911 |       transitionRef.current();
  1912 |     }
  1913 |   }; // Resize browser

#### Thanks

**Comment by bartvanandel** [comment]
Your compiled code lacks the `e.target.className` check, so you probably just need a rebuild.

A better solution than inspecting the `className` string is actually to look at the `classList` property instead. See https://developer.mozilla.org/en-US/docs/Web/API/Element/classList

**Comment by usmanbinnaeem** [comment]
thank you
