### ISSUE TITLE
Could not any way to change the border of selected day

### ISSUE THREAD

**Issue by ShahirZain** [jquense/react-big-calendar#1968]
#### i want to change the border of date when i clicked on any but could not found any way to do it

![Screenshot_1](https://user-images.githubusercontent.com/30791669/124307332-20a6d280-db81-11eb-990e-754c3ebdc997.png)

**Comment by duttasuraj93** [comment]
that is expected as this library is not a date picker. it only displays the events during the course

**Comment by ShahirZain** [comment]
i have found a solution so i am closing this
