### ISSUE TITLE
resizable still does not work on react v17.0.2

### ISSUE THREAD

**Issue by anuragnandi** [jquense/react-big-calendar#1999]
Hey guys I've been using rbc on react v16 and it was working great, after updating my react to v17 it seems to be broken. Everything else is working, just the resizable prop does not work, I am not able to drag to resize, can't even see the handlebars to make the action, even after setting it to true.  

I did read here in the issues that this has been fixed but I am not sure why I have the problem. I am sure I am using the latest version of the react-big-calendar. Any help on how I can solve this?
here's what my calendar looks like: 

```
<DragAndDropCalendar
        selectable
        resizable
        onEventResize={resizeEvent}
        onEventDrop={onEventDrop}
        localizer={localizer}
        events={events}
        onSelectSlot={handleSelect}
        defaultView="week"
        scrollToTime={moment() .set({ h: 10, m: 0 }) .toDate()}
        timeslots={2}
        step={15}
        popup
        tooltipAccessor={(e) => e.title}
      />
```

I tried using this version aswell, It does not work for me.
https://github.com/jquense/react-big-calendar/pull/1857

**Comment by martin-trajanovski** [comment]
+1
