### ISSUE TITLE
How to edit number of event in a day?

### ISSUE THREAD

**Issue by sherkot** [jquense/react-big-calendar#2006]
Good morning,
I would like to change the number of items that are displayed in a single day. The single item has been customized as pictured. Is there any way to change this number? I would like to change it after the third event (so 3 events and then the +X events button)

![image](https://user-images.githubusercontent.com/16966007/129419084-d04c5945-8b7f-498f-a607-5fcc43cabe33.png)

**Comment by cutterbl** [comment]
The number of events, displayed within a day, is completely dependent upon the available space at the time of render.
