### ISSUE TITLE
Help on changing the default errror message on Agenda View

### ISSUE THREAD

**Issue by AliciaTannn** [jquense/react-big-calendar#2015]
![Screenshot 2021-08-28 at 7 21 46 PM](https://user-images.githubusercontent.com/38933559/131216336-20eee6ff-b9c7-4fd1-8d9d-e8cfc09fa553.png)

Can i get help on how to change the error message in Agenda when there is no events? Maybe change the message to another message.

**Comment by dpbfh** [comment]
You've probably already figured it out yourself, but if anyone has the same problem, you could use the message attribute of the calendar.
                    <Calendar messages={{
                        noEventsInRange: 'noEventsInRange',      
                    }} 
/>

**Comment by nickcarnival** [comment]
I wanted to embed JSX into the `messages` prop but the types are defined as  [`string | undefined`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-big-calendar/index.d.ts) in definitely-typed. 

You _can_ embed JSX like so, I'm using the `momentLocalizer` this may not work with other localizers I haven't tested it. 

```tsx
        messages={{
          noEventsInRange: (
            <div className="w-full h-full flex flex-col items-center border-2 rounded-md p-10">
              <span className="text-xl">No events in range</span>
            </div>
          ) as ReactNode as string
        }}
```
