### ISSUE TITLE
Typescript type definition for EventProps is incorrect

### ISSUE THREAD

**Issue by aaronbabaron** [jquense/react-big-calendar#2016]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?
`EventProps` only has `event` and `title` in the typedef, but there are more props actually passed in
Current typedef: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-big-calendar/index.d.ts#L224

#### What's the expected behavior?
I'd expect all values passed in to be available on the `EventProps`. A lot of them are very useful, such as `continuesPrior` and `continuesAfter`, especially if we want to use standard drag and drop while also having access to these props. Similar props are available on the wrapper (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-big-calendar/index.d.ts#L250), but changing the wrapper disables use of standard drag and drop.

It seems a lot of other props are missing on a lot of the typedefs as well.

**Comment by DanielBailey-web** [comment]
You can (and probably should) extend the default EventProps with your own custom attributes that you are adding to your events. Something like:
```ts
export interface EventProps extends Object, Event {
  id: string;
  className?: string;
  title: string | ReactNode;
  type: CalendarEventTypes;
  allDay: boolean;
  start: Date;
  end: Date;
  styles?: CSSProperties;
  domAttributes?: HTMLAttributes<HTMLDivElement> &
    DOMAttributes<HTMLDivElement>;
  toolTip: (e: EventProps) => string;
  errorType: CalendarEventErrors;
}
```

But also this is not the place to complaine about DefinitelyTyped errors. As those types are not maintained in this repo.

**Comment by pietrofxq** [comment]
Yes, all type issues should be fixed on DefinitelyTyped for now. I am in the process for converting the whole codebase to TS, but it will take time. You can add me as reviewer in the PR there since I already fixed some types before
