### ISSUE TITLE
How to change week start and end?

### ISSUE THREAD

**Issue by mherkarapetyan4** [jquense/react-big-calendar#2025]
Hi everyone , 
For example i peek 10/06/2021 and i want to make week calendar to start 10/06/2021 even if it not Monday (or Sunday)

**Comment by DanielBailey-web** [comment]
use date-fns as your localizer? then you can do something like this:


```ts
import { getDay } from "date-fns";
const dayOfWeekToStartOn = getDay(new Date("10/16/2021"));

const localizer = dateFnsLocalizer({
  format,
  parse,
  startOfWeek: (
    date: number | Date,
    options?:
      | {
          locale?: Locale | undefined;
          weekStartsOn?: 0 | 1 | 2 | 3 | 4 | 5 | 6 | undefined;
        }
      | undefined
  ) => startOfWeek(date, { ...options, weekStartsOn: dayOfWeekToStartOn }),
  getDay,
  locales: {
    "en-US": require("date-fns/locale/az"),
  },
});
```
make sure to `import { dateFnsLocalizer } from "react-big-calendar";` 

If you want to make it dynamic, you could memoize the localizer and put it inside the components you are calling Calendar in.

**Comment by cutterbl** [comment]
A better way to handle this is to provide a [custom Week View](http://jquense.github.io/react-big-calendar/examples/index.html#prop-components). [Here is a CodeSandbox](https://codesandbox.io/s/z2jqpmlr14?file=/src/MyWorkWeek.component.js:0-945) with an example of a custom Week where a different `range` method was provided for the layout. You can provide your own custom `range` method this way.

```js
Week.range = (date, {localizer}) => {
  const start = // some custom logic to determine your start date
  const end = // some custom logic to determine your end date
  const range = localizer.range(start, end)
}
```
