### ISSUE TITLE
Examples are a bit out of date

### ISSUE THREAD

**Issue by christopher-caldwell** [jquense/react-big-calendar#2029]
### Do you want to request a _feature_ or report a _bug_?

Feature, I suppose

### What's the current behavior?

The examples are using JS class based components and `moment` which recently reached EoL. Not to say moment is no good, but there is not a `date-fns` example.

### What's the expected behavior?

I made a new example using TypeScript, React hooks, `date-fns` and bundled with [Vite](https://vitejs.dev/), [here](https://github.com/christopher-caldwell/react-big-calendar-demo)

**Comment by pietrofxq** [comment]
@christopher-caldwell can you create a PR to add these demos in this repository?

**Comment by christopher-caldwell** [comment]
I think this can be closed now 👍
