### ISSUE TITLE
Wrong duration for Moment localizer

### ISSUE THREAD

**Issue by acocheo** [jquense/react-big-calendar#2033]
https://github.com/jquense/react-big-calendar/blob/ad8defa643692911fd0b00c71b70de94715140a9/src/addons/dragAndDrop/common.js#L44
`star, end `are probably inverted:
https://github.com/jquense/react-big-calendar/blob/ad8defa643692911fd0b00c71b70de94715140a9/src/localizers/moment.js#L181
Result is an negative event duration during drag&drop

**Comment by cutterbl** [comment]
Nice catch! Lot of changes for that timezone support. Thanks for looking out. Just filed PR #2034 for it. As soon as it's reviewed...

**Comment by cutterbl** [comment]
@jquense This issue can now be closed, right?
