### ISSUE TITLE
How do i change the table header text in Agenda View? 

### ISSUE THREAD

**Issue by AliciaTannn** [jquense/react-big-calendar#2035]
![Screenshot 2021-10-04 at 12 11 33 AM](https://user-images.githubusercontent.com/38933559/135762399-daee536c-9d7d-436f-92e3-d36a709ba001.png)

How would i change the table header, Event to another text such as List?

**Comment by cutterbl** [comment]
You can adjust the text on the toolbar by setting the [formats.agendaHeaderFormat](http://jquense.github.io/react-big-calendar/examples/index.html#prop-formats.agendaHeaderFormat), but the only way to change the table headers is by providing your own [custom View component](http://jquense.github.io/react-big-calendar/examples/index.html#prop-components).

**Comment by dpbfh** [comment]
If you only want to change the text of the header, do you think I use the message attribute
`     <Calendar
                        messages={{
                            date: 'Change Date Header',
                            event: 'List',
                        }}
                         />`
this works at least in typescript

**Comment by cutterbl** [comment]
@AliciaTannn  Ah, looking at the source code, @dpbfh is right, you could use the `messages` to change those column headers. `messages={{ date: 'date header', time: 'time header', event: 'event header' }}`.
