### ISSUE TITLE
Can we add a date-picker to calendar header?

### ISSUE THREAD

**Issue by amang95** [jquense/react-big-calendar#2036]
In the. following screenshot, is it possible to inject a date-picker as a dropdown on the highlighted section in Month, Week and Day views?
![Screen Shot 2021-10-04 at 1 34 17 PM](https://user-images.githubusercontent.com/52672332/135897597-2bc7ad80-c40b-4b54-be92-d5806320b569.png)

**Comment by pietrofxq** [comment]
@amang95 you can create a custom toolbar component:

```js
<BigCalendar components={{
 toolbar: function Toolbar(toolbarProps) {

 }
}} />
```

on `toolbarProps` there is the method `onNavigate` that you can use to implement the same features as Month, Week, Today, Back, Next etc
