### ISSUE TITLE
culture in components.X.header

### ISSUE THREAD

**Issue by decimoseptimo** [jquense/react-big-calendar#2041]
when setting components.X.header, as in
```js 
components={{ week: { header } }}
...
const header: FC<HeaderProps> = ({ date, localizer }) => (
  <>{localizer.format(date, 'D', culture)}</>
);
```
@eps1lon Is there a reason why culture [was removed](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/403944318959c0ff68984fae98f5285d9245e4da#diff-81e071c666c9d6dc0b38ef8937117d3982b1677e0678af6fa395c5d4774f5743L100) from HeaderProps? because here ts throws errors as [culture is required by localizer.format](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/c520b66719d92e8cf1caba44cdd8f067879124a0/types/react-big-calendar/index.d.ts#L311)

So either it isn't being passed to header, or it isn't required by format.

**Comment by cutterbl** [comment]
I'm not overly familiar with TS, and don't know who changed those TS definitions, so I can't speak to that. Maybe you can submit a PR to the definition repo?

**Comment by decimoseptimo** [comment]
If i understand you, although localizer.format requires a culture. Somehow RBC will take care of that, so we could say, it is no longer required... if so, I can definitely update the ts definition. 

But then again, what about [formats](https://jquense.github.io/react-big-calendar/examples/index.html#prop-formats)? in the examples culture is available as a prop, and it is being used... it is not homogeneus.

**Comment by decimoseptimo** [comment]
I'll pr to definitelyTyped then, and will also take a look at the aforementioned docs
