### ISSUE TITLE
Is it possible to customize event wrapper ?

### ISSUE THREAD

**Issue by corentindesfarges** [jquense/react-big-calendar#2071]
Hi,

Is there any way to properly customize the "event" style in the calendar, by passing a custom css based or whatever.
I need to do something like that, and I can't believe I'm the only one who need that king of feature.

![image](https://user-images.githubusercontent.com/5452616/145146031-7b03018a-e1f5-440c-80e2-5b10d2fa432a.png)

Thanks !

**Comment by cutterbl** [comment]
You can use the [eventPropGetter](http://jquense.github.io/react-big-calendar/examples/index.html#prop-eventPropGetter) prop to add custom classes and styling to 'events'.

```js
(
    event: Object,
    start: Date,
    end: Date,
    isSelected: boolean
) => { className?: string, style?: Object }
```

**Comment by corentindesfarges** [comment]
Thanks a lot, that's exactly what I needed. Here is a small example of implementation.
Hope it will help others.

```jsx
...
const eventStyleGetter = (event, start, end, isSelected) => {
  return {
    style: {
      opacity: isSelected ? 1 : 0.9,
      borderColor: event.color,
      backgroundColor: event.color,
    },
  };
};

function MyCalendar(props) {
  const { events } = props;
  return (
    <Calendar
      events={events}
      defaultView="week"
      localizer={localizer}
      eventPropGetter={eventStyleGetter}
    />
  );
}
```
