### ISSUE TITLE
Bug with listeners in Selection.teardown method

### ISSUE THREAD

**Issue by vmstarchenko** [jquense/react-big-calendar#2072]
#### Bug report
I am not sure but visually there is a bug with `Selection.teardown` method. Everywhere in this file variable `_listeners` is used but in `teardown` method it doesn't starts with underscore:
`this._listeners = Object.create(null)`
vs
`this.listeners = Object.create(null)`

(https://github.com/jquense/react-big-calendar/blob/master/src/Selection.js#L47 vs https://github.com/jquense/react-big-calendar/blob/master/src/Selection.js#L102)

It might cause a problem with event listeners unbinding.

**Comment by cutterbl** [comment]
@vmstarchenko Thanks again for pointing this out. It has now been resolved.
