### ISSUE TITLE
Help error Uncaught TypeError: d[("get" + method)] is not a function with date-fns

### ISSUE THREAD

**Issue by RatchetNine76** [jquense/react-big-calendar#2073]
Hello, I am new to this and I am still learning on how to do it. I am making a calendar project using date-fns instead of moment, and have a function that would manually input the title, date, and time using DateTimePicker from https://www.npmjs.com/package/react-datetime-picker, for me to add user event to save into localstorage.
![calendarProject](https://user-images.githubusercontent.com/33405640/145208776-422f2afb-317c-4eac-b163-a02ab8a02dbe.png)
It would save successfully into localstorage, but the page will go blank when viewing it in week and day and when I try to check in the localstorage that to me there is nothing wrong with the data when I compare with existing date and the my test input. I dont know where it went wrong.
`import { useEffect, useState } from "react"
import format from "date-fns/format"
import parse from 'date-fns/parse'
import startOfWeek from 'date-fns/startOfWeek'
import getDay from 'date-fns/getDay'
import { dateFnsLocalizer } from "react-big-calendar"
import DateTimePicker from "react-datetime-picker/dist/DateTimePicker"
import 'react-datetime-picker/dist/DateTimePicker.css'
import 'react-calendar/dist/Calendar.css'
import 'react-clock/dist/Clock.css'
import { Calendar } from "react-big-calendar"
import 'react-big-calendar/lib/css/react-big-calendar.css'
import events from "../data/events"

const locales ={
    "en-US" : require("date-fns/locale/en-US")
}

const localizer = dateFnsLocalizer({
    format,
    parse,
    startOfWeek,
    getDay,
    locales
})

function Body() {
    const [ newEvent, setNewEvent ] = useState({ title: "", start: "", end: ""})
    /*const [ allEvents, setAllEvents ] = useState(events)*/
    /*const [currentEvent, setCurrentEvent] = useState("")*/

    const [ allEvents, setAllEvents ] = useState(() => {

        const savedEvents = localStorage.getItem("events")

        if (savedEvents) {
            return JSON.parse(savedEvents)
        } else {
            return events
        }
    })

    useEffect(() => {
        localStorage.setItem("events", JSON.stringify(allEvents))
    }, [allEvents])

    function handleAddEvent(e){
        e.preventDefault()
        
        if (newEvent !== "") {
            setAllEvents([
                ...allEvents,
                newEvent
            ])
        }
        
        console.log(newEvent)
        setNewEvent({ title: "", start: "", end: "" })
    }  
    
    return (
        <div className="cal-body">
            <div className="picker">
                <input 
                    type="text"
                    value={newEvent.title} 
                    onChange={(e) => setNewEvent({...newEvent, title: e.target.value})}
                />
                <DateTimePicker
                    disableClock={true}
                    disableCalendar={true}
                    selected={newEvent.start}
                    dayPlaceholder="dd"
                    monthPlaceholder="mm"
                    yearPlaceholder="yyyy"
                    hourPlaceholder="hh"
                    minutePlaceholder="mm"
                    onChange={(start) => setNewEvent({...newEvent, start})}
                />
                <DateTimePicker
                    disableClock={true}
                    disableCalendar={true}
                    style={{
                        background: "white"
                    }}
                    selected={newEvent.end}
                    dayPlaceholder="dd"
                    monthPlaceholder="mm"
                    yearPlaceholder="yyyy"
                    hourPlaceholder="hh"
                    minutePlaceholder="mm"
                    onChange={(end) => setNewEvent({...newEvent, end})}
                />
                <button className="button" onClick={handleAddEvent}>Add</button>
            </div>
            
            <div className="calendar">
                <Calendar
                    selectable
                    localizer={localizer}
                    events={allEvents}
                    startAccessor="start"
                    endAccessor="end"
                    popup="true"
                    onSelectEvent={() => setOpenModal(true)}
                    style={{ 
                        height: 500, 
                        margin:"50px", 
                        background: "white", 
                        color: "black",
                        border: "2px solid black" }}
                />
            </div>
        </div>
    )
}

export default Body
`

**Comment by cutterbl** [comment]
This can happen when you do not use true `Date` instances for event start and end dates

**Comment by RatchetNine76** [comment]
I'm sorry if I ask a dumb question, but how do I use true `Date` instances? I dont think I encountered that through react-big-calendar documentation

**Comment by cutterbl** [comment]
Every 'date' type prop is a `PropType.instanceOf(Date)`. So, when considering your event 'edit' form, you'll have to convert your string date representation to a true `Date`, i.e. `start: new Date(form.startDate)`

**Comment by RatchetNine76** [comment]
would this function work on converting it to true `Date` and save to localstorage?
```
function convert(str) {
        var date = new Date(str),
            mnth = ("0" + (date.getMonth()+1)).slice(-2),
            day  = ("0" + date.getDate()).slice(-2);
        var hours  = ("0" + date.getHours()).slice(-2);
        var minutes = ("0" + date.getMinutes()).slice(-2);
        return [ date.getFullYear(), mnth, day, hours, minutes ].join(", ");
    }
```

and I also change the the line  `onChange={(start) => setNewEvent({...newEvent, start})}` to
 `onChange={(start) => setNewEvent({...newEvent, start: new Date(convert(start))})}`
 and also the line:` const [ newEvent, setNewEvent ] = useState({ title: "", start: "", end: ""})` to
`const [ newEvent, setNewEvent ] = useState({ title: "", start: new Date(0), end: new Date(0)})`

After testing this, it would no longer save in localstorage nor would show into calendar or console.log

**Comment by RatchetNine76** [comment]
After trying to fix the issue, I somehow get it to work somewhat, as after submitting new test event and saving to localstorage, when viewing month,week,and day would work fine. But the problem is that when I refresh the page, even though the new test event is still there and be viewed in month, it will go blank when viewing in Week and Day and have the same error

**Comment by cutterbl** [comment]
You `JSON.stringify()` your events, when putting them in local storage, and probably `JSON.parse()` them, pulling them out of storage. `JSON.stringify()` will convert a `Date` to a string, but `JSON.parse()` will not convert that back to a `Date` object.
