### ISSUE TITLE
node-sass

### ISSUE THREAD

**Issue by jwhite88** [jquense/react-big-calendar#2079]
Older version of node-sass will not will not allow full install of dependencies to run examples.  Installation eventually quits and displays errors.  I'm using NodeJS version 16.13.1.

Regards

**Comment by jquense** [comment]
I don't think we support node-sass anymore, it's been deprecated and most people should switch to using dart sass

**Comment by cutterbl** [comment]
@jquense It's the RBC current dependency for generating css from the sass files. I'll replace it and submit a PR.

**Comment by cutterbl** [comment]
@jwhite88 This is now fixed in release 0.38.2.
