### ISSUE TITLE
Failed to compile with 0.38.2

### ISSUE THREAD

**Issue by TrentMcGinnis** [jquense/react-big-calendar#2087]
#### What's the current behavior?
My code won't compile and is throwing this error

SassError: Invalid CSS after "...percentage(math": expected expression (e.g. 1px, bold), was ".div(1, 7)) !defaul"
redacted:         on line 11 of ../../node_modules/react-big-calendar/lib/sass/variables.scss
redacted:         from line 1 of ../../node_modules/react-big-calendar/lib/sass/styles.scss
redacted:         from line 10 of src/scss/style.scss
redacted: >> $segment-width: percentage(math.div(1, 7)) !default;

#### What's the expected behavior?
Not sure, but it is stopping my code from compiling. I have gone back to 0.38.1 and this solved this issue for now. Just wanted to make it known.

**Comment by cutterbl** [comment]
What are you using for compiling your SASS?

**Comment by TrentMcGinnis** [comment]
Node-sass 6.0.1 @cutterbl

**Comment by sdumjahn** [comment]
You need to change `node-sass` package to `sass`

**Comment by cutterbl** [comment]
@TrentMcGinnis [node-sass](https://github.com/sass/node-sass) has been deprecated (see warning at top of README on linked page), which is why RBC switched to pure `sass`. They have made changes to how they handle math, which is why our sass code has been updated.
