### ISSUE TITLE
Trigger drill down on event select

### ISSUE THREAD

**Issue by reediculous456** [jquense/react-big-calendar#2093]
#### What's the expected behavior?
I'm trying to set up the calendar to start on the month view and then drill down to the agenda view when the user selects an event. I have the month view drill down set to agenda, however it only triggers when you click the date header or the "see more" label.
Is there a way to drill down on select?

**Comment by cutterbl** [comment]
The you would provide a custom [onSelectEvent](http://jquense.github.io/react-big-calendar/examples/index.html#prop-onSelectEvent) method, and take into account your current `view` (which you would control). Some pseudo code might be

```js
const onSelectEvent = (ev) => view === Views.MONTH ? setView(Views.AGENDA) : doSomethingWith(ev);
// ...
<Calendar
  onSelectEvent={onSelectEvent}
```

Though I have to say that from a UX point of view this might confuse a user. If you think of any other calendar application (Outlook, Google Calendar, etc), the typical behavior of 'selecting' an event is typically to see the details of that event. But, that's my $.02. Something like what I said above would work.
