### ISSUE TITLE
having problem in month view in march

### ISSUE THREAD

**Issue by zohrefarzam** [jquense/react-big-calendar#2094]
hi,
thanks for your awsome library. it works fine till now but in march view doesnt display correctly and its wierd. i attach its behavior. 
please let me know about it.
![march view](https://user-images.githubusercontent.com/62729825/148221966-7c5e40fd-5deb-4f84-be85-441b86714c07.png)

**Comment by cutterbl** [comment]
When I look at March 2022, I do not see this at all. You are including the stylesheet or importing the SASS? What does your code look like?

**Comment by DanielBailey-web** [comment]
Uhh, Something is also wrong with you days. (March 21 is displayed twice) This means it is probably a problem with your localizer. Can you post your localizer code? (or better yet a minimal example)

**Comment by zohrefarzam** [comment]
hi, thanks for your feedback. this is my localizer code
const localizer = useMemo(() => {
    moment.locale(calendarContext.locale);
    //@ts-ignore
    moment.bindCalendarSystemAndLocale();
    return momentLocalizer(moment-timezone);
  }, [calendarContext.locale]);
 i use moment-timezone for ablity to change timezone eventhogh i dont think thats the problem i chnage it to moment library and again i have it :((
its a huge problem i dont how can i fix this.

**Comment by DanielBailey-web** [comment]
@zohrefarzam  Do you have a minimal reproducible example?

**Comment by zohrefarzam** [comment]
> @zohrefarzam Do you have a minimal reproducible example?
hi, thanks again :)
i did what you say .
import moment from 'moment'
import 'moment-timezone' // or 'moment-timezone/builds/moment-timezone-with-data[-datarange].js'. See their docs
import { Calendar, momentLocalizer } from 'react-big-calendar'

// Set the IANA time zone you want to use
moment.tz.setDefault('Europe/Paris')

// Setup the localizer by providing the moment Object
// to the correct localizer.
const localizer = momentLocalizer(moment) // or globalizeLocalizer

export const Home = props => (
  <div>
    <Calendar
      localizer={localizer}
      events={[]}
      date={'Wed Mar 09 2022 14:48:14 GMT+0330 (Iran Standard Time)'}
      startAccessor="start"
      endAccessor="end"
    />
  </div>
)
it works normally tii i change timezone to 'Asia/tehran'
i think thats the problem but i dont Know how to fix this because i really need timezone after all

**Comment by zohrefarzam** [comment]
and i check some others timezone and it works fine till i check thats just 'Asia/tehran' timezone problem.
i would appreciate if anyone can help me with this.

**Comment by zohrefarzam** [comment]
i fix it , thanks every one for brainstorming

**Comment by zohrefarzam** [comment]
i fix it , thanks every one for brainstorming

**Comment by DanielBailey-web** [comment]
> 

What was the problem?

**Comment by zohrefarzam** [comment]
> > 
> 
> What was the problem?

its because of iran timezone has changed for 3:30 to 4:30 after iranian new year. i remove moment-timezone default when timezone selected on iran and it fixed.
