### ISSUE TITLE
"UNSAFE_componentWillReceiveProps " and "findDOMNode is deprecated in StrictMode" errors

### ISSUE THREAD

**Issue by hanuz06** [jquense/react-big-calendar#2104]
When I open a page with Calendar. I get these errors in React strict mode. It looks likes somethings is inside component.

![image](https://user-images.githubusercontent.com/17211293/150046359-5c4eda4a-fe32-4d3b-94d2-f802e1a7ff9b.png)

![image](https://user-images.githubusercontent.com/17211293/150046170-210a3181-f1e6-4cf2-97c8-bf235e4719f3.png)

**Comment by cutterbl** [comment]
These are deprecation warnings from the React library, telling you that these two things will eventually be deprecated in the library. They will not create an issue in current production code.

**Comment by hanuz06** [comment]
Okay. Gotcha. Thank you.

**Comment by SaT-hisH** [comment]
@cutterbl  can you share the sample

**Comment by cutterbl** [comment]
@SaT-hisH share what sample?

**Comment by SaT-hisH** [comment]
@cutterbl  how to avoid this error

**Comment by cutterbl** [comment]
@SaT-hisH It's not an error. It's a warning. Read my previous comment above.

**Comment by SaT-hisH** [comment]
@cutterbl  can you tell me how to solve?

**Comment by cutterbl** [comment]
There is nothing solve. It's a **warning** from the React library. It will always be there, until such time as we update Big Calendar to no longer use those methods. It's on our roadmap.

**Comment by SaT-hisH** [comment]
@cutterbl  got it thanks
