### ISSUE TITLE
Possible error with React 17.0.2 UNSAFE

### ISSUE THREAD

**Issue by WildOsk** [jquense/react-big-calendar#2105]
I have enabled `React.StrictMode`

My code looks like:

![image](https://user-images.githubusercontent.com/62115925/150151183-a20ea595-9566-4c2b-ae7b-0ae2a382cfc9.png)

And i keep receiving those errors in **console**:

![image](https://user-images.githubusercontent.com/62115925/150151425-f55f5e48-4464-4464-a337-9bdcd9454204.png)

**Comment by cutterbl** [comment]
These are not errors. They are warnings, related to React features that will eventually be deprecated. Big Calendar will continue to function with React 17.0.2, as these console warning have no effect on code function.

**Comment by WildOsk** [comment]
Okay. Thank you
