### ISSUE TITLE
I need to stop onSelectSlot

### ISSUE THREAD

**Issue by decimoseptimo** [jquense/react-big-calendar#2106]
Either through stopProgation or preventDefault, but i need to be able to stop it.
I'm researching this, if anyone has an idea let me know.

**Comment by pietrofxq** [comment]
not sure if I understand, can't you just `return` and do nothing?

**Comment by decimoseptimo** [comment]
- I have Popovers wrapping individual events (upon event click, a popover with event details opens up)
- I have Popovers wrapping calendar cells ([onSelectSlot]. Upon cell click, a popover with create event opens up)
- The popovers have an onClickOutside prop that closes the popover

My inital hipothesis is that both are MouseEvents. Naturally a click event may bubble or target both. As I need that when one closes the other doesn't open. They need to cancel each other, so that only one takes place.

But it seems that onSelectSlot is always ocurring. It may not be a mouseEvent (doesn't receive `e, event` props).
Seems like a flaw to me, I'm researching into the repo for a solution.

**Comment by cutterbl** [comment]
Do you not differentiate by using both `onSelectEvent` and `onSelectSlot`?

**Comment by decimoseptimo** [comment]
I am not using `onSelectEvent `because there's no way to differenciate events that span multiple rows (e.g. month view).
Its [docs](https://jquense.github.io/react-big-calendar/examples/index.html#prop-onSelectEvent) and ts signature says it receives `e, event` but in reality it's `slotInfo`.

I solved that by https://github.com/jquense/react-big-calendar/issues/2081

But still `onSelectEvent, onSelectSlot `doesn't seem to be mouse events nor can be stopped. Im not sure that you mean by differentiate.

**Comment by cutterbl** [comment]
`onSelectEvent` does get the `event`, not `slotInfo` (which is only sent from `onSelectSlot`). I just tested this, and the signature is correct `(event: Object, ev: SyntheticEvent) => any`. The `event` does include `start` and `end`, which would allow you to know if it spanned multiple rows (if you were in 'month' view).

Just so happens I'm working on some new documentation right now, and was able to quickly test this by applying multiple `on` handlers simultaneously. It very easily knew the difference between selecting a `slot` and an `event`. Here's the code from the 'story' I used to test it.

```js
import React, { useCallback, useRef, useEffect, useMemo } from 'react'
import moment from 'moment'
import { Calendar, momentLocalizer } from 'react-big-calendar'
import demoEvents from '../resources/events'

const mLocalizer = momentLocalizer(moment)

function buildMessage(calEvent, eventName) {
  return `[${eventName}] an 'event' selection was made with:
  ${JSON.stringify(calEvent, null, 2)}`
}

export function OnSelectEvent() {
  const clickRef = useRef(null)

  useEffect(() => {
    /**
     * What Is This?
     * This is to prevent a memory leak, in the off chance that you
     * teardown your interface prior to the timed method being called.
     */
    return () => {
      window.clearTimeout(clickRef?.current)
    }
  }, [])

  const onSelectEvent = useCallback((calEvent) => {
    /**
     * Here we are waiting 250 milliseconds (use what you want) prior to firing
     * our method. Why? Because both 'click' and 'doubleClick'
     * would fire, in the event of a 'doubleClick'. By doing
     * this, the 'click' handler is overridden by the 'doubleClick'
     * action.
     */
    window.clearTimeout(clickRef?.current)
    clickRef.current = window.setTimeout(() => {
      window.alert(buildMessage(calEvent, 'onSelectEvent'))
    }, 250)
  }, [])

  const onDoubleClickEvent = useCallback((calEvent) => {
    /**
     * Notice our use of the same ref as above.
     */
    window.clearTimeout(clickRef?.current)
    clickRef.current = window.setTimeout(() => {
      window.alert(buildMessage(calEvent, 'onDoubleClickEvent'))
    }, 250)
  }, [])

  const onSelectSlot = useCallback((slotInfo) => {
    /**
     * Notice our use of the same ref as above.
     */
    window.clearTimeout(clickRef?.current)
    clickRef.current = window.setTimeout(() => {
      window.alert(buildMessage(slotInfo, 'onSelectSlot'))
    }, 250)
  }, [])

  const defaultDate = useMemo(() => new Date(2015, 3, 1), [])

  return (
    <div className="height600">
      <Calendar
        defaultDate={defaultDate}
        events={demoEvents}
        localizer={mLocalizer}
        onDoubleClickEvent={onDoubleClickEvent}
        onSelectEvent={onSelectEvent}
        onSelectSlot={onSelectSlot}
        selectable
      />
    </div>
  )
}
```

**Comment by decimoseptimo** [comment]
Some clarifications/corrections:
- `onSelectEvent ` signature `(event: Object, e: SyntheticEvent) => any` is incorrect. It does receive `event` (rcb event) but does not `e` (SyntheticEvent).
- event's `start, end`, allow to know if an event spanned multiple rows, but does not allow to diffenciate them as unique "touch targets" (did i click a given event on the first row, or on the second row? which e.currentTarget was it? where a popover should open?) [[solved with](https://github.com/jquense/react-big-calendar/issues/2081#issuecomment-999981099)].
- and still `onSelectEvent, onSelectSlot `doesn't seem be able to be stopped. Imagine there's intermediate `onCLickOutside `event. And a action like: "Open event popover, onClickOutside (click on the cell/slot, stopPropagation), on onSelectSlot
 doesn't fire" is wanted.

**Comment by cutterbl** [comment]
I see what you're saying. These event handlers do not seem to get the syntheticEvent, though you seemed to have found some form of workaround for your popover.

So let me ask a different question for you, as I'm not overly familiar with any of the selection code or how to adjust any of it. What is it, exactly, that you are trying to accomplish? You keep mentioning an `onClickOutside`, but I would think you would have that target clicking outside over the popover (to close your popover), so I'm unsure what you're trying to do with these event handlers in this scenairo?

**Comment by decimoseptimo** [comment]
Thanks for asking man, I have setup a [codesandbox](https://codesandbox.io/s/rbc-click-events-ejdsl) based on your code.
Performs these steps:
- click an event (onSelectEvent)
- see the corresponding popover open up
- click on a cell (onClickOutside)
- see pop over close up
- see how (onSelectSlot) takes place (if implemented, this event would open a "create event" popover)

In these particular step scenario, I want to avoid that last event, because thats not how gcal does it. When a event is open, any onClickOutside event closes it, but does not open another popover.

**Comment by cutterbl** [comment]
I see what you mean. I increased the size of the popover, clicked directly on the popover and saw that the event target was the row/cell below it (sometimes).

I tried digging through the selection code a little yesterday, and it's a squirrelly bit of code. I'll try to run some local testing, and if I can figure it out I'll file a PR, but maybe @jquense has some insight...

**Comment by decimoseptimo** [comment]
@cutterbl let me know of any findings, i'll do my own as well. I'm also working on an update to DefinitelyTyped, where rbc is behind. Apparently strings are no longer supported as date inputs is lots of places.

**Comment by cutterbl** [comment]
@decimoseptimo When you get a chance, pull the `fix/2106` branch and see if that actually covers you here.

**Comment by decimoseptimo** [comment]
Just took a look. The new second param is `undefined`, if you are extrancing it from `bounds`, that was already `undefined`.
```(2) [{…}, undefined]
0:
action: "click"
bounds: undefined
box: {x: 279, y: 194, clientX: 279, clientY: 194}
end: Wed Apr 01 2015 00:00:00 GMT-0700 (Pacific Daylight Time) {}
slots: [Tue Mar 31 2015 00:00:00 GMT-0700 (Pacific Daylight Time)]
start: Tue Mar 31 2015 00:00:00 GMT-0700 (Pacific Daylight Time) {}
[[Prototype]]: Object
1: undefined
length: 2
[[Prototype]]: Array(0)```

**Comment by cutterbl** [comment]
Yeah, and I kind of thought that might be the problem with this. 'Selection' is based upon a mouse (move) event, whereas event selection is either a 'click' or a 'dblclick'.

If I were tackling the same scenario myself, with the current code, I would be managing all state with `useReducer`. My `onSelectEvent`, `onDoubleClickEvent` and `onSelectSlot` handlers would all be triggering some `dispatch`. Since my popover state would also be from that reducer, my click handlers `dispatch` calls could do something like 'if popover open return current state' (to do nothing), while my `onClickOutside` would be on a slightly longer delay (closing the popover).

**Comment by decimoseptimo** [comment]
@cutterbl Pretty much what i ended up doing. And since I'm sharing the same `clickRef` with `onClickOutside` <- a 0 timeout is enough, since the next event `onSelectSlot` cancels the former. I was able to mimic gCal to the T.

Have you noticed that https://jquense.github.io/react-big-calendar/examples/index.html#selectable dragging doesn't work on mobile touch, I wonder if it's due to

>  'Selection' is based upon a mouse (move) event,
