### ISSUE TITLE
Seeking Assistance With New Documentation

### ISSUE THREAD

**Issue by cutterbl** [jquense/react-big-calendar#2115]
Issue:
The current BigCalendar documentation site is not in sync with the repository, missing a number of updates and features. Currently there is no automated process for updating the documentation site (GitHub page) when new packages are created.

Solution:
PR #2108 is a complete rewrite of Big Calendar documentation, located in the `chore/storybookUpgrade` branch. Some of it's highlights include:

- All documentation has been moved to Storybook
- Storybook has been upgraded
- All previous Examples have been updated and included
- Stories, with mdx docs and specific examples, have been created for every prop
- Addon stories, to include examples and prop stories, have been created for DnD
- Guide stories have been created to talk about Custom Styling, Custom Views, information about Big Calendar and Dates, and a guide on dealing with Timezones
- General documentation contribution guidelines have been included
- A GitHub workflow is included that will automatically build and deploy documentation to GitHub pages, after successful Release workflow (requires review and discussion with @jquense)

ToDo:
I need help in reviewing this documentation, and getting the testing straightened out. A number of dependencies were updated for this (**Read: requires `yarn install`**), and though all 'build' processes fine something in the Babel config is conflicting with Jest.

Any and all assistance is appreciated.

**Comment by jquense** [comment]
new docs look great! I'd be happy to help review the tooling changes, but don't have a time of time (as i'm sure you noticed) to look over docs thoroughly

**Comment by cutterbl** [comment]
@jquense Much appreciate the look at tooling. Also would need some assist with the auto doc deploy workflow, as that requires some info from you about the GitHub Pages setup for the repo.

**Comment by decimoseptimo** [comment]
I'm already helping at definitely typed. I'll take a look at this later, I'm still no aware of this update.

**Comment by cutterbl** [comment]
@jquense Have you had any time/luck looking at the tooling?
