### ISSUE TITLE
Event goes back to og date after drag and drop

### ISSUE THREAD

**Issue by kevinRoomies** [jquense/react-big-calendar#2117]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?
Event doesn't stay on the new date after a drag and drop, despite the date being correctly updated.

![GIF 03-02-2022 18-35-51](https://user-images.githubusercontent.com/65670017/152397600-af22df80-8163-4e69-bbd5-d8bd4168cc06.gif)

#### What's the expected behavior?
Event stays on the new date.

**Comment by cutterbl** [comment]
It is impossible to troubleshoot your issue without seeing your code. Create a CodeSandbox from [our base example](https://codesandbox.io/s/l9jwl0kj6m), or include the relevant code, to include your bits for props like `onEventDrop` and `onEventResize`. Also, review the [DnD Example](https://github.com/jquense/react-big-calendar/blob/master/examples/demos/dnd.js) for tips.
