### ISSUE TITLE
Issue with day/week views on Safari.

### ISSUE THREAD

**Issue by RikuRuokonen** [jquense/react-big-calendar#2128]
#### Do you want to request a _feature_ or report a _bug_?
Report a bug

#### What's the current behavior?
The calendar works fine in Chrome and Firefox. In Safari, day view and week view are empty and events won't render. However, events render on month-view. Week and day views also fail to render any background lines or numbers.

Code: 
```
import React from 'react'
import { Calendar, momentLocalizer } from 'react-big-calendar'
import moment from 'moment'
import 'react-big-calendar/lib/css/react-big-calendar.css'

const eventList = [
  {
    id: 0,
    title: 'Board meeting',
    start: new Date('2022-02-15T07:08:00'),
    end: new Date('2022-02-15T10:10:00')
  }
]
const MainCalendar = () => (
  <div
    style={{
      height: '75vh',
      minHeight: '580px',
      minWidth: '650px',
      background: '#fff',
      padding: '15px'
    }}
  >
    <Calendar
      localizer={momentLocalizer(moment)}
      events={eventList}
      startAccessor="start"
      endAccessor="end"
    />
  </div>
)

export default MainCalendar
```

React-big-calendar version: 0.38.5

Browser: Safari

Month view:

![Näyttökuva 2022-2-15 kello 13 47 22](https://user-images.githubusercontent.com/32368461/154059486-6cd63b39-e0d4-42ba-bc36-c6656e812299.png)

Week view:
![Näyttökuva 2022-2-15 kello 13 47 29](https://user-images.githubusercontent.com/32368461/154059497-ab427b10-2782-40b4-bd7b-3ed7ed721b98.png)

Day view:
![Näyttökuva 2022-2-15 kello 13 47 37](https://user-images.githubusercontent.com/32368461/154059505-344ec421-91c6-4a6f-aa39-93afe84ff855.png)

#### What's the expected behavior?
Day view and Week view to render correctly.

**Comment by cutterbl** [comment]
That's odd. I pulled the 0.38.5 tag, deleted the `node_modules`, ran `yarn install`, and ran storybook locally, and day and week views ran perfectly in Safari. Current version (0.38.9) as well. Do you have a reproducable codesandbox using this version? Have you tried updating to latest? Have you attempted a clean dependency install?
