### ISSUE TITLE
Drag and drop to Resource title row , event disappears and calendar looses focus.

### ISSUE THREAD

**Issue by securit** [jquense/react-big-calendar#2133]
#### What is the behaviour
If use the Drag and Drop add-on and drag an event to the Resource Title row in the week view, the event disappears and the calendar grid looses focus. See attached screen recording. If you click, anywhere on the calendar, the event returns to where it was.

https://user-images.githubusercontent.com/168565/155620474-a7e0bda0-8f77-4665-bcc3-437022e9c90a.mov

#### What's the expected behavior?
The expected behaviour would be that the event would return to its original slot without disappearing and return the focus to the gird.

**Comment by lukbak** [comment]
@cutterbl This issue still exists.
