### ISSUE TITLE
selected event custimization

### ISSUE THREAD

**Issue by nichtsam** [jquense/react-big-calendar#2142]
Hi,
I've been studying the docs, few things I couldn't figure out yet:

1. how to customize the background-color for selected event?
I imagine there should be a way to modify this.
I achieve this by using css !important property now, which is not ideal.

2. support for repeating events?
For example, let's say the is a giveaway event, happens everyday for a month, I can give it a range of a month.
What if there is a giveaway event happens every Monday for a month, Is there a way to achieve this?

3. self-defined isSelected property
Is there a way to define how an event is selected? 
I see there is a `selected` prop on the calendar, but the documentation is vague and `selected` doesn't seem to achieve what I want.

**Comment by cutterbl** [comment]
@nichtsam Our 'Issues' area is for submitting defects and feature requests. For implementation questions beyond the documentation you should probably look to Stackoverflow. We do have more extensive documentation coming (#2108). To give you some info:

1. You can pass an [eventPropGetter](http://jquense.github.io/react-big-calendar/examples/index.html#prop-eventPropGetter) function to your Calendar, allowing you to apply custom styles and classes to an event (like background color).
2. The Calendar shows what you give it. At my work, we generate repeated events server side, and include them in the `events`.
3. `selected` (better documented in #2108) should be a reference to an event in your `events`. The whole object. You have methods like [onSelectSlot](http://jquense.github.io/react-big-calendar/examples/index.html#prop-onSelectSlot), [onSelectEvent](http://jquense.github.io/react-big-calendar/examples/index.html#prop-onSelectEvent) and [onDoubleClickEvent](http://jquense.github.io/react-big-calendar/examples/index.html#prop-onDoubleClickEvent) as well.
