### ISSUE TITLE
Unable to find node on an unmounted component error with release 0.39.4

### ISSUE THREAD

**Issue by ferencbenko** [jquense/react-big-calendar#2151]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/wild-fire-c3dsz1?

### Bug description

The newest release is completely unusable for me, since I get the ,,Unable to find node on an unmounted component" error.
Reverting to 0.39.3 solves the issue.

### react-big-calendar version

0.39.4

### React version

16.14.0

### Platform/Target and Browser Versions

Microsoft Edge 99.0.1150.36

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a react-big-calendar issue and not an implementation issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nichtsam** [comment]
Here is an example for the error:
https://stackblitz.com/edit/nextjs-gtrsss

**Comment by ferencbenko** [comment]
I could, but rather reverted the calendar version to 0.39.3 for a quick fix, since I wasted too much time already figuring out why the calendar isn't working

**Comment by sangeeth96** [comment]
@nichtsam @ferencbenko can you folks try 0.39.6? Should fix this issue. @nichtsam in your example, pass an empty `events={[]}` prop as well.

**Comment by nichtsam** [comment]
> @nichtsam @ferencbenko can you folks try 0.39.7? Should fix this issue. @nichtsam in your example, pass an empty `events={[]}` prop as well.
> 
> Edit: I meant to say 0.39.7

Seems to get pass that error, but another error occurs:
`TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))`

Example below ( events added )
https://stackblitz.com/edit/nextjs-3bcjzv

**Comment by BrianMehrman** [comment]
> @nichtsam @ferencbenko can you folks try 0.39.7? Should fix this issue. @nichtsam in your example, pass an empty `events={[]}` prop as well.
> 
> Edit: I meant to say 0.39.7

First I would just like to thank you two for working on this bug. I ran into this on Friday morning and was so ecstatic to see someone else was having the same issue. 

I just updated to 0.39.7 and can confirm that the change @sangeeth96 made has fixed the error for me and my simple implementation of your calendar library.

Thank you again @sangeeth96 for getting this fix out for all of us who use your library. 

@nichtsam I was taking a look at your example. Is there an `event` attribute for the Calendar component. I found the calendar worked if you changed `event={{}}` to `events={[{}]}`
 
https://stackblitz.com/edit/nextjs-pfmgz1?file=pages/index.js

**Comment by nichtsam** [comment]
> > @nichtsam @ferencbenko can you folks try 0.39.7? Should fix this issue. @nichtsam in your example, pass an empty `events={[]}` prop as well.
> > Edit: I meant to say 0.39.7
> 
> First I would just like to thank you two for working on this bug. I ran into this on Friday morning and was so ecstatic to see someone else was having the same issue.
> 
> I just updated to 0.39.7 and can confirm that the change @sangeeth96 made has fixed the error for me and my simple implementation of your calendar library.
> 
> Thank you again @sangeeth96 for getting this fix out for all of us who use your library.
> 
> @nichtsam I was taking a look at your example. Is there an `event` attribute for the Calendar component. I found the calendar worked if you changed `event={{}}` to `events={[{}]}`
> 
> https://stackblitz.com/edit/nextjs-pfmgz1?file=pages/index.js

Oops, my bad, misread the comment!
didn't put much attention on it since it wasn't causing the original issue.

does `events` not accept `undefined` anymore?
I think it did accepted before, so does the typing suggest, but it seems to break with `undefined` provided.

**Comment by sangeeth96** [comment]
@nichtsam you're right, in 0.39.3, there was only a warning but when I switch to Week/Day/Agenda, things still break. Maybe there's better error reporting that can be done here but that's probably a different issue/PR.

cc @cutterbl

**Comment by ferencbenko** [comment]
It's working now with 0.39.7. Thank you @sangeeth96!
