### ISSUE TITLE
Unable to move and resize

### ISSUE THREAD

**Issue by erikmartinessanches** [jquense/react-big-calendar#2152]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://jquense.github.io/react-big-calendar/examples/index.html?path=/story/additional-examples-drag-and-drop--custom-steps-and-timeslots

### Bug description

When moving and resizing the item stays in place.

### Expected Behavior

Move and resize events.

### react-big-calendar version

the one in the docs

### React version

the one in the docs

### Platform/Target and Browser Versions

Chrome version 99.0.4844.74

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a react-big-calendar issue and not an implementation issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by cutterbl** [comment]
@erikmartinessanches The examples you were looking at have no code to handle what to do when you drop an item somewhere else. I think you probably want the [Drag and Drop](https://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/addons-drag-and-drop-introduction--page) core documentation for better understanding.
