### ISSUE TITLE
Apple M1 – Issue w/ @babel/runtime/helpers/interopRequireDefault.js error w/ NextJS, unable to use component

### ISSUE THREAD

**Issue by gavgrego** [jquense/react-big-calendar#2153]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://github.com/gavgrego/dead-cal

### Bug description

When trying to use component on a page with NextJS get an error related to `/home/runner/work/react-big-calendar/react-big-calendar/node_modules/@babel/runtime/helpers/interopRequireDefault.js`

`error - Error: Cannot find module '/home/runner/work/react-big-calendar/react-big-calendar/node_modules/@babel/runtime/helpers/interopRequireDefault.js'
Require stack:
- /Users/gavin/Sites/cal-dead/cal-dead/node_modules/react-big-calendar/lib/index.js
- /Users/gavin/Sites/cal-dead/cal-dead/.next/server/pages/index.js
- /Users/gavin/Sites/cal-dead/cal-dead/node_modules/next/dist/server/require.js
- /Users/gavin/Sites/cal-dead/cal-dead/node_modules/next/dist/server/load-components.js
- /Users/gavin/Sites/cal-dead/cal-dead/node_modules/next/dist/build/utils.js
- /Users/gavin/Sites/cal-dead/cal-dead/node_modules/next/dist/build/output/store.js
- /Users/gavin/Sites/cal-dead/cal-dead/node_modules/next/dist/build/output/index.js
- /Users/gavin/Sites/cal-dead/cal-dead/node_modules/next/dist/cli/next-dev.js
- /Users/gavin/Sites/cal-dead/cal-dead/node_modules/next/dist/bin/next`

### react-big-calendar version

0.36.4

### React version

0.36.4

### Platform/Target and Browser Versions

macOS M1

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a react-big-calendar issue and not an implementation issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by wayimp** [comment]
I encountered this exact same issue with my Next.js project.

**Comment by darraghmckay** [comment]
Reverting to [v0.39.3](https://github.com/jquense/react-big-calendar/releases/tag/v0.39.3) solved the issue for me

**Comment by cutterbl** [comment]
So, you do not see a `@babel/runtime` folder in your `node_modules`? It is a dependency of Big Calendar.

**Comment by sangeeth96** [comment]
@cutterbl I have encountered this as well and I believe `"absoluteRuntime": false` needs to be passed for `babel-preset-react-app`. Have documented the changes in #2155 — let me know if this does it.

**Comment by gavgrego** [comment]
@sangeeth69 @cutterbl looks like this just introduced a new bug, still not working for me.

`Error: require() of ES Module /Users/gavin/Sites/cal-dead/cal-dead/node_modules/@babel/runtime/helpers/esm/objectSpread2.js from /Users/gavin/Sites/cal-dead/cal-dead/node_modules/react-big-calendar/lib/Calendar.js not supported.
Instead change the require of objectSpread2.js in /Users/gavin/Sites/cal-dead/cal-dead/node_modules/react-big-calendar/lib/Calendar.js to a dynamic import() which is available in all CommonJS modules.`

**Comment by sangeeth96** [comment]
Hey @gavgrego and others. Sorry, npm was giving issues yesterday so I couldn't test a possible fix for the issues you're facing. But could you check https://github.com/jquense/react-big-calendar/issues/2156#issuecomment-1076510454 and maybe any further discussions on this can go in #2156
