### ISSUE TITLE
Stop Overlapping of Events in a single time slot

### ISSUE THREAD

**Issue by Gaurav7004** [jquense/react-big-calendar#2154]
### Clear and concise description of the problem

I am facing difficulty in stopping the overlapping of the multiple events in a single time slot. I want to show only one allowed event in a single time slot.

### Suggested solution

Show all the hour slots as filled or empty in week view.

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples/index.html).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [X] I'm willing to open a PR

**Comment by cutterbl** [comment]
Control of what can be entered into a slot is completely up to the developer. I suggest some form of logic in your [onSelectSlot)(http://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/props--on-select-slot) method
