### ISSUE TITLE
How can i custom DateCell in MonthView

### ISSUE THREAD

**Issue by ttnghia195** [jquense/react-big-calendar#2163]
Hello guys!
In the Month View, I just want to show the total number of events for the day. So how can I customize it for this?
Thank you!
![Screen Shot 2022-04-01 at 15 39 10](https://user-images.githubusercontent.com/19924565/161227793-b664671c-9762-4f51-b536-073507d5c929.png)

**Comment by cutterbl** [comment]
The current Month 'View' wouldn't really support this layout. You might be able to do it with a custom Month View, where you handle all of your own rendering logic.

**Comment by ttnghia195** [comment]
> The current Month 'View' wouldn't really support this layout. You might be able to do it with a custom Month View, where you handle all of your own rendering logic.

Thank you, I really did follow that way 😅
