### ISSUE TITLE
Drag and drop from popup doesn't work any more

### ISSUE THREAD

**Issue by vedpir-havatec** [jquense/react-big-calendar#2164]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://jquense.github.io/react-big-calendar/examples/index.html?path=/story/addons-drag-and-drop--example-1

### Bug description

Drag and drop from popup doesn't work anymore if I try in month view. The following error is given. 

react-dom.production.min.js:101 Uncaught TypeError: _this.props.handleDragStart is not a function
    at onDragStart (Popup.js:92:43)
    at Object.Rb (react-dom.production.min.js:52:317)
    at Xb (react-dom.production.min.js:52:471)
    at Yb (react-dom.production.min.js:53:35)
    at Ze (react-dom.production.min.js:100:68)
    at se (react-dom.production.min.js:101:380)
    at react-dom.production.min.js:113:65
    at Jb (react-dom.production.min.js:292:189)
    at Nb (react-dom.production.min.js:50:57)
    at jd (react-dom.production.min.js:105:469)

### Expected Behavior

When i drag a event from month pop up view and drop in a other month cell I expect that de event will move to this cell.

### Actual Behavior

The event wont move to the new month cell.

### react-big-calendar version

0.40.0

### React version

17

### Platform/Target and Browser Versions

Chrome

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a react-big-calendar issue and not an implementation issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by vedpir-havatec** [comment]
Please help wanted?

**Comment by cutterbl** [comment]
@vedpir-havatec Can you fork this [Codesandbox](https://codesandbox.io/s/react-big-calendar-example-v9wdyd), and create an example using a version of Big Calendar that did have this functionality?

**Comment by Fir3st** [comment]
@vedpir-havatec I had the same issue. I found there is a separated handler `handleDragStart` that must be set and ends up with `onDropFromOutside`.

**Comment by vedpir-havatec** [comment]
@Fir3st thanks that was exactly what i needed to do
