### ISSUE TITLE
Problem with exceeding the event slots in the calendar

### ISSUE THREAD

**Issue by sbin0819** [jquense/react-big-calendar#2166]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/react-big-cal-datecellwrapper-so-question-forked-kdrpv?file=/src/index.js

### Bug description

Exceeding the event slots in the calendar (month type) will cause problems. Under normal circumstances, this is fine.
However, if the event slot is exceeded, the number of showmores is displayed correctly. For example, if an event slot that is exceeded is longer than that date, information about that date is lost from the calendar.
Do you hanppend to know how to fix it?

### Expected Behavior

Excess date information seems to have to be printed on the calendar. 
Perhaps it should be shown in showmore, not in a slot in the calendar.

### react-big-calendar version

0.38.9

### React version

17.0.2

### Platform/Target and Browser Versions

macOS/Windos, chrome

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a react-big-calendar issue and not an implementation issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by sbin0819** [comment]
<img width="394" alt="Screen Shot 2022-04-08 at 10 26 51 AM" src="https://user-images.githubusercontent.com/20038519/162345233-34da9ae6-ea07-4cce-90bf-545bdb526dad.png">

t5 is now displaying in calendar
<img width="488" alt="Screen Shot 2022-04-08 at 10 27 12 AM" src="https://user-images.githubusercontent.com/20038519/162345266-898b55a2-d5cd-4874-8757-1ec18e28be98.png">

**Comment by cutterbl** [comment]
I haven't picked your example apart, but I imagine what you're seeing may have to do with your misuse of dates. Looking at your `events`, you have both strings and moment objects for `start` and `end`, when the [documentation specifically states](http://jquense.github.io/react-big-calendar/examples/index.html?path=/story/guides-understanding-dates--page) that Big Calendar requires true JS Date objects.

**Comment by sbin0819** [comment]
> I haven't picked your example apart, but I imagine what you're seeing may have to do with your misuse of dates. Looking at your `events`, you have both strings and moment objects for `start` and `end`, when the [documentation specifically states](http://jquense.github.io/react-big-calendar/examples/index.html?path=/story/guides-understanding-dates--page) that Big Calendar requires true JS Date objects.

Thank you for your reply.

Could you check reproduction link again?
I changed `start` and `end` type, but it's still not working.

I think it's internal algorithm problem.

**Comment by cutterbl** [comment]
This has to do with the way events are sorted. T5 is the last event to start on the 13th, so it drops to the 'more' for that date. Looking at the event in the TimeGrid view, it does span through the 15th, but since there isn't enough space in your Month view to display all of the dates, it's not displayed.

**Comment by sbin0819** [comment]
> This has to do with the way events are sorted. T5 is the last event to start on the 13th, so it drops to the 'more' for that date. Looking at the event in the TimeGrid view, it does span through the 15th, but since there isn't enough space in your Month view to display all of the dates, it's not displayed.

So, you mean not updating that part?

**Comment by cutterbl** [comment]
since the height of your calendar is only tall enough to display three events on a day, t5 is not displayed, and is part of the 'more' for the 13th. That's why you don't see it.

**Comment by sbin0819** [comment]
> since the height of your calendar is only tall enough to display three events on a day, t5 is not displayed, and is part of the 'more' for the 13th. That's why you don't see it.

Thanks, I still like this library.
I know what you mean exactly, but I just want to see them at any height.
I thought `more` is going to be the answer.
