### ISSUE TITLE
percentage(math.div(1, 7))

### ISSUE THREAD

**Issue by andrconstruction** [jquense/react-big-calendar#2171]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://

### Bug description

For what are you use this? It will be 0.14 i think/ If not use dynamic variables.
At this moment it is incompatible with older builders like gulp-sass. Is it necessary? 

### Expected Behavior

Build without errors

### react-big-calendar version

0.39.3

### React version

17.0.2

### Platform/Target and Browser Versions

windows

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a react-big-calendar issue and not an implementation issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by cutterbl** [comment]
@andrconstruction I'm having difficulty understanding what your issue is, but let me try here.

The gulp-sass package deprecated the use of `node-sass` as it's compiler, requiring the developer to install a SASS compiler, with it's 5.0.0 release. If you're using the current `sass` package, then this is fine, and will work with our current code, as we also deprecated the use of `node-sass` and switched to `sass` (`math.div()` is a relatively new form required by the current SASS compiler, and the updated `bootstrap-sass` dependency uses this form).

Did this answer your question?

**Comment by andrconstruction** [comment]
> @andrconstruction I'm having difficulty understanding what your issue is, but let me try here.
> 
> The gulp-sass package deprecated the use of `node-sass` as it's compiler, requiring the developer to install a SASS compiler, with it's 5.0.0 release. If you're using the current `sass` package, then this is fine, and will work with our current code, as we also deprecated the use of `node-sass` and switched to `sass` (`math.div()` is a relatively new form required by the current SASS compiler, and the updated `bootstrap-sass` dependency uses this form).
> 
> Did this answer your question?

Yep, thanks. But anyway I missunserstand for what use function if variables is static

**Comment by cutterbl** [comment]
I guess you need to clearly explain what the use case is, so I can understand.

**Comment by andrconstruction** [comment]
**percentage(math.div(1, 7)) === percentage(0.14)** 
and import  use:math  within a variables.sass file will be not neccessary

**Comment by cutterbl** [comment]
`sass:math` is actually a replacement (from SASS) for the older `1 / 7` syntax, and *is* used in the bootstrap-sass as well. The move to this was to handle the deprecation of node-sass. I see what you mean though, about it not being necessary (we _could_ do that math ourselves). I'll see if I can find others to discuss it some.

**Comment by bartvanandel** [comment]
> replace percentage(math.div(1, 7)) with percentage(0.14)

Although the idea is sound, we will need more precision or we will run into gaps of several pixels pretty quickly. 14 * 7 = 98, so you'll be looking at missing 2% with 7 columns. Using `0.14286` reduces the error to 0.002% from 2%, i.e. a 1000-fold improvement.
