### ISSUE TITLE
Time breaks

### ISSUE THREAD

**Issue by rihanddevelopment** [jquense/react-big-calendar#2177]
### Clear and concise description of the problem

As a developer using big calendar I want to create time breaks. For example I wanna pass to blockTimeSlots props like startTime, endTime, resourceId and date. It will create a blocked times and user cannot create any event when click on these slots.

### Suggested solution

Create new propType like blockTimeSlots or timeBreakSlots and pass these properties -- startTime, endTime, resourceId and date and It would be nice customize these slots style.

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples/index.html).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by cutterbl** [comment]
You're right, there is no 'automatic' way that Big Calendar will block this selection today. But, the developer *can* manually handle that in the various selection methods itself, if it can determine that the selection made matches some criteria. You could use `backgroundEvents` to display your 'blocked' times, and compare selections (in your select methods) against the `backgroundEvents` ranges, and manually block the rest of process.
