### ISSUE TITLE
Problem with module exports with npm run build

### ISSUE THREAD

**Issue by pmichelfeit** [jquense/react-big-calendar#2178]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/

### Bug description

'momentLocalizer' is not exported by src/react-big-calendar/react-big-calendar.js, imported by src/xyz.jsx

1: import React, { useEffect, useReducer, useState } from "react";
2:
3: import { Calendar, momentLocalizer } from './react-big-calendar/react-big-calendar';
   ^
4: import withDragAndDrop from "./react-big-calendar/lib/addons/dragAndDrop";

### Expected Behavior

Modules are exported

### Actual Behavior

Modules are not exported

### react-big-calendar version

0.40.1

### React version

16.13.2

### Platform/Target and Browser Versions

Windows, Linux

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a react-big-calendar issue and not an implementation issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by cutterbl** [comment]
The base [Codesandbox](https://codesandbox.io/s/react-big-calendar-example-v9wdyd) has been updated to use 0.40.1, and it's working just fine. You aren't importing it properly.

```js
import {Calendar, momentLocalizer} from 'react-big-calendar';
```

**Comment by pmichelfeit** [comment]
I built it locally on my machine with npm run build, and it is not working as expected.
Have you an Idea whats the cause for that ?

**Comment by bartvanandel** [comment]
Without more details this is impossible to answer. What does your current code look like? What have you tried to resolve the problem you're facing? etc.

**Comment by philipp-michelfeit** [comment]
See #2179 for more info !

**Comment by cutterbl** [comment]
@philipp-michelfeit You've built it locally, you said, which implies no build errors. Can you run the documentation (`yarn storybook`)? Why are you building locally? You don't appear to be 'link'ing the package in...

**Comment by pmichelfeit** [comment]
No, I get some errors when trying to execute 'yarn storybook'.

**Comment by pmichelfeit** [comment]
How do you build react big calendar from source ?
What commands do you use ?

**Comment by cutterbl** [comment]
@pmichelfeit 

- Clone Repo
- Run `yarn install` (We use yarn, not npm. This is important.)
- Run `yarn build` (builds package locally)
- Run `yarn storybook` (runs the documentation locally)
- If you have errors in process, post errors to a note on this issue
- Suggest Node v14 or higher

**Comment by philipp-michelfeit** [comment]
yarn install and yarn build run all fine !

Except yarn storybook. This is the output on a Linux bash:

philipp@:~/GIT/react-big-calendar> yarn storybook
info @storybook/react v6.4.19
info 
info => Loading presets
ERR! TypeError: details.family.toLowerCase is not a function
ERR!     at /home/philipp/GIT/react-big-calendar/node_modules/ip/lib/ip.js:385:39
ERR!     at Array.filter (<anonymous>)
ERR!     at /home/philipp/GIT/react-big-calendar/node_modules/ip/lib/ip.js:384:37
ERR!     at Array.map (<anonymous>)
ERR!     at ip.address (/home/philipp/GIT/react-big-calendar/node_modules/ip/lib/ip.js:379:37)
ERR!     at getServerAddresses (/home/philipp/GIT/react-big-calendar/node_modules/@storybook/core-server/dist/cjs/utils/server-address.js:20:55)
ERR!     at storybookDevServer (/home/philipp/GIT/react-big-calendar/node_modules/@storybook/core-server/dist/cjs/dev-server.js:91:67)
ERR!     at async buildDevStandalone (/home/philipp/GIT/react-big-calendar/node_modules/@storybook/core-server/dist/cjs/build-dev.js:115:31)
ERR!     at async buildDev (/home/philipp/GIT/react-big-calendar/node_modules/@storybook/core-server/dist/cjs/build-dev.js:161:5)
ERR!  TypeError: details.family.toLowerCase is not a function
ERR!     at /home/philipp/GIT/react-big-calendar/node_modules/ip/lib/ip.js:385:39
ERR!     at Array.filter (<anonymous>)
ERR!     at /home/philipp/GIT/react-big-calendar/node_modules/ip/lib/ip.js:384:37
ERR!     at Array.map (<anonymous>)
ERR!     at ip.address (/home/philipp/GIT/react-big-calendar/node_modules/ip/lib/ip.js:379:37)
ERR!     at getServerAddresses (/home/philipp/GIT/react-big-calendar/node_modules/@storybook/core-server/dist/cjs/utils/server-address.js:20:55)
ERR!     at storybookDevServer (/home/philipp/GIT/react-big-calendar/node_modules/@storybook/core-server/dist/cjs/dev-server.js:91:67)
ERR!     at async buildDevStandalone (/home/philipp/GIT/react-big-calendar/node_modules/@storybook/core-server/dist/cjs/build-dev.js:115:31)
ERR!     at async buildDev (/home/philipp/GIT/react-big-calendar/node_modules/@storybook/core-server/dist/cjs/build-dev.js:161:5)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

**Comment by philipp-michelfeit** [comment]
You can work around the above error by replacing details.family.toLowerCase() by details.family.toString().toLowerCase() in the file ./node_modules/ip/lib/ip.js. This is a bug of the ip module.
After the fix yarn storybook runs fine.

philipp@:~/GIT/react-big-calendar> grep -r 'details.family.toLowerCase' ./
./node_modules/ip/lib/ip.js:      var itemFamily = details.family.toLowerCase();
./node_modules/ip/lib/ip.js:      details.family = details.family.toLowerCase();

**Comment by philipp-michelfeit** [comment]
This is a bug of the ip module ( v1.1.5 and prior ).
Following are the modules listed which are affected by this bug of the ip module:

philipp@:~/GIT/react-big-calendar> npm ls ip
react-big-calendar@0.40.1 /home/philipp/GIT/react-big-calendar
├─┬ @storybook/react@6.4.19
│ └─┬ @storybook/core@6.4.19
│   └─┬ @storybook/core-server@6.4.19
│     └── ip@1.1.5
├─┬ semantic-release@19.0.2
│ └─┬ @semantic-release/npm@9.0.1
│   └─┬ npm@8.5.4
│     └─┬ make-fetch-happen@10.1.5
│       └─┬ socks-proxy-agent@6.1.1
│         └─┬ socks@2.6.2
│           └── ip@1.1.5 deduped
└─┬ webpack-dev-server@4.7.4
  └─┬ bonjour@3.5.0
    └─┬ multicast-dns@6.2.3
      └─┬ dns-packet@1.3.4
        └── ip@1.1.5 deduped
