### ISSUE TITLE
Unable to use forked react big calendar in my project

### ISSUE THREAD

**Issue by philipp-michelfeit** [jquense/react-big-calendar#2179]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io

### Bug description

Please provide the steps to build react big calendar from source and to use it in another project !

Reason for this is that it does not work to use custom built big calendar in my project for the following reasons:

1. Big calendar needs esm javascript module to work properly
2. But dragAndDrop functionality doesnt work with esm javascript module

### Expected Behavior

Building from source and using in another project is working

### Actual Behavior

Not working to use it in another project

### react-big-calendar version

0.40.1

### React version

18.1.0

### Platform/Target and Browser Versions

Windows, Linux

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a react-big-calendar issue and not an implementation issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by jquense** [comment]
Forking and building from source is not really a supported flow. You are more than welcome to do it of course but it's up to you to figure it out

**Comment by philipp-michelfeit** [comment]
How do you build react big calendar from source and what I have to include in my project so that it works ?
