### ISSUE TITLE
Event in Event to have a container

### ISSUE THREAD

**Issue by jechazelle** [jquense/react-big-calendar#2183]
### Clear and concise description of the problem

Hi,

I would like to know if it possible to embed an event in event, like this : 

![render](https://user-images.githubusercontent.com/6713790/169764295-0efb5efa-72d7-413f-8076-48fd6aa968c1.png)

Currently I use this code : 

> events : 

    const items = [
        {
            id: 0,
            title: 'event',
            start: new Date('2022-05-18T13:05Z'),
            end: new Date('2022-05-18T16:05Z'),
            items: [
                {
                    id: 1,
                    title: 'sub-event-1',
                    items: [
                        {
                            id: '1-1',
                            title: 'sub-sub-event-1-1',
                        },
                        {
                            id: '1-2',
                            title: 'sub-sub-event-1-2',
                        },
                    ],
                },
                {
                    id: 2,
                    title: 'sub-event-2',
                    items: [
                        {
                            id: '2-1',
                            title: 'sub-sub-event-2-1',
                        },
                        {
                            id: '2-2',
                            title: 'sub-sub-event-2-2',
                        },
                    ],
                },
            ],
        },
    ];

 > Calendar.js : 

    <DnDCalendar
        events={items}
        components={{
            event: CustomEvent,
        }}
    />

> CustomEvent.js : 

    export default function CustomEvent(props: any) {
        return (
            <div>
                <span>{props.title}</span>

                <div>
                    {props.event.items.map((item) => {
                        return (
                            <div className="bg-red-300 m-1 p-1">
                                <span>{item.title}</span>

                                {item.items.map((item) => {
                                    return <div className="bg-slate-300 m-1">{item.title}</div>;
                                })}
                            </div>
                        );
                    })}
                </div>
            </div>
        );
    }

### Suggested solution

Include CustomEvent in CustomEvent.

### Additional context

I would like to have a container surround the events, but currently I don't have a real placement with date.

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples/index.html).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by cutterbl** [comment]
No, that isn't something that's currently possible, and extremely edge case scenario. You have two possible options to you here. One, you could create a [custom event](http://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/props--components) layout, consuming your event object and handling it's layout yourself (similar to what you suggest). Or, you could use [backgroundEvents](http://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/props--back-ground-events) to create your 'containers' (not true containers, but visually so) for your [events](http://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/props--events).

**Comment by jechazelle** [comment]
Thank you @cutterbl for your answer !
