### ISSUE TITLE
Issue with popup location

### ISSUE THREAD

**Issue by wolf1347** [jquense/react-big-calendar#2186]
React version: 17.0.1 
React-Big-Calendar version: 0.41.1
Current Behavior (recreated in the code sandbox):
https://codesandbox.io/s/big-calendar-overflow-issue-iw6oct?file=/src/styles.css

There is an issue I am having with the +more popup in the calendar where it is rendering in an incorrect location with overflow hidden. The version of React being used has been updated recently and since then the +more has been acting differently. Previously the popup for the +more would use the space above the date but now (as shown in the codesandbox) the popup renders below the date and gets cut off. Any ideas on what would have caused this change in behavior/potential fixes?

Thank you so much in advance!

**Comment by muhib-dev** [comment]
dnd error on popup event
