### ISSUE TITLE
npm package not updated to react 18

### ISSUE THREAD

**Issue by pioteres** [jquense/react-big-calendar#2189]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://github.com/jquense/react-big-calendar

### Bug description

please update npm package to using with react 18.

### react-big-calendar version

0.40.1

### React version

18.0.1

### Platform/Target and Browser Versions

Chrome

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a react-big-calendar issue and not an implementation issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by abalexandre** [comment]
Issue is present for React 17 too.

**Comment by MarcHbb** [comment]
+1

**Comment by kenianbei** [comment]
+1

**Comment by cutterbl** [comment]
@pioteres @cmeddins-e2g Check this with latest build (0.40.2) and see if that resolved the issue.

**Comment by cmeddins-e2g** [comment]
> @pioteres @cmeddins-e2g Check this with latest build (0.40.2) and see if that resolved the issue.

@cutterbl Yes, this seems to resolve the react 18 dependency issue on my end. Thanks!
