### ISSUE TITLE
findDOMNode is deprecated in StrictMode & is breaking functionality

### ISSUE THREAD

**Issue by Inrixia** [jquense/react-big-calendar#2193]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

Its obvious

### Bug description

I have just enabled the popup prop re this example: https://jquense.github.io/react-big-calendar/examples/index.html?path=/story/examples--example-6

After doing so when there are too many events to be displayed the popup text renders properly 
![image](https://user-images.githubusercontent.com/6373693/174431651-2c9eaf0b-e446-4f52-9ec5-2837705948e6.png)
but clicking on it does nothing and I have the following error in console:
![image](https://user-images.githubusercontent.com/6373693/174431682-9d6b809c-55b9-4c26-9dff-af4108aac604.png)

### Expected Behavior

Clicking the prompt would show events.

### Actual Behavior

Clicking the prompt does nothing and there is a issue with `findDOMNode` in console being deprecated.

Presumably all that is needed to fix this is to replace the usage of `findDOMNode` with `useRef`.

### react-big-calendar version

0.40.2

### React version

18.0.14

### Platform/Target and Browser Versions

Create React Defaults

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a react-big-calendar issue and not an implementation issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR (*unchecked as I can't get the library to build happily in my dev env*)

**Comment by cutterbl** [comment]
I need testers to checkout PR #2195 to see if it resolves these issues without breaking functionality.

**Comment by Inrixia** [comment]
I've had a quick look at the pr. Looks good, I would test it myself but I am unable to build this package from source on my system.
