### ISSUE TITLE
Remove slots between min and max

### ISSUE THREAD

**Issue by lamamasters** [jquense/react-big-calendar#2196]
Is it possible to completely REMOVE or HIDE the slots between `min` and `max`?

<img width="1056" alt="Screenshot 2022-06-23 at 12 07 48" src="https://user-images.githubusercontent.com/17729580/175275191-26230004-a182-4346-911f-ec38c972f89b.png">

### Suggested solution

Create the possibility to remove slots between min and max.

**Comment by cutterbl** [comment]
Actually, the only time slots shown, in the TimeGrid, are those between `min` and `max`, hiding anything earlier than `min` or later than `max`. To reverse this would be kind of counter intuitive.

**Comment by lamamasters** [comment]
@cutterbl You are right, but I would like to remove "disabled slots" from the calendar and these can create many gaps between min and max. Is it possible?

I know that this is not possible only with CSS.
If I will put `display: none` on the `.rbc-timeslot-group` I can still select a disabled time.
