### ISSUE TITLE
Uncaught TypeError: Cannot use 'in' operator to search for 'window' in undefined

### ISSUE THREAD

**Issue by LiniovasDovydas** [jquense/react-big-calendar#2201]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://jquense.github.io/react-big-calendar/examples/index.html?path=/story/addons-drag-and-drop--example-2

### Bug description

TimeGrid fails to measure gutter width due to gutter being undefined. 

### Expected Behavior

Gutter is measured

### Actual Behavior

Fails to measure the gutter due to invalid ref to the gutter dom element

### react-big-calendar version

0.40.4

### React version

^16.14.0 || ^17 || ^18

### Platform/Target and Browser Versions

Chrome, Edge, Firefox

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a react-big-calendar issue and not an implementation issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by GiftedMediaBJ** [comment]
I am running into the same issues. 
I found that this issue starts at 0.40.3

**Comment by cutterbl** [comment]
Resolved in 0.40.7
