### ISSUE TITLE
Drag and Drop and resize events on month view are not functional

### ISSUE THREAD

**Issue by darkcattz** [jquense/react-big-calendar#2209]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://jquense.github.io/react-big-calendar/examples/index.html?path=/story/additional-examples-drag-and-drop--custom-steps-and-timeslots

### Bug description

On v0.40.7 Drag and Drop and resize events on month view are not functional.

No problems on v0.38.9 and inferior.
No problems on week views.

onEventDrop={this.moveResizeEvent}. -> no result and no error on month view
onEventResize={this.moveResizeEvent} -> no result and no error on month view

### Expected Behavior

onEventDrop and onEventResize must be functional on month view

### Actual Behavior

onEventDrop and onEventResize do nothing currently

### react-big-calendar version

0.40.7

### React version

17.0.2

### Platform/Target and Browser Versions

Chrome 103.0.5060.114

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a react-big-calendar issue and not an implementation issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by cutterbl** [comment]
Resolved in 0.40.8
