### ISSUE TITLE
Changing Date Range on docs breaks Events

### ISSUE THREAD

**Issue by bvergara87** [jquense/react-big-calendar#2222]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

docs

### Bug description

When changing the date range on the docs, events have undefined behavior. Events lose their start or end time and, as a result, lose their height when rendered on the calendar.

### react-big-calendar version

docs

### React version

docs

### Platform/Target and Browser Versions

docs

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a react-big-calendar issue and not an implementation issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by cutterbl** [comment]
@bvergara87 Can you give me the exact steps you are using to recreate this behavior?

**Comment by valeriomycit** [comment]
I see the same problem in week and day views even with 2 simple hardcoded events, all my code is below (using fns localizer)

is enough to go back and forth with the week selector.
When I go from previous week to current, tomorrow event goes to the bottom
from next week back to current, it goes to the top
Same happens with With events in other weeks 
today event is always fine
(removing min and max do not change behavior)

`    const locales = {
        'en-US': enUS,
      }
      
    const localizer = dateFnsLocalizer({
        format,
        parse,
        startOfWeek,
        getDay,
        locales,
    })


    const hardEvents = [
        {
         start: new Date("2022-07-12T10:00:00.000Z"),
         end: new Date("2022-07-12T14:00:00.000Z"),
         title: "Event today"
        },
        {
         start: new Date("2022-07-13T09:00:00.000Z"),
         end: new Date("2022-07-13T13:00:00.000Z"),
         title: "Event tomorrow"
        }
        
    ];
    return (
        <Calendar
            localizer={localizer}
            events={hardEvents}
            style={{ height: 500 }}
            min={new Date(2020, 1, 0, 8, 0, 0)}
            max={new Date(2020, 1, 0, 18, 0, 0)}
        />
    )`

**Comment by darkcattz** [comment]
Hello same problem here, 
See example video and png on attachment.

It seems to be a problem updating the state on big-calendar.
Events lose their start time which changes the display for 1/4 second and then resets normally.

It's a recent problem. I didn't have this problem in v38.

[bigcalendar-stateUpdateBug](https://www.netside-planning.com/imgs/github/react-bigcalendar2.png)
[bigcalendar-stateUpdateBug-video](https://www.netside-planning.com/imgs/github/react-bigcalendar3.mov)

**Comment by darkcattz** [comment]
> The bug seems to be on the documentation too : Just go to : https://jquense.github.io/react-big-calendar/examples/index.html?path=/story/examples--example-10 Click next (all events are at the bottom), click back (all events are at the top).

Yes, same bug in the demo.

**Comment by davellx** [comment]
This fix introduced 2 new bugs (that were not present before):
- clicking on the anchor of  an DnD event scrolls to top, maiking the dragging difficult
- changing range doesn't change the DnD date, creating events for weeks other than the current is impossible with mouse selection.

I'll open issues with that.

**Comment by darkcattz** [comment]
blocking Bug in last version : 
`DayColumn.getSnapshotBeforeUpdate(): A snapshot value (or null) must be returned. You have returned undefined.
    at DayColumn (http://localhost:8083/static/js/2.chunk.js:16616:34)`

**Comment by darkcattz** [comment]
The update of the state is no longer done at all after the first load
