### ISSUE TITLE
Drag'n'Drop anchor clicks jumps to top

### ISSUE THREAD

**Issue by davellx** [jquense/react-big-calendar#2225]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/addons-drag-and-drop--example-1

### Bug description

(visible on the current documentation/demo)
When I try to drag an event to resize it, the calendar scroll jumps to top immediately on "mousedown" making drag very difficult.

### Expected Behavior

The calendar scroll should not move on mousedown, only on drag if needed.

### Actual Behavior

Jump !

### react-big-calendar version

1.3.2

### React version

17.0.2

### Platform/Target and Browser Versions

Chrome, Firefox

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a react-big-calendar issue and not an implementation issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by cutterbl** [comment]
This is resolved in v1.4.0
