### ISSUE TITLE
Create event with mouse selection after navigate doesn't reflect correct date

### ISSUE THREAD

**Issue by davellx** [jquense/react-big-calendar#2226]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/examples--example-2

### Bug description

(visible on current documentation/demo)

- go on the reproduction link, in week view
- click on next
- drag in the calendar to create a new event, give it a name -- > it disappears
- click on back
- it is here, same hour but one week earlier

### Expected Behavior

The event should be created at the day selected by the mouse selection.

### Actual Behavior

The event seems to be created at the original range of the calendar.

### react-big-calendar version

1.3.2

### React version

17.0.2

### Platform/Target and Browser Versions

Chrome, Firefox

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a react-big-calendar issue and not an implementation issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by cutterbl** [comment]
This has been resolved in v1.4.0
