### ISSUE TITLE
[Request for Feedback] Calendar does not scroll if we drag event at top or bottom edge of container

### ISSUE THREAD

**Issue by AmitRDesai** [jquense/react-big-calendar#2231]
### Clear and concise description of the problem

When the user wants to move the event to a time that is currently outside of the view port of the calendar then the user needs to drag and drop the event multiple times to move it to the desired time.

### Suggested solution

When an event is being dragged at the top or bottom edge of the calendar then it will auto-scroll the calendar by adjusting the scrollTop property of the calendar container 

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples/index.html).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [x] I'm willing to open a PR

**Comment by cutterbl** [comment]
@AmitRDesai has been kind enough to submit a PR for a solution to this long standing issue. We're looking for feedback on two possible scenarios.

1. A prop could be added that would allow the default behavior (no autoscroll), or
2. Just autoscroll on DnD as the new default behavior

Looking for other's opinions on which way to go

**Comment by dhruvgoel92** [comment]
Not sure if there is a use-case for disabling the auto-scroll when dragging.
