### ISSUE TITLE
Calendar scroll back to `scrollToTime` when selecting an Event

### ISSUE THREAD

**Issue by Ne0xygene** [jquense/react-big-calendar#2233]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/props--scroll-to-time

### Bug description

Steps to reproduce :
1. Go to [https://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/props--scroll-to-time](url)
2. Scroll up.
3. Click on the event at 8:00AM
4. The position is reset to 12:00PM

### Expected Behavior

It should not scroll back to default position when `scrollToTime` is defined and a user select an event.

### Actual Behavior

When user scroll on the calendar with `scrollToTime` defined. It goes back to its default position.

(It seems to be a bug caused by changes in 1.2.0 as 1.1.0 does not seem to have the bug).

### react-big-calendar version

1.4.0

### React version

17.0.2

### Platform/Target and Browser Versions

macOs Google Chrome Version 100.0.4896.127

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a react-big-calendar issue and not an implementation issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by lukbak** [comment]
@cutterbl Unfortunately, we have the same issue in DnD mode. 

**Steps to reproduce:**
1. Open https://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/addons-drag-and-drop--example-1
2. Select Day View
3. Scroll to 8:00 PM
4. Select slot

**Comment by iainad** [comment]
It looks like this problem still exists in 1.5.0 in DnD mode - see: #2260
