### ISSUE TITLE
Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code.

### ISSUE THREAD

**Issue by marakos** [jquense/react-big-calendar#2241]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

undefined

### Bug description

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://reactjs.org/link/derived-state

Please update the following components: DayColumn

This error appears in console when using Next.js 12 with  reactStrictMode: true.

### react-big-calendar version

1.5.0

### React version

17.0.2

### Platform/Target and Browser Versions

Chrome, Safari

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a react-big-calendar issue and not an implementation issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by bostonmacosx** [comment]
@marakos Any thoughts on this

**Comment by cutterbl** [comment]
@bostonmacosx The [Documentation](http://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/guides-understanding-dates--page) explains exactly how Big Calendar deals with Dates

**Comment by bostonmacosx** [comment]
@cutterbl yes however....if the month view loads fine then the weeks and or day view crash that is a bug not a data issue. There should be consistency in the way that the app handles dates....not one way for the inital load then another way just because you went from month to day view.

**Comment by cutterbl** [comment]
No, it is a data issue, dealing with internal data conversions once you switch from the view. Big Calendar currently uses true JS Date objects for all dates. This is something we are possibly changing in the next major release, but this is the way it was originally built and how it currently works.

**Comment by bostonmacosx** [comment]
@cutterbl  well We'll have agree to disagree....

If the initial view can handle the data there is the reasonable expectation that other views can handle it as well. i find it odd that the process to interpret the date in the initial view differs than the changing of the view....as a coder myself I would consider that an inconsistency....if it was a data issue then 0 of the views would be able to handle the data.. if I put 

{ "end":"123"} all of the views would not be able to handle it because that is consistent...

**Comment by cutterbl** [comment]
@bostonmacosx You're frustrated. I understand. But, as the guy who spent months writing in the timezone support for Big Calendar, I promise you that this __is__ the issue. You must use true JS Date objects for all date props. Using a UTC string for a date will give you an initial 'false positive', but fall apart as you begin to interact. It is the single most common mistake a dev makes implementing Big Calendar the first time (happened with me too, first time out).

As I brought up before, we are discussing changing this in the next major release. If you're part of our new [Slack](https://join.slack.com/t/bigcalendar/shared_invite/zt-1ml1j99af-qIvqOfosMog1W7WxM0~j2Q) community you should join the `#next` channel to provide feedback.

**Comment by lupothecat** [comment]
I get the same issue, except it's asking to update 'DayColumn2' instead of 'DayColumn'. The project was created (copy/pasted) from provided examples in Typescript. 

Would appreciate any help.

**Comment by nick-catalist** [comment]
FWIW I am getting the error regarding `UNSAFE_componentWillReceiveProps` (and it seems to be preventing me from switching between weeks) despite having JS dates on all my events.
