### ISSUE TITLE
Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code.

### ISSUE THREAD

**Issue by justoverclockl** [jquense/react-big-calendar#2250]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

http://localhost.com

### Bug description

Passing from "month view", to "week view" cause this error:

```
Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code. See https://reactjs.org/link/unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://reactjs.org/link/derived-state

Please update the following components: DayColumn

```

### react-big-calendar version

1.5.0

### React version

18.2.0

### Platform/Target and Browser Versions

Windows chrome@latest

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a react-big-calendar issue and not an implementation issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nick-catalist** [comment]
Also experiencing this.

**Comment by justoverclockl** [comment]
Seems that this library is abandoned

**Comment by cutterbl** [comment]
@justoverclockl No, not abandoned. Just working on our 'next' version update (details can be found in our Slack group).

The warning you experience is just that, a warning. It is not an error, and does not block JS execution in any way. It is a message from the React team about a feature that will be (but is not yet) deprecated in the library. This is one of the items we will be resolving in our 'next' version.

You seem to be having an issue moving from one view to another. Can you give us some particulars about your code? Are you working with controlled or uncontrolled props for view and date? Is your application using Next.js maybe?

**Comment by nick-catalist** [comment]
FYI: React strict mode seems to actually prevent you from changing date ranges while in week mode. The Calendar does not re-render with the new date range after pressing "back" or "next" with the default toolbar. Probably fixable by using a custom toolbar...
