### ISSUE TITLE
Uncaught TypeError: d[("get" + method)] is not a function when i click on "+3 more" event

### ISSUE THREAD

**Issue by justoverclockl** [jquense/react-big-calendar#2251]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

http://localhost.com

### Bug description

here is my Calendar Component, i can't find a solution to this! please i need some help.

```
const localizer = momentLocalizer(moment)


<Calendar
                        localizer={localizer}
                        events={retrieveAllEvents}
                        defaultView="month"
                        startAccessor="start"
                        endAccessor="end"
                        style={{ minHeight: 1000, margin: '50px' }}
                        eventPropGetter={(event, start, end, isSelected) => ({
                            event,
                            start,
                            end,
                            isSelected,
                            style: { backgroundColor: event.assignedColor },
                        })}
                        components={{
                            event: EventTooltip,
                        }}
                    />
```

here is my object

```
const handleAddEvent = () => {
        if (newEvent)
            dispatch(
                addNewEvent({
                    title: newEvent.title,
                    description: newEvent.description,
                    start: moment(formatUTC(newEvent.start)).toDate(),
                    end: moment(formatUTC(newEvent.end)).toDate(),
                    assignedTo: newEvent.assignedTo,
                    assignedColor: newEvent.assignedColor,
                })
            )
    }
```

### react-big-calendar version

@latest

### React version

@latest

### Platform/Target and Browser Versions

windows chrome@latest

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a react-big-calendar issue and not an implementation issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by cutterbl** [comment]
Your reproduction link is not a CodeSandbox, so there is no way of seeing the exact issue. This error always comes up when your event's `start` and `end` dates are not true JS Dates. Big Calendar does not attempt to parse string dates. See our documentation on [Understanding Dates]](http://jquense.github.io/react-big-calendar/examples/index.html?path=/story/guides-understanding-dates--page)
