### ISSUE TITLE
How to hidden Week View's Day Time Show

### ISSUE THREAD

**Issue by zangguojun** [jquense/react-big-calendar#2256]
### Clear and concise description of the problem

<img width="1134" alt="image" src="https://user-images.githubusercontent.com/49148972/184599653-2e8bccc3-61f2-46c6-a272-e1f60a4f23c3.png">
For big data, I think the data in the red frame is useless and messy!
I want to know if there is a props to **HIDDEN** this

### Suggested solution

Now I can only use CSS to hide it

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples/index.html).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by cutterbl** [comment]
@zangguojun I'm afraid your question is unclear. You just want to hide the week view? Or you don't want the week view to be a time grid? (and, if that is the case, what else would it be?)

**Comment by zangguojun** [comment]
> @zangguojun I'm afraid your question is unclear. You just want to hide the week view? Or you don't want the week view to be a time grid? (and, if that is the case, what else would it be?)

Sry, I may not say clearly.
emmm, I only want to hidden the bottom time grid (2222 part), and heighten the top(11111 part)

<img width="771" alt="image" src="https://user-images.githubusercontent.com/49148972/184661319-3f8997c4-79f3-41e2-8659-b803852e0d21.png">

**Comment by cutterbl** [comment]
Then you may want to [write your own custom Week view component](http://jquense.github.io/react-big-calendar/examples/index.html?path=/story/guides-creating-custom-views--page)
