### ISSUE TITLE
Popover Mechanism on Events.

### ISSUE THREAD

**Issue by Canopix** [jquense/react-big-calendar#2269]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://replit.com/@Canopix/react-big-calendar-popover#src/mockedEvents.js

### Bug description

Hello Everyone! 

I'm trying to create a Calendar with popovers in events like the following example (that calendar was created with react-big-calendar) by people from @Toggl. 
![2022-09-08 14 34 40](https://user-images.githubusercontent.com/4460417/189189429-2ee009cf-6fbd-4799-8879-6b2f6e8b00b4.gif)

In my case, I created a new EventWrapper for the events and passed it in the `components` prop in Calendar. 
You can see it here: 

[https://replit.com/@Canopix/react-big-calendar-popover](https://replit.com/@Canopix/react-big-calendar-popover)

The main issue here is that my EventWrapper component is not in the same position as my event. 

<img width="591" alt="image" src="https://user-images.githubusercontent.com/4460417/189189974-50601d97-966b-41ee-9992-7f99a095aa0e.png">

This is the code of my EventWrapper 
```javascript
<div
      id="custom-wrapper"
      {...{
        ...props,
        // style: { ...style, top: `${style.top}%`, position: 'absolute' },
      }}
    >
      <Popover>
        <PopoverTrigger>
          <div>{props.children}</div>
        </PopoverTrigger>
        <PopoverContent>
          <PopoverBody>
            Are you sure you want to have that milkshake?
          </PopoverBody>
        </PopoverContent>
      </Popover>
    </div>
```

The style is commented to show the bug if I put the style attribute as position absolute and the top with %. 
The result is the following.

<img width="326" alt="image" src="https://user-images.githubusercontent.com/4460417/189190543-6ec635fd-3846-4886-8a09-02ac33913a8f.png">

But I lost the ability to resize the events, and the events are too small. The popover is working.

<img width="326" alt="image" src="https://user-images.githubusercontent.com/4460417/189190962-05330986-12d9-4b2b-91e1-7e4b02456449.png">

Now, I'm not know how to face this issue.
Is there a good guide to creating popovers on events? 

Thanks to all! 

### Expected Behavior

Custom Wrapper should be in the right place and not lose the ability to resize the events.

### Actual Behavior

I described above.

### react-big-calendar version

^1.5.0

### React version

^16.12.0

### Platform/Target and Browser Versions

MacOs Chrome

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a react-big-calendar issue and not an implementation issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by jsmith8954** [comment]
having the same issue.  Find any workaround?

this is also noticeable on the Fullstory example found here: https://jquense.github.io/react-big-calendar/examples/index.html?path=/story/additional-examples--custom-event-wrapper

It works correctly for the month view, but positioning is not correct for Week or Day view.

<img width="1039" alt="image" src="https://user-images.githubusercontent.com/16658156/197935012-424e3b92-22b6-47c2-8854-417cba02b7e5.png">

<img width="1339" alt="image" src="https://user-images.githubusercontent.com/16658156/197935085-1a89b7f6-85bc-473e-ae80-5c4edb37b5a1.png">

**Comment by Canopix** [comment]
I didn't find any workaround for this, so I changed the approach and create a modal. Is not the same but I prefer to deploy something done until the next iteration.

**Comment by RiteshMakan** [comment]
I can confirm that I am experiencing the same issue when overriding the `eventWrapper` with my own custom event container.

If I apply a similar component to Event, then my new component is nested within the original EventWrapper that is positioned correctly. I could use this solution, but then I would need to remove the default data in the original component and rather have it in my nested custom component

![image](https://user-images.githubusercontent.com/82932397/198296646-d2120a5b-145a-4cb4-a82d-e50dd7b1a0cd.png)
![image](https://user-images.githubusercontent.com/82932397/198296762-1dd40dbc-b2ae-485f-a10d-46f8c68bb9db.png)

**Comment by salao-na-mao** [comment]
Same issue here!

**Comment by salao-na-mao** [comment]
This works for me: https://github.com/jquense/react-big-calendar/issues/1217#issuecomment-502370452

**Comment by cutterbl** [comment]
Thank You @salao-na-mao. For other's trying to figure this out, please reference the comment above.
