### ISSUE TITLE
making the current months whole calendar view show in a side panel when in today view

### ISSUE THREAD

**Issue by Jen-DG** [jquense/react-big-calendar#2272]
I am making a react calendar using react-big-calendar. When I am in my default view, which is todays view, on the side I want to be able to also display the months calendar in a typical calendar form.

Has anyone been able to achieve this? I am posting a picture of my desired outcome for reference. I have been looking for a few hours and i haven't been able to find anyone whole has done something similar. so any help would be incredibly appreciated.

[
![Screenshot 2022-09-09 at 07 02 05](https://user-images.githubusercontent.com/83011240/189336012-ebce0599-2346-4c1e-973d-50e23f64b471.png)
](url)

**Comment by cutterbl** [comment]
Seems like a StackOverflow question. You would use a basic calendar control, in your right hand panel, and need some logic to sync displays in someway (probably by controlling your `date` prop at a higher level, and sharing between the two)
