### ISSUE TITLE
ERROR: react-dom.development.js:86 Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code.

### ISSUE THREAD

**Issue by justoverclockl** [jquense/react-big-calendar#2274]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

http://localhost.com

### Bug description

Show big calendar in a react application and then open console, you can see a warning

```
react_devtools_backend.js:4026 Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code. See https://reactjs.org/link/unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://reactjs.org/link/derived-state

Please update the following components: DayColumn
```

### Expected Behavior

DayColumn component need an update from mantainers

### react-big-calendar version

1.5.0

### React version

18.2.0

### Platform/Target and Browser Versions

linux

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a react-big-calendar issue and not an implementation issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by cutterbl** [comment]
We are already aware of this issue, and a search of Issues will show you that it's been previously reported.
