### ISSUE TITLE
Calender drag & drop event

### ISSUE THREAD

**Issue by ajaykumar1232** [jquense/react-big-calendar#2279]
I wanted to drag a event and drop it to the next month,day or week how can i do it?

**Comment by ajaykumar1232** [comment]
Is there any event which tells when a event is being dragged(event between drag start and drag end)

**Comment by cutterbl** [comment]
These questions are better served in StackOverflow, with this area intended for Issues and Feature Requests.

There is no facility for dragging an event from month to month (unless you put two instances side by side, maybe, with custom code for [drag from outside](http://jquense.github.io/react-big-calendar/examples/index.html?path=/story/addons-drag-and-drop--example-3)). In the month view you can drag an event from one week to another (just drop it on the day you wish), or to any specific day. Within the week view you can drag an event from one day to another, within the same week.
