### ISSUE TITLE
Event drag & drop

### ISSUE THREAD

**Issue by ajaykumar1232** [jquense/react-big-calendar#2280]
Is there any event which tells when a event is being dragged(event between drag start and drag end)

**Comment by cutterbl** [comment]
These questions are best asked on StackOverflow. This area is used for Issues and Feature Requests.

You should [review the Drag & Drop](http://jquense.github.io/react-big-calendar/examples/index.html?path=/story/addons-drag-and-drop-introduction--page) documentation. Pay attention to the 'props'. There are multiple examples available.
