### ISSUE TITLE
React-big-calendar Toolbar access outside calendar component

### ISSUE THREAD

**Issue by IronTony** [jquense/react-big-calendar#2283]
Hello, this is not a real issue, but I cannot find any documentation or help also elsewhere, so I try here.

I am trying to understand if it is possible with react-big-calendar to have a custom Toolbar with next/prev buttons and also the other buttons outside the normal calendar component or also access to them from outside, creating a custom Toolbar placed another position then the usual one?

**Comment by naothomachida** [comment]
Me too
