### ISSUE TITLE
Support React 18 types

### ISSUE THREAD

**Issue by dohomi** [jquense/react-big-calendar#2291]
### Clear and concise description of the problem

With React 18 typescript currently there is a typing error. 
```
'Calendar' cannot be used as a JSX component.
  Its instance type 'Calendar<EventCalendar, object>' is not a valid JSX element.
    The types returned by 'render()' are incompatible between these types.
```

### Suggested solution

It would be great if React 18 types would not throw an error.

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples/index.html).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by bu6n** [comment]
Can you provide a repro link? Just updated to React 18 without error.

**Comment by iurylemos** [comment]
The solution in my case was simple. This error happens only for typescript applications

**Example**:

`
const **CalendarWrapper** = Calendar as any;

<**CalendarWrapper**
        localizer={localizer}
        events={formatEvents}
        views={["day"]} />
`

It looks like Hungry but it solves the problem and the typescript does not reclaim

**Comment by iurylemos** [comment]
The solution in my case was simple. This error happens only for typescript applications

Example:

`
const **CalendarWrapper** = Calendar as any;

<**CalendarWrapper**
localizer={localizer}
events={formatEvents}
views={["day"]} />
`

It looks ugly but it solves the problem and the typescript does not reclaim

**Comment by cutterbl** [comment]
Types for Big Calendar are not controlled within Big Calendar, as they currently come from [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-big-calendar)

**Comment by zaini** [comment]
For now, just add `@ts-ignore`. I wouldn't suggest doing the `as any` strat because you lose typing.

```js
        <div className="h-[800px]">
            {/* @ts-ignore */}
            <Calendar<TimeEntry>
                localizer={localizer}
                events={timeEntries}
                startAccessor="start"
                endAccessor="end"
                defaultView="week"
                views={['week', 'day', 'month', 'agenda']}
                components={{
                    event: EventComponent,
                    toolbar: CustomToolbar,
                }}
                selectable
                onSelectSlot={handleSelectSlot}
            />
        </div>
```

**Comment by sandrosimas** [comment]
I was able to fix this using the following on `package.json`:
```
"resolutions": {
    "@types/react": "18.3.23"
}
```
It looks like `@types/react-big-calendar` uses react 19.
