### ISSUE TITLE
Supports timezone setting in luxonLocalizer

### ISSUE THREAD

**Issue by hdoan-codaio** [jquense/react-big-calendar#2292]
### Clear and concise description of the problem

We use Luxon in our React app, and it'd be nice to use the luxonLocalizer as our Localizer. However, given that user can customize their timezone, and each Calendar may have its own timezone, we cannot simply set the global timezone on Luxon to a given timezone like in the example: https://github.com/jquense/react-big-calendar/blob/master/stories/demos/exampleCode/luxon.js

### Suggested solution

If LuxonLocalizer accepts {timezone} as a config (similar to the `firstDayOfWeek` config), it'll allow us to use the luxon localizer instead of writing our own.

### Alternative

We'd have to write our own localizer and repeat much of the logic in LuxonLocalizer

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples/index.html).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by cutterbl** [comment]
You can already [do timezones with the Luxon Localizer](http://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/examples--luxon-localizer)

**Comment by hdoan-codaio** [comment]
@cutterbl: The luxonLocalizer doesn't support custom timezone per localizer. That's what I'm requesting here.

In the example code, you'd see that the timezone is set globally for Luxon, but that's not enough for us. We'd like it to be customized per localizer 

https://github.com/jquense/react-big-calendar/blob/master/stories/demos/exampleCode/luxon.js#L33

**Comment by cutterbl** [comment]
"per localizer"? I'm afraid I do not follow. There is only a single localizer instance per calendar instance. Are you putting more than on Calendar instance on a page?

**Comment by hdoan-codaio** [comment]
Yes, by "per localizer" I mean per Calendar. We can have more than one calendar instance on a page, and each may have its own timezone.

**Comment by hdoan-codaio** [comment]
Now, I doubt people will have crazy settings with different timezone per calendar like that, but it's possible. At least, the calendar may have different timezone from the rest of the website. We don't want to set the global Luxon timezone to the calendar timezone.

**Comment by hdoan-codaio** [comment]
I'm close to replicate the whole localizer on our own repo in order to support timezone lol. LMK if you're interested, I can give it a try to add a timezone params for LuxonLocalizer.

**Comment by hdoan-codaio** [comment]
@cutterbl LMK if you'd like it & I can give it a try to add a timezone params for LuxonLocalizer.
