### ISSUE TITLE
Luxon Localizer with TypeScript 

### ISSUE THREAD

**Issue by tomhands1** [jquense/react-big-calendar#2295]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/react-big-calendar-example-forked-ib8nqm?file=/src/App.tsx

### Bug description

luxonLocalizer exposed by `react-big-calendar` accepts a type of `config: object` but expects the DateTime from luxon followed by the config.
We are trying to implement with TS and getting an error for `luxonLocalizer(DateTime, { firstDayOfWeek: 1 })` as the luxonLocalizer function exposed by react-big-calendar only expects one argument

Are there any more specific types we could use?

### react-big-calendar version

1.5.0

### React version

18.0.2

### Platform/Target and Browser Versions

Chrome

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a react-big-calendar issue and not an implementation issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by butermann** [comment]
This is probably an error in `@types/react-big-calendar`, you could propose a change there?
See https://github.com/DefinitelyTyped/DefinitelyTyped/blob/d0d6196ddf354adbe01005e2206834cc6470c8be/types/react-big-calendar/index.d.ts#L456

**Comment by vpzomtrrfrt** [comment]
looks like this have been resolved by DefinitelyTyped/DefinitelyTyped#63557
