### ISSUE TITLE
Repeating timeslot and wrong time on the day when daylight saving time change for America time zone

### ISSUE THREAD

**Issue by snuzi** [jquense/react-big-calendar#2296]
### Check that this is really a bug

- [x] I confirm

### Reproduction link

https://codesandbox.io/s/react-big-calendar-example-forked-w4u7s2?file=/index.js

### Bug description

On the day when daylight saving time change for `America` (at least) time zones at midnight the 1:00AM is repeating. This results on a wrong event time display by one hour as seen in the reproduction environment or the attached screenshot.
Ex. The event is at **6:00 AM - 7:00 AM** but in the calendar time slot it is shown at **5:00 AM**
![react-big-calendar-timezone issue](https://user-images.githubusercontent.com/10135355/200517296-9bf3726d-0fe6-4bcb-bef5-51716d43b1ab.png)
**

### Expected Behavior

Correct event time

### Actual Behavior

Event time is shown one hour before the real time.

### react-big-calendar version

1.5.0

### React version

18.2.0

### Platform/Target and Browser Versions

Chrome

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a react-big-calendar issue and not an implementation issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by snuzi** [comment]
@cutterbl  thank you for the response, I just checked the Codesandbox demo again and I still see it wrong, as in the first screenshot.
Might this be related to a users local browser's timezone maybe, even though it is specifically set as `America/New_york` in the code? My local timezone is `Europe/Vienna` btw.

**Comment by cutterbl** [comment]
I tried setting a location Sensor in Chrome, but that didn't change anything (maybe because CodeSandbox loads in an iFrame?) I also tried changing my system timezone as well, but that didn't change anything either. Not sure how to troubleshoot this...

**Comment by bu6n** [comment]
You'd probably have to change the timezone on your computer to test.

It's probably a bug in the localizer (or just a case that hasn't been thought about).
Same happens with Luxon.
With dayjs (available in `>1.6.2`) however the problem doesn't seem to happen.

```js
import { Calendar, dayjsLocalizer } from "react-big-calendar";
import dayjs from "dayjs";
import timezone from "dayjs/plugin/timezone";

dayjs.extend(timezone);
dayjs.tz.setDefault("America/New_York");
const localizer = dayjsLocalizer(dayjs);
```

This seems to work in your sandbox. I don't know however if this would have other consequences on your codebase.

**Comment by cutterbl** [comment]
@bu6n Thanks for looking into this. Yeah, I changed my system (OS) timezone, and still couldn't replicate. Think you could dig into the localizers and see what the difference might be between moment/Luxon/dayjs localizers in this instance?

**Comment by snuzi** [comment]
Hi @cutterbl
Thank you for the fix. I found another case where this issue is present.

It happens now when using `min` and `max` calendar properties.

I have updated the demo in the reproduction link above (**please make sure that the time zone on your computer/mobile is set to `New York` )**.


Steps to reproduce:
1. Set `min` and `max` (maybe max is not necessary).
2. Change the time zone on your local computer to **New York**.

**Comment by peterholcomb** [comment]
> Hi @cutterbl Thank you for the fix. I found another case where this issue is present.
> 
> It happens now when using `min` and `max` calendar properties.
> 
> I have updated the demo in the reproduction link above (**please make sure that the time zone on your computer/mobile is set to `New York` )**.
> 
> Steps to reproduce:
> 
> 1. Set `min` and `max` (maybe max is not necessary).
> 2. Change the time zone on your local computer to **New York**.

We are also seeing this issue.  Changing the view to work_week fixed it temporarily for us.

**Comment by prestontunnellwilson** [comment]
Created a separate issue since this issue is already closed: https://github.com/jquense/react-big-calendar/issues/2466

Thank you, @snuzi for creating the reproducible example!
