### ISSUE TITLE
Avoid wwo events sharing one time overlap

### ISSUE THREAD

**Issue by Canopix** [jquense/react-big-calendar#2302]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

-

### Bug description

I have two events that share only one time: 

Event A: Finish at 4 PM
Event B: Start at 4 PM 

The events are being split in the calendar and are not needed.

How avoid this? 
<img width="401" alt="image" src="https://user-images.githubusercontent.com/4460417/201426007-11a7728a-6217-4175-a095-252d8d2ed790.png">

### react-big-calendar version

-

### React version

=-

### Platform/Target and Browser Versions

-

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a react-big-calendar issue and not an implementation issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by butermann** [comment]
There already similar issues to this problem. Would #1530 help for example?

**Comment by Canopix** [comment]
Hey everyone!

I just wanted to drop a quick note to say thank you for all your help on the react-big-calendar issue with overlapping events. With your suggestions and solutions, I was able to solve the issue by adjusting minimumStartDifference with the overlap function. You guys are awesome, and I really appreciate all the time and effort you put into helping me out.


Thanks again for everything!

**Comment by Canopix** [comment]
Hey everyone!

Just wanted to give you all a quick update on my `react-big-calendar` issue. Thanks to the awesome folks in this [Github issue](https://github.com/jquense/react-big-calendar/issues/1530), I was able to solve the problem of overlapping events by tweaking the `minimumStartDifference` with the `overlap` function.

I really appreciate all the help and support from the community. Your suggestions and solutions made a huge difference, and I can't thank you enough for your time and effort in helping me out.

Hope this solution will be helpful for others who run into similar issues in the future.

Thanks again, you guys rock!
