### ISSUE TITLE
Help with using the examples

### ISSUE THREAD

**Issue by edentsubery** [jquense/react-big-calendar#2307]
Hello,  I am really new to react and in need of help.
 I tried using the dndOutsideSource.js  source to make a calendar that you can drag and drop to get a new event, I am not quite sure how to use it though. I left only the relevant parts to me in my code, and I am trying to call the function from another function. I get the following errors.
![image](https://user-images.githubusercontent.com/73164901/204149061-16836112-fc87-46e4-813a-1e46d6b19c44.png)

this is how I called it
![image](https://user-images.githubusercontent.com/73164901/204149135-25c67cd6-0411-4142-9785-6c3238ba8cc6.png)

Would appreciate  any help. thank you!

**Comment by butermann** [comment]
Hi Eden. It's difficult to help with so little code. Can you provide a reproduction link?
Also, the GitHub issues are more for bugs. If you need support, maybe you can try StackOverflow?

**Comment by ahpkadota** [comment]
A localizer object is expected as argument by the DnDOutsideResource, pass it as a prop or define the localizer within the component function. I tried to answer here:
https://stackoverflow.com/questions/74592034/react-big-calendar-drag-and-drop/78442220#78442220
