### ISSUE TITLE
Day View: Event ending after midnight are not showed correctly

### ISSUE THREAD

**Issue by popeating** [jquense/react-big-calendar#2311]
I have a calendar with day view created as follow:
```
<Calendar
        components={{
          event: (e) => EventMain(e),
          agenda: { event: (e) => EventAgenda(e) },
        }}
        events={events}
        localizer={localizer}
        resources={resourcesMap}
        resourceIdAccessor="resourceId"
        resourceTitleAccessor="restitle"
        messages={messages}
        onSelectEvent={(e) => handleSelectEvent(e)}
        eventPropGetter={(e, start, end, isSelected) =>
          eventStyler(e, start, end, isSelected)
        }
        selectable
        onSelectSlot={(slotInfo) => {
          selectSlot(slotInfo);
        }}
        onView={(e) => setView(e)}
        min={new Date(2020, 1, 0, 19, 0, 0)}
        step={30}
        timeslots={1}
      />
```

Some events could end after midnight, in this case in day view events are showed at the top of the view and compressed, instead that starting at the correct time and reaching the end

![screenshot-localhost_3000-2022 12 09-10_07_34](https://user-images.githubusercontent.com/10193354/206667321-59ecab26-dffc-4446-b8fe-f233d725740e.png)

In the screenshot the event compressed at the top start at 22:30 and end next day at 1:00; i need it to be placed correctly at least at start time.

any suggestion?

**Comment by butermann** [comment]
Maybe `showMultiDayTimes`?
https://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/props--show-multi-day-times

**Comment by popeating** [comment]
Thank you, ill have a look, actually i dont really need the event to be taken to the next day since these are reservation for a restaurant and 99,99% of the ones that go over midnight, i dont really care when they really end (and i dont want to show them the next day)
at the moment i solved by rewriting the end time of the evento to 23:59 if the end time is the next day based on start time
