### ISSUE TITLE
Drag & Drop issues

### ISSUE THREAD

**Issue by popeating** [jquense/react-big-calendar#2312]
I have installed the drag&drop addon but i have some issues; for example when i am in the day view and i drag & drop an event and update it, the calendar is "moved" to today (it does not stay on same day i operated the drag&drop);
also when in month view and i click the "+ X more" to have the detail, the day it opens is always today and not the correct day, when i click a slot (that is handled by onSelectSlot) it get back to today...
this is how i implemented my calendar:

```
<DnDCalendar
        components={{
          event: (e) => EventMain(e),
          agenda: { event: (e) => EventAgenda(e) },
        }}
        events={events}
        view={view}
        resizable={false}
        localizer={localizer}
        resources={resourcesMap}
        resourceIdAccessor="resourceId"
        resourceTitleAccessor="restitle"
        messages={messages}
        onSelectEvent={(e) => handleSelectEvent(e)}
        onEventDrop={(e) => dropEvent(e)}
        eventPropGetter={(e, start, end, isSelected) =>
          eventStyler(e, start, end, isSelected)
        }
        selectable
        onSelectSlot={(slotInfo) => {
          selectSlot(slotInfo);
        }}
        onView={(e) => {
          setView(e);
        }}
        min={new Date(2020, 1, 0, 19, 0, 0)}
        step={30}
        timeslots={1}
      />
```

the _view_ is a state i use to check which view im currently on (since i need to disable certain features based on view)
if i dont use the view, every time i drop it get back to month view, even when im on day view

**Comment by butermann** [comment]
It's difficult to help without having the whole code.  If you create an issue with the "Big Calendar Issue" template, you are encouraged to provide a codesandbox example.

Also, GitHub issues are more for bugs in the library itself. If you need support, StackOverflow may be better.
