### ISSUE TITLE
How to split ui month calendar events with start end date range

### ISSUE THREAD

**Issue by tanz98** [jquense/react-big-calendar#2315]
### Clear and concise description of the problem

Hi i need to know how to spread the ui calendar month without one by one date eventlist? here my code

``` 
  const [myEventsList, setMyEventsList] = useState([
    // i need spread list events this in month calendar view
    {
      title: "Test from 12 to 17",
      detail: "test",
      start: new Date(2022, 11, 12),
      end: new Date(2022, 11, 17),
      allDay: true
    },
    // both below is ui i expect
    {
      title: "Test from 12 to 13 spread",
      detail: "test",
      start: new Date(2022, 11, 12),
      end: new Date(2022, 11, 12),
    },
    {
      title: "Test from 12 to 13 spread",
      detail: "test",
      start: new Date(2022, 11, 13),
      end: new Date(2022, 11, 13),
      allDay: true
    },
  ]);
```
Here my expected UI
<img width="906" alt="Screenshot 2022-12-15 at 19 21 30" src="https://user-images.githubusercontent.com/35478469/207858407-529e7551-2811-4c87-90f2-b5f77d1cbd55.png">

### Suggested solution

If the feature dont have like that, maybe i suggested to add props in events : spreadui : boolean 
```
  const [myEventsList, setMyEventsList] = useState([
    // i need spread list events this in month calendar view
    {
      title: "Test from 12 to 17",
      detail: "test",
      start: new Date(2022, 11, 12),
      end: new Date(2022, 11, 17),
      spredui: true // may
    },
  ]);
```

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples/index.html).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by cutterbl** [comment]
I understand what it is you would like to do, but this is unsupported in Big Calendar. An event that spreads multiple days would span those days in the month view.
