### ISSUE TITLE
How to default the Week view to show from 6:00 AM instead of 12:00 AM?

### ISSUE THREAD

**Issue by debotos** [jquense/react-big-calendar#2317]
<img width="417" alt="Screenshot 2022-12-16 at 2 02 13 PM" src="https://user-images.githubusercontent.com/29367677/208051661-923a9bfc-e586-4aef-9dd1-f08e7aa37925.png">

<img width="573" alt="Screenshot 2022-12-16 at 2 03 04 PM" src="https://user-images.githubusercontent.com/29367677/208051828-c2f78080-a90a-4faa-9b4a-5613352ad84c.png">

**Comment by debotos** [comment]
Solution is pass `scrollToTime` props.
```js
const scrollToTime = new Date().setHours(6)
```

**Comment by cutterbl** [comment]
Use the [min](http://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/props--min) and [max](http://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/props--max) props.

**Comment by kml-rohillaa** [comment]
@cutterbl Can we render from 8am of current day to 7am of next day ?
