### ISSUE TITLE
Add documentation for Luxon localizer

### ISSUE THREAD

**Issue by corymharper** [jquense/react-big-calendar#2320]
### Clear and concise description of the problem

In [this commit](https://github.com/jquense/react-big-calendar/commit/ad8defa643692911fd0b00c71b70de94715140a9) support for Luxon was added. However, the readme was never updated to reflect its intended usage or that it was supported at all.

### Suggested solution

Add documentation detailing usage and support of Luxon as a localizer.

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples/index.html).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by cutterbl** [comment]
You are correct, that the README seems to be missing the Luxon example. However, the [documentation site](http://jquense.github.io/react-big-calendar/examples) has an [example of using the Luxon Localizer](http://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/examples--luxon-localizer) that links to the code.
