### ISSUE TITLE
How to make the default toolbar responsive according to varying screen size?

### ISSUE THREAD

**Issue by Shakya7** [jquense/react-big-calendar#2324]
Hello everyone. 

I am making a project for myself where I needed to integrate one calendar component. After almost doing a good amount of research, I found out React Big Calendar is the best option to choose for.

However, I am getting one small issue.
How can I make the default toolbar responsive to varying screen size? I have gone through some issues here, but mostly majority of them is of implemeting a new custom toolbar. But I dont want that. I just want to make the deafult toolbar responsive, because its breaking the layout.

```
<Calendar
     localizer={localizer}
     events={events}
     startAccessor="start"
     endAccessor="end"
     style={{ height: 500}}
     showMultiDayTimes={true}
     showAllEvents={true}
     selectable
     onSelectSlot={onSelectSlot}
     className="px-8 text-slate-400 text-filter xsm:text-base"
     dayPropGetter={calendarStyle} 
/>
```

I am using tailwind with react. As you can see I have added a media query---> "text-filter xsm:text-base"; but its taking effect only inside the cell contents.
![react-big-calendar](https://user-images.githubusercontent.com/68787887/210135594-972c5dc7-cdaa-4beb-8a60-e603f0767fcc.png)

I want the similar action of resizing that is happening to the cells and cell contents, for the toolbar component also.

Can anybody help me on this? I am really struggling to find answers in the internet.
Thank you!

**Comment by Shakya7** [comment]
I figured out the issue finally. 
So, we have to basically manipulate by the _class names of the toolbar components in our App.css file_.

Let me lay out the class names for corresponding toolbar components.

i)Toolbar component (Parent DIV) ---> **rbc-toolbar**
ii) Toolbar buttons (Two Parent DIV) ---> **rbc-btn-group**
iii) Toolbar middle label ---> **rbc-toolbar-label**

Closing this issue. 
Thank you.

**Comment by cutterbl** [comment]
@Shakya7 Perhaps you could provide a pull request for this?
