### ISSUE TITLE
v1.6.0 not released correctly

### ISSUE THREAD

**Issue by nichtsam** [jquense/react-big-calendar#2330]
The actions for #2264 failed to release to registry, but had created a tag v1.6.0.
Hence the actions for #2326 detected a tag v1.6.0 and started there, didn't finish the real release process.

**Comment by onesine** [comment]
Indeed, I also have the same problem.

**Comment by nichtsam** [comment]
Github Actions Bot has created an issue #2334 , might be helpful.

**Comment by jquense** [comment]
I updated the token, should be gtg now hopefully

**Comment by cutterbl** [comment]
@jquense Still getting release failures. Did you update the existing token associated with the `NPM_TOKEN` in the repo's Secrets? This is the exact error we're seeing

> [2:43:17 PM] [semantic-release] › ✖  EINVALIDNPMTOKEN Invalid npm token.
The npm token (https://github.com/semantic-release/npm/blob/master/README.md#npm-registry-authentication) configured in the NPM_TOKEN environment variable must be a valid token (https://docs.npmjs.com/getting-started/working_with_tokens) allowing to publish to the registry [https://registry.npmjs.org/.](https://registry.npmjs.org/)

> If you are using Two Factor Authentication for your account, set its level to "Authorization only" (https://docs.npmjs.com/getting-started/using-two-factor-authentication#levels-of-authentication) in your account settings. semantic-release cannot publish with the default "
Authorization and writes" level.

> Please make sure to set the NPM_TOKEN environment variable in your CI with the exact value of the npm token.

**Comment by K0rINf** [comment]
3 weeks have passed. Can someone submit a new release?

**Comment by nichtsam** [comment]
> @jquense Still getting release failures. Did you update the existing token associated with the `NPM_TOKEN` in the repo's Secrets? This is the exact error we're seeing
> 
> > [2:43:17 PM] [semantic-release] › ✖  EINVALIDNPMTOKEN Invalid npm token.
> > The npm token (https://github.com/semantic-release/npm/blob/master/README.md#npm-registry-authentication) configured in the NPM_TOKEN environment variable must be a valid token (https://docs.npmjs.com/getting-started/working_with_tokens) allowing to publish to the registry [https://registry.npmjs.org/.](https://registry.npmjs.org/)
> 
> > If you are using Two Factor Authentication for your account, set its level to "Authorization only" (https://docs.npmjs.com/getting-started/using-two-factor-authentication#levels-of-authentication) in your account settings. semantic-release cannot publish with the default "
> > Authorization and writes" level.
> 
> > Please make sure to set the NPM_TOKEN environment variable in your CI with the exact value of the npm token.

@jquense I'm not sure, but I think this is an issue that only the repo owner can resolve?

**Comment by jquense** [comment]
Neither of us have been able to get semantic release working. I am not blocking manual releases to npm at this point! Still happy to help but no time to actively troubleshoot why the tooling isn't working

**Comment by fotijr** [comment]
Thank you all for the continued effort on restoring this 👏
