### ISSUE TITLE
Month View: Is there a way to control the row height when we click on "+X more" link in any cell of that row?

### ISSUE THREAD

**Issue by vasanthkumar258** [jquense/react-big-calendar#2346]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://stackblitz.com/edit/big-calendar-demo-mfzisu?file=index.js

### Bug description

In Calendar Month view, a row will have cells with different "+X more" link.

Current Behaviour - When we click on "+X more" link, we either go to day view or open a pop up

Expected Behaviour - When we click on "+X more" link, we expand the entire row to the height that fits the all the events and show Collapse for all the Days in a row?

### Expected Behavior

When we click on "+X more" link, we expand the entire row to the height that fits the all the events and show Collapse for all the Days in a row?

### Actual Behavior

 When we click on "+X more" link, we either go to day view or open a pop up

### react-big-calendar version

1.5.2

### React version

18.2.0

### Platform/Target and Browser Versions

Chrome

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a react-big-calendar issue and not an implementation issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by cutterbl** [comment]
@vasanthkumar258 This is not a bug, but expected, documented behavior of Big Calendar

**Comment by vasanthkumar258** [comment]
@cutterbl, Yeah this is not a bug. Can we achieve the above behaviour by using any workaround?

**Comment by cutterbl** [comment]
@vasanthkumar258 In the way that Big Calendar is currently rendered, I don't think there is. But I can't be certain. You might ask on StackOverflow though, as someone may have tried this.
