### ISSUE TITLE
[Question] Is it possible to format big calendar like

### ISSUE THREAD

**Issue by markditianquin** [jquense/react-big-calendar#2347]
Hello,

I'm thinking of using this package to create a calendar like this.
![image](https://user-images.githubusercontent.com/12157330/214686037-d5a66551-3214-49b2-8bca-3f4eb1823123.png)

Can I achieve this using react-big-calendar? 
I know toolbar area can be customized. 
But can I add week number on each row? If so, how?

Thanks,
Mark

**Comment by bu6n** [comment]
Maybe the easiest way would be to use the month view of `react-big-calendar` and create your `week x` components outside of it ? Same goes for the days on top :)

**Comment by cutterbl** [comment]
@markditianquin Perhaps with a custom Month view? Better asked on StackOverflow, or possibly from our Slack community.
