### ISSUE TITLE
How to add time slots?

### ISSUE THREAD

**Issue by marlonhub** [jquense/react-big-calendar#2369]
Hi, I have the time slots working but can anyone point me towards how to allow users to choose a time and not be assigned the local time of their machine? Thank you.

**Comment by cutterbl** [comment]
Welcome to "dealing with dates on the web". Browser, by default, will always display dates in the local timezone of the machine. If you want to 'cast' all of your dates to another timezone, you can do so with the `luxon`, `moment` or the `dayjs` localizers. [There's an example in the Documentation](http://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/examples--luxon-localizer).
