### ISSUE TITLE
dragFromOutsideItem does not work in week view

### ISSUE THREAD

**Issue by gnapse** [jquense/react-big-calendar#2383]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

http://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/addons-drag-and-drop--example-3

### Bug description

When using `dragFromOutsideItem` to give feedback as you drag over the calendar something from outside, the feedback item appears as expected when in month view, but not when in week view. In week view, it appears when dragging over the full-day events area. But it does not appear when dragging over the hourly planning area.

https://user-images.githubusercontent.com/15199/226417975-97067d27-5ccb-4fc4-91a0-055752dfcad3.mp4

### Expected Behavior

I'd expect to get an event-like element appearing in the hourly planning area as I drag over it.

### Actual Behavior

Nothing appears over the hourly planning are in a week or day view as I drag over an event from outside.

### react-big-calendar version

1.6.8

### React version

18.2.0

### Platform/Target and Browser Versions

Any browser

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a react-big-calendar issue and not an implementation issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by digitalw** [comment]
Same goes for Day view.

**Comment by joeskyforged** [comment]
Any interest in fixing this? Makes dragFromOutsideItem completely useless for my use case

**Comment by Daveiano** [comment]
For me, the same as for @joeskyforged applies, would be great if this could be fixed.
