### ISSUE TITLE
Support "show more" in "All day" in week view

### ISSUE THREAD

**Issue by gnapse** [jquense/react-big-calendar#2386]
### Clear and concise description of the problem

When you have too many all-day events, it can become cumbersome in the week view:

<img width="978" alt="CleanShot 2023-03-24 at 10 44 40@2x" src="https://user-images.githubusercontent.com/15199/227537876-992835ae-407f-49d8-b55e-86491e2693d1.png">

### Suggested solution

Add a "show more" that would show a popup, just as with day cells in month view

### Alternative

I added this CSS rule:

```css
.rbc-allday-row {
  max-height: 110px;
  overflow: auto;
}
```

And it mitigates the issue, but not a great UX:

![CleanShot 2023-03-24 at 10 47 11](https://user-images.githubusercontent.com/15199/227538423-83a1e448-adce-4bbc-9e28-57566d26ddc1.gif)

### Additional context

Full Calendar seems to support it:

<img width="1123" alt="image" src="https://user-images.githubusercontent.com/15199/227539171-21613490-2967-4882-955b-bb0e4a6576ba.png">

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples/index.html).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by fornesarturo** [comment]
Please review the changes proposed, I've also been looking for this feature before
