### ISSUE TITLE
Support for mounting a custom "Show More" popup at a particular cell

### ISSUE THREAD

**Issue by tymefighter** [jquense/react-big-calendar#2391]
### Clear and concise description of the problem

I am using big calendar in my application, and I need to show a popup which appears on clicking the "Show More" button. But, this popup is very different from the one currently rendered by big calendar, hence I need to implement my custom popup instead of using the built-in one.

The issue I am facing is that the current contract of the calendar component has this `onShowMore` callback and this `messages` configuration function, both of these do not provide enough information for me to **mount my popup at the cell in which the "Show More" was clicked**.

1. The issue with `onShowMore`:  `onShowMore` provided me with the `events` and the `date` of the cell in which the "Show More" button was clicked. But it doesn't provide me with the `target` HTML element of the "Show More" button. Hence, I am not able to mount my popup at that specific cell.

<img width="594" alt="image" src="https://user-images.githubusercontent.com/40702069/230784179-1436f9d9-7dd4-41c8-b4e8-4445e2fdb3b6.png">

2. The issue with `messages`: The `showMore` property on `messages` allows me to render custom JSX (if I ignore the string output type). Here I could technically render my own button, and manage my own click handlers. This would provide me with my target element for mounting my popup. But, here the issue is that I don't have access to the `events` and `date` of that particular cell, hence I won't be able to show the relevant information in my popup.

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/40702069/230784297-e68799f7-2b90-445e-b148-9f35415d4024.png">

Neither of the above two props provide me with enough information to render my popup while mounting it at the cell in which "Show More" was clicked.

### Suggested solution

I suggest that we add support for `target` argument as well in the `onShowMore` callback. The updated function would look like this:

```
function (events: Array[event: Object], date: Date, target: HTMLElement) => any
```

I could then just use the `events` and `date` information to render my custom popup, while being mounted at `target` HTML element.

### Additional context

I have read this issue - https://github.com/jquense/react-big-calendar/issues/1147. But it doesn't solve my problem. The fix which was raised for this issue only allows me to render my own popup, but does not allow me to mount it at a specific cell.

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples/index.html).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [X] I'm willing to open a PR

**Comment by qjinle** [comment]
I also need this feature

**Comment by b9shal** [comment]
Adding this to RBC would be very convenient for adding custom popup.

**Comment by FerShihab** [comment]
yeah it will good, that will be a good feature

**Comment by stoner2497** [comment]
@tymefighter Do you find any work around for this - like a wrapper function or dynamic positioning?

**Comment by knguye** [comment]
Am I wrong, or was the PR for the fix only adding a custom element for the `X+ more` text below the events in the calendar, but this discussion is about the actual popup that displays when clicking on that text?
