### ISSUE TITLE
Year view on Big calendar

### ISSUE THREAD

**Issue by anoukdeserranno1** [jquense/react-big-calendar#2392]
I'm using Typescript and want a custom Year view.

Currently this is my code.

```
        <Calendar
          localizer={localizer}
          events={myEvents}
          views={{
            month: true,
            year: Year
          }}
          startAccessor="start"
          endAccessor="end"
          eventPropGetter={eventStyleGetter}
          components={{
            dateCellWrapper: eventWrapper
          }}
          onSelectSlot={handleSelectSlot}
          showAllEvents
          selectable
        />
```

But I keep getting this error message. 
No overload matches this call.
  Overload 1 of 2, '(props: CalendarProps<Event, object> | Readonly<CalendarProps<Event, object>>): Calendar<Event, object>', gave the following error.
    Type '{ month: true; year: typeof Year; }' is not assignable to type 'ViewsProps<Event, object> | undefined'.
      Object literal may only specify known properties, and 'year' does not exist in type 'ViewsProps<Event, object>'.
  Overload 2 of 2, '(props: CalendarProps<Event, object>, context: any): Calendar<Event, object>', gave the following error.
    Type '{ month: true; year: typeof Year; }' is not assignable to type 'ViewsProps<Event, object> | undefined'.
      Object literal may only specify known properties, and 'year' does not exist in type 'ViewsProps<Event, object>'.ts(2769)

But it seems to work here (in js )https://codesandbox.io/s/jjmky5047y?file=/src/index.js

**Comment by cutterbl** [comment]
This isn't a problem with Big Calendar, but rather the [TypeScript definitions from DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped). Big Calendar does not, currently, maintain it's own TS 'types'. You should file a bug with them, or submit a PR to them.
