### ISSUE TITLE
formatdate is not exported from '@fullcalendar/react'

### ISSUE THREAD

**Issue by boxingcoder00** [jquense/react-big-calendar#2396]
### Clear and concise description of the problem

I am putting a react application using @fullcalendar/react and i keep getting the error below .

![error2](https://user-images.githubusercontent.com/111091683/233510826-ff68bdd3-b168-4d26-b8db-152096cf753c.png)

### Suggested solution

i think its the issue of the current one I have but I cant find any details on it looking for a misspell also but cant find any  below is how i have it set up 

### Alternative

import { useState } from "react";
import FullCalendar, { formatDate } from "@fullcalendar/react";
import dayGridPlugin from "@fullcalendar/daygrid";
import timeGridPlugin from "@fullcalendar/timegrid";
import interactionPlugin from "@fullcalendar/interaction";
import listPlugin from "@fullcalendar/list";
import {
  Box,
  List,
  ListItem,
  ListItemText,
  Typography,
  useTheme,
} from "@mui/material";
import Header from "../../components/Header";
import { tokens } from "../../theme";

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples/index.html).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by jquense** [comment]
This isn't the repo for full calendar, looks like you have the wrong project

**Comment by boxingcoder00** [comment]
oh wow sorry about that
