### ISSUE TITLE
Swapping resource/time in day view

### ISSUE THREAD

**Issue by popeating** [jquense/react-big-calendar#2399]
At the moment day view when using resources (in my case rooms/appointment) shows the resources in colum and the time in rows; it would be nice to have a props to swap this behaviour (time in columns, resources in rows), this would be useful especially if (like me) you have a lot of resources and small time span, in my case i have around 20 rooms and a span from 7pm to midnight; so my interface show the occupied timslots very thin but very tall!
i tried to modify it with a dayLayoutAlgorithm using a custom style but with no luck, any suggestion? i would also create a custom view but time is not on my side at the moment

**Comment by cutterbl** [comment]
@popeating Thank you for your feedback. This idea has been brought up several times in the past, and is a feature request item on the board for consideration in the next major version update to Big Calendar. I'm going to close this issue, but know that "we hear you".

**Comment by RiswanaA** [comment]
Hi, Is this feature (swapping resource/time ) completed ? If so, please let me know where to find code for this . Thanks in advance

**Comment by cutterbl** [comment]
@RiswanaA No, this is still not yet available

**Comment by manhld-scts** [comment]
Hi there, is this feature available now?
