### ISSUE TITLE
Button Issue.

### ISSUE THREAD

**Issue by vivpan24** [jquense/react-big-calendar#2404]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/props--drilldown-view

### Bug description

Hi Community,  On clicking the Month, Week, Day, Agenda buttons the rbc-active class is applied to the clicked buttons and the button remains hightlighted. But on clicking Today, Back, Next the button gets hightlighted but when we click outside the button the style gets lost. How can we achieve the same style behaviour for TODAY,NEXT,BACK as it is going for MONTH,WEEK,DAY,AGENDA.

### react-big-calendar version

1.5.2

### React version

16.9.0

### Platform/Target and Browser Versions

113.0.5672.127 (Official Build) (64-bit)

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a react-big-calendar issue and not an implementation issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by 7assenTlili** [comment]
@vivpan24 It doesn't look like a bug to me. This is how it is implemented, the TODAY, NEXT and PREVIOUS button do not have an "active" class, only :focus and :hover styles. 
You can achieve your desired outcome by using a custom toolbar component with a state that tracks the active button.
