### ISSUE TITLE
Console Warning with react strict mode

### ISSUE THREAD

**Issue by sambbaahh** [jquense/react-big-calendar#2417]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/embed/react-big-calendar-example-forked-zvpkpq?fontsize=14&hidenavigation=1&theme=dark

### Bug description

Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code. See https://reactjs.org/link/unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://reactjs.org/link/derived-state

Please update the following components: DayColumn

When I click Week/day, the error appears to console.

Is there anyway to fix this warning? Do I have to care about it?

### Expected Behavior

No errors

### react-big-calendar version

1.8.1

### React version

18.2.0

### Platform/Target and Browser Versions

Windows, Chrome

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a react-big-calendar issue and not an implementation issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by cutterbl** [comment]
This has been reported several times in the past. We are aware of the console warning. This is a warning, from React, that the feature being used will be deprecated in a future version of React. That being said, it is a warning, and does not effect the current function of Big Calendar. The issue will be addressed in a future version of Big Calendar.
