### ISSUE TITLE
Resize doesn't work

### ISSUE THREAD

**Issue by marcellio4** [jquense/react-big-calendar#2421]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/react-big-calendar-example-forked-dc74c6?from-embed

### Bug description

Resize prop doesn't work in Calendar. Here is my setup

          `<section style={{ height: '100vh' }}>
             <DnDCalendar localizer={localizer}
                    events={pickerEvents}
                    draggableAccessor={() => true}
                    onSelectSlot={handleOnSelectSlot}
                    onSelectEvent={handleOnSelectEvent}
                    onEventDrop={handleOnEventDrop}
                    onEventResize={handleOnResize}
                    resizableAccessor={() => true}
                    selectable
                    popup
                    resizable
                    showMultiDayTimes={true}
                    step={15}
                />
          </section>`
            

### Expected Behavior

resizeable should work

### Actual Behavior

in react 18 and higher version is not working. 

### react-big-calendar version

1.8.1

### React version

18.2.0

### Platform/Target and Browser Versions

Chrome

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a react-big-calendar issue and not an implementation issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by cutterbl** [comment]
You forgot to add the DnD stylesheet. See the [DnD Example Codesandbox](https://codesandbox.io/s/react-big-calendar-resizable-example-p6t8z4?file=/src/App.js)
