### ISSUE TITLE
Does Background events have click event?

### ISSUE THREAD

**Issue by sumanth6738** [jquense/react-big-calendar#2422]
I have added few background events represent slots,  that cannot be clicked. Is there a way to detect this (that the user clicked on a background event)

**Comment by cutterbl** [comment]
@sumanth6738 No, there's no additional behavior there. In your other event handlers you would have to test for intersection with a background event. (This may be something for us to consider for our *next* version. You might bring it up in the our `#next` channel in the Slack group)
