### ISSUE TITLE
How can i display just the title event?

### ISSUE THREAD

**Issue by alessiav8** [jquense/react-big-calendar#2438]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://drive.google.com/file/d/14aBey9l9TiW3hCv9IVpqfnB5r7iZxzMb/view?usp=drive_link

### Bug description

How can i display just the title event on the weekly view of the calendar? Right now is visible the title and the time range but i want just the title if possible. And how can i set the size of the container? they are smaller than the range cells 

### react-big-calendar version

1.8.2

### React version

18.2.0

### Platform/Target and Browser Versions

macOs Chrome

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a react-big-calendar issue and not an implementation issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by cutterbl** [comment]
@alessiav8 Going to close this, as it isn't a bug. You can ask these kinds of questions in our [Slack](https://join.slack.com/t/bigcalendar/shared_invite/zt-1ml1j99af-qIvqOfosMog1W7WxM0~j2Q) area.
