### ISSUE TITLE
Maximum update depth exceeded.

### ISSUE THREAD

**Issue by haseebuchiha** [jquense/react-big-calendar#2442]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/trusting-haze-fhdt9x?file=/src/App.js

### Bug description

Using any version above 0.33 results in Maximum update depth exceeded for setState. The docs are showing white screen as well. 

<img width="1789" alt="image" src="https://github.com/jquense/react-big-calendar/assets/19784907/73ce74e3-4c0a-4664-9c84-83ae5eb292c3">

### Expected Behavior

Should show big calendar

### Actual Behavior

Crashes the page

### react-big-calendar version

1.8.2

### React version

18.2.0

### Platform/Target and Browser Versions

Chrome, safari, firefox

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a react-big-calendar issue and not an implementation issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by haseebuchiha** [comment]
Issue was caused because I was using a timespoofing chrome extension. Closing as won't fix.

**Comment by girlboss-energy** [comment]
@haseebuchiha Thanks, you saved me from a big headache!
