### ISSUE TITLE
Slack Community link is broken

### ISSUE THREAD

**Issue by burakgazi** [jquense/react-big-calendar#2453]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://github.com/jquense/react-big-calendar

### Bug description

The link on the readme page as well as link in couple issues are all broken, 

### react-big-calendar version

current

### React version

current

### Platform/Target and Browser Versions

web

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a react-big-calendar issue and not an implementation issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by cutterbl** [comment]
seemed to work for me, just now...

**Comment by burakgazi** [comment]
So can you let me know what I am doing wrong :) 

Please find attached screen recording

https://github.com/jquense/react-big-calendar/assets/17268518/6fed121a-0ca9-4ef4-98e2-8d86dbf3cd08

**Comment by CamiloGarciaLaRotta** [comment]
same broken link for me :/

**Comment by cutterbl** [comment]
@CamiloGarciaLaRotta It's been updated. Try again
