### ISSUE TITLE
View button does not respond when clicked

### ISSUE THREAD

**Issue by xgqfrms** [jquense/react-big-calendar#2455]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/mystifying-paper-xh7mw7?file=%2Fapp%2Fpage.tsx%3A53%2C86

### Bug description

I followed the demo code but the results were not as expected.

https://github.com/jquense/react-big-calendar/blob/master/stories/demos/exampleCode/basic.js

### Expected Behavior

click View button do the right respond as example.

https://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/examples--example-1

### Actual Behavior

View button does not respond when clicked

### react-big-calendar version

1.8.4

### React version

18.2.0

### Platform/Target and Browser Versions

macOS Chrome v118

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a react-big-calendar issue and not an implementation issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by cutterbl** [comment]
You're right. This is a known bug, when using SSR. You must use controlled variables when using SSR.

**Comment by xgqfrms** [comment]
Is there any fix plan or just provide an example using the `control variables`.

**Comment by souravnub** [comment]
you can use state to keep track of the current day and use that in the calendar.. then use onNavigate to set that day

**Comment by danielzeroconsulting** [comment]
> you can use state to keep track of the current day and use that in the calendar.. then use onNavigate to set that day

could you show an example of this implementation?

**Comment by cutterbl** [comment]
@danielzeroconsulting Click the 'Show Code' button on the example in the [onView](https://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/props--on-view) documentation
