### ISSUE TITLE
Unable to add full image

### ISSUE THREAD

**Issue by JessyAngel07** [jquense/react-big-calendar#2467]
I'm using react-native-big-calendar and try to import image in the cell and i got this partial image as result 

 events: [
                {
                    title: '1',
                    start: new Date(2023, 11, 11, 10, 0),
                    end: new Date(2023, 11, 11, 10, 30),
                    isImageTitle: false,
                },
                {
                    title: 'Me',
                    start: new Date(2023, new Date().getMonth(), 11, 10, 0),
                    end: new Date(2023, new Date().getMonth(), 11, 10, 30),
                    isImageTitle: false,

                },

                {
                    title: (<Image
                        source={require('../../assets/images/png/Event.png')}
                        style={[styles.image, { tintColor: CommonColors.black, backgroundColor: CommonColors.green }]}
                        resizeMode='cover'
                    />),
                    start: new Date(2023, 11, 15, 0),
                    end: new Date(2023, 11, 15, 0),
                    isImageTitle: true,

                },
            ],
 this is my event where i try to import image 
![issue](https://github.com/jquense/react-big-calendar/assets/144873346/a42b4c1b-08a2-490b-9fd7-38c89e3fb5c2)
@ogyr @jeanlazarou @sonnyp @tiwatson

**Comment by JessyAngel07** [comment]
and is there any other possible way to add image on cell

**Comment by cutterbl** [comment]
I think you're looking for [this project](https://github.com/acro5piano/react-native-big-calendar). We are not affiliated.
