### ISSUE TITLE
Display event on full calendar [Day & Week view]

### ISSUE THREAD

**Issue by ravigopani** [jquense/react-big-calendar#2476]
### Clear and concise description of the problem

In react big calendar currently showing events something like as below.
![image](https://github.com/jquense/react-big-calendar/assets/4223162/867a2526-e0a4-46e7-8481-525f804e3bbf)
![Capture](https://github.com/jquense/react-big-calendar/assets/4223162/27e4e3c5-e3f9-4733-8155-cbc57286258b)

and somewhere i saw something like as below image. which has look and feel more then what we have currently in react-big-calendar. and  also it has big area to display event so with this it is easy to read event content.
![Screenshot 2023-11-22 at 10 14 00 AM](https://github.com/jquense/react-big-calendar/assets/4223162/75f8fca8-404b-46ff-a666-2be3f03c3acb)

so how to do customization in display events. and also let's say my event start from 10:00 AM and end at 05:00 PM so that event should display as stretched format. means that event should display vertically long in day view.

### Suggested solution

I am looking for that solution as mentioned problem above. please help me out for this.

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples/index.html).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by Berchez** [comment]
It would be interesting to have an option to not have this layout with overlay
