### ISSUE TITLE
Title is undefined when using a Custom View

### ISSUE THREAD

**Issue by krotek20** [jquense/react-big-calendar#2494]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/react-big-calendar-year-view-9jp26s?file=%2Fsrc%2FApp.tsx%3A7%2C1

### Bug description

I am trying to create a calendar that only shown the Year View. The new Custom view is rendered only if the month view is set to true. Otherwise, `Cannot read properties of undefined (reading 'title')` is received. However, writing `views={{ year: YearView, month: true } as any}` solves the issue, but I don't want to display any other view in my app despite my Custom Year View. Weirdly enough, adding day or week view instead of month view won't work.
Note: CSS not provided in codesandbox.

### Expected Behavior

Displaying Custom Views should work without adding month view.

### Actual Behavior

Custom views cannot be displayed without `month: true`

### react-big-calendar version

1.8.6

### React version

18.2.0

### Platform/Target and Browser Versions

Chrome 121.0.6167.86

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a react-big-calendar issue and not an implementation issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by cutterbl** [comment]
When using an object for `views` you either a) enable/disable a view (true/false) or b) define a custom view. The default `view` is the 'month' view, so you must target another view if you're disabling the 'month' view.
```
views={{
  year: CustomYear,
  month: false,
  week: false,
  day: false
}},
view='year'
```
Also remember that, when creating a [Custom View](https://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/guides-creating-custom-views--page) you must define `title()`, `range()`, and `navigate()` methods on your component.
