### ISSUE TITLE
Invalid Slack link in the README file

### ISSUE THREAD

**Issue by totitoti7** [jquense/react-big-calendar#2499]
### Check that this is really a documentation issue

- [X] I confirm

### Reproduction link

https://github.com/jquense/react-big-calendar#

### Documentation mistake description

At the end of the README file in the Join Community section, the link of Slack channel is invalid.

### Expected Behavior

I wanted to join the community on Slack and help improve Big Calendar! 

### Actual Behavior

I expected the link to take me to the Big Calendar Slack Channel

### react-big-calendar version

v1.9.1

### React version

16.14.0

### Platform/Target and Browser Versions

Chrome

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a react-big-calendar issue and not an implementation issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by cutterbl** [comment]
@totitoti7 Thank you for letting us know. Unfortunately Slack invite links have an expiration, so we constantly have to update the link. I've updated the link now, so you should be able to join.

**Comment by totitoti7** [comment]
> @totitoti7 Thank you for letting us know. Unfortunately Slack invite links have an expiration, so we constantly have to update the link. I've updated the link now, so you should be able to join.

Thank you for the update and for taking the time to refresh the Slack invite link. I'll go ahead and join the Slack channel now. Looking forward to engaging with the community there!
