### ISSUE TITLE
Typos in README file

### ISSUE THREAD

**Issue by totitoti7** [jquense/react-big-calendar#2501]
### **While reading the README file I've noticed a minor typo in:** 

1. In the first paragraph, it says "made for modern browsers" which could be rephrased for clarity, perhaps to "designed for modern browsers".
2. In the localization section, it states "you must choose a localizer to use this library". While technically correct, this could be phrased more user-friendly by saying "you need to choose a localizer to use this library".

These are just minor suggestions, and I understand if you prefer to keep the current phrasing. I hope this feedback is helpful nonetheless.

**Comment by cutterbl** [comment]
@totitoti7 I implemented your first suggestion, though I think it's important to keep the verbiage mentioned in the second one, as Big Calendar will error if you don't include a localizer.
