### ISSUE TITLE
Cloning Denied

### ISSUE THREAD

**Issue by bnono2001** [jquense/react-big-calendar#2503]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

n/a

### Bug description

![issue](https://github.com/jquense/react-big-calendar/assets/146487504/2aab6462-bdf5-4b15-9204-f4288c1b699b)

### Expected Behavior

I expected to clone the repository from my VsCode terminal but it did not work out as expected. 

### Actual Behavior

Here's the error :
Cloning into 'react-big-calendar'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
![issue](https://github.com/jquense/react-big-calendar/assets/146487504/9f510a73-6ee4-43c5-990c-47512b760b19)

### react-big-calendar version

latest

### React version

not yet used

### Platform/Target and Browser Versions

Windows 10

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a react-big-calendar issue and not an implementation issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by bnono2001** [comment]
$ git clone git@github.com:jquense/react-big-calendar.git
$ cd react-big-calendar
$ yarn
$ yarn storybook

These commands did not work on my PC, I forked then cloned from my repository, and npm install worked but not yarn, I think the explanation was not clear enough or obvious for a beginner, I would request more details !

**Comment by cutterbl** [comment]
1. Use node >= 18
2. yarn install
3. yarn storybook
