### ISSUE TITLE
Proposal to Translate README into Arabic for Wider Accessibility

### ISSUE THREAD

**Issue by totitoti7** [jquense/react-big-calendar#2511]
### Clear and concise description of the problem

The current README file is available only in English, which may limit accessibility for Arabic-speaking developers who are interested in contributing to or using the project but may not be comfortable with English. As the developer community is global, providing documentation in multiple languages can significantly lower the barrier to entry and foster a more inclusive and diverse community.

### Suggested solution

I propose to create an Arabic translation of the README file, to be named README.ar.md, which will reside alongside the existing English README in the project repository. This translation will ensure that Arabic-speaking users can easily understand the project's purpose, setup, and contribution guidelines, thereby expanding the project's reach and inclusivity.

### Additional context

To ensure the translation remains accurate and up-to-date, I will:
- Regularly check the original README for updates and reflect any changes in the Arabic version.
- Collaborate with other Arabic-speaking contributors to review and improve the translation for accuracy and readability.
I am committed to making this initial translation and maintaining it as part of my contribution to the project. This effort will help bridge language barriers and make the project more accessible to a wider audience.

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples/index.html).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [X] I'm willing to open a PR

**Comment by cutterbl** [comment]
I think it's a great idea. Hopefully we can find contributors willing to submit in other languages as well. I would place it in a 'docs' folder, in the root, and we can add a link in the main README (in Arabic). Look forward to seeing what you submit.
