### ISSUE TITLE
Event menu does not open when clicking on an event

### ISSUE THREAD

**Issue by eeefg650** [jquense/react-big-calendar#2513]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/xenodochial-currying-dxl85n?file=%2Fsrc%2FApp.js%3A19%2C16

### Bug description

When trying to click an event, the menu doesn't open as expected, 
but if I don't use withDragAndDrop, 
then the problem goes away.

Or if i removed the "props.event.children" in EventComponent also the problem goes away.
You can examine the problem in the link I attached.

### Actual Behavior

The menu will show up as expected with - "WithDragAndDrop"

### react-big-calendar version

1.5.2

### React version

18.0.2

### Platform/Target and Browser Versions

chrome 107.0.5304.107

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a react-big-calendar issue and not an implementation issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by cutterbl** [comment]
Apparently I have too many Draft sandboxes to make any changes to see, but...

My guess is you don't have the correct function component definition. You have

```
eventWrapper: (e) => {
            return <EventComponent event={e} />;
          },
```
Where you would need
```
eventWrapper: EventComponent
```
Which would automatically pass all props (including `event`) to the component. Remember that this not the same as a click event, but rather the `event` object from your calendar.

**Comment by eeefg650** [comment]
> Apparently I have too many Draft sandboxes to make any changes to see, but...
> 
> My guess is you don't have the correct function component definition. You have
> 
> ```
> eventWrapper: (e) => {
>             return <EventComponent event={e} />;
>           },
> ```
> 
> Where you would need
> 
> ```
> eventWrapper: EventComponent
> ```
> 
> Which would automatically pass all props (including `event`) to the component. Remember that this not the same as a click event, but rather the `event` object from your calendar.


It still does not work.
I lowered to version 0.40.8 and it works fine
The problem is that it breaks other things for me because it's an old version
