### ISSUE TITLE
All-day solt optional

### ISSUE THREAD

**Issue by liaokaime** [jquense/react-big-calendar#2515]
### Clear and concise description of the problem

![image](https://github.com/jquense/react-big-calendar/assets/27792976/61b297bf-590c-42a6-be78-95dcf099e023)
Not everyone needs to display all-day solt, and there are times when I understand that all-day events will never occur, so it becomes a useless white space taking up space

### Suggested solution

Add a parameter "showAllDay"，true or false, default true.

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples/index.html).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by cutterbl** [comment]
Maybe not the answer that you want, but (for now) you can always override the `.rbc-allday-cell` class, setting it to `display:none`

**Comment by liaokaime** [comment]
The way you said it works, and in fact that's what I did. But this means that users need to understand how the internal layout of react-big-calendar works, and I just think that for a library, the less the outside knows about the internal implementation details, the better

**Comment by cutterbl** [comment]
@liaokaime True. I'll put this on the feature request board for 'next' version.
