### ISSUE TITLE
Custom View Issues with TimeGrid

### ISSUE THREAD

**Issue by qpjs** [jquense/react-big-calendar#2518]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/react-big-calendar-example-forked-q8gyf3

### Bug description

I created a custom TwoWeekView based on the example here: https://jquense.github.io/react-big-calendar/examples/index.html?path=/story/guides-creating-custom-views--page

(I also added some colorization to the weekends... would like to do this only for my custom view, but dayPropGetter seems only to work at the Calendar level.)

I have a few issues:

1. The time of day column on the left-hand side of the view does not show. 
2. The 30 min incremental sections on the days do not show.
3. Time periods within the days cannot be selected.
4. Regardless of when the events are within the day they are always shown at the top of the day column.

### Expected Behavior

I would expect that expanding to two weeks wouldn't fundamentally change the TimeGrid view behavior.

### Actual Behavior

Elements of the TimeGrid view behavior no longer work, mostly around time of day rendering and interactions.

### react-big-calendar version

latest

### React version

18.2.0

### Platform/Target and Browser Versions

Windows, Linux, MacOS with Chrome and Safari 

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a react-big-calendar issue and not an implementation issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by qpjs** [comment]
Oh yeah, another item... I can't seem to figure out how to add a new navigation button to the list of Views. I'd like to be able to call it 'Two Week' instead of using the 'Work Week'.

**Comment by cutterbl** [comment]
@qpjs This isn't a bug in the library, but an issue with your implementation. You should really ask these things within our Slack community or on StackOverflow. 

Big Calendar is complex, but our documentation is extensive.

You'd have to follow the chain in the render process in Dev Tools/React Tools. [There is an example](https://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/examples--example-9) for something similar (custom view with specific range) that includes a link to it's code. I would copy that code and make adjustments for your custom view.

As far as selection is concerned, you do need the [selectable](https://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/props--selectable) prop, as well as your event handlers. There are a lot of examples in the documentation. 

The 'Work Week' button text replacement is a little harder to find. You have to replace that in the [messages](https://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/props--messages) prop. You don't have to replace the entire object, just the keys you're trying to target.
