### ISSUE TITLE
Agenda view customizations

### ISSUE THREAD

**Issue by eduardolbruno** [jquense/react-big-calendar#2519]
Hi lads,

Firstly I want to thank you for this amazing calendar plugin. Works really good and I really like it.

I am using the plugin in 2 sections of a project. My question goes for the "Agenda" view of the Calendar, and know if its possible to make some customizations of it. 
For ex: 

- Is it possible to add an image when no events are loaded? I know I can change the default text, but can I add some extra complexity ? (like adding a button or an image on it) 
![image](https://github.com/jquense/react-big-calendar/assets/111282091/f491271d-57a2-4fe4-9153-bb1de4bca3fc)

- I am trying to customize the Event column. I added a title and a text related to the event of that day, and its displaying correctly. I also made some styling changes and its really easy to setup. However, I was wondering if I could get some info of the actual row (day/time) that is rendered on the Agenda view but on the Event column. So then, I could show some especific info related of the actual row rendered. 

For example, in the Event column I could add a text that shows when the event is starting-finishing. Or toggle some info related to that same day displayed. Is it possible to do something like this?
![image](https://github.com/jquense/react-big-calendar/assets/111282091/478d970e-ff9b-419b-a39c-b4f321c41b29)

If someone has any idea how to do it, or maybe there is a specific prop for doing this, and you could point me into the right direction that'd be great!

Cheers!

**Comment by cutterbl** [comment]
@eduardolbruno These sort of questions are really best done in our Slack group or on StackOverflow.

I did a test locally, and though kind of a hack, I was able to do this for the 'no events' message

```
const CustomAgendaNoEvents = () => <div>Custom No Events</div>

const messages = {
  noEventsInRange: CustomAgendaNoEvents()
}

<Calendar messages={messages} ...
```
Now, this renders my `CustomAgendaNoEvents` in the span with the `rbc-agenda-empty` class, so you'll have to handle that.

Custom Agenda Event [components](https://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/props--components) are possible. By default, only the event `title` is displayed. But if you provide an Agenda specific Event display component it will be used, receiving the `event` and `title` as props (and no other props)

**Comment by eduardolbruno** [comment]
> @eduardolbruno These sort of questions are really best done in our Slack group or on StackOverflow.
> 
> I did a test locally, and though kind of a hack, I was able to do this for the 'no events' message
> 
> ```
> const CustomAgendaNoEvents = () => <div>Custom No Events</div>
> 
> const messages = {
>   noEventsInRange: CustomAgendaNoEvents()
> }
> 
> <Calendar messages={messages} ...
> ```
> 
> Now, this renders my `CustomAgendaNoEvents` in the span with the `rbc-agenda-empty` class, so you'll have to handle that.
> 
> Custom Agenda Event [components](https://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/props--components) are possible. By default, only the event `title` is displayed. But if you provide an Agenda specific Event display component it will be used, receiving the `event` and `title` as props (and no other props)

Thanks for your quick answer!
Sure, next time I will leave my question on StackOverflow, no worries. 

BTW your hack it works, but _noEventsInRange_ shows an error as it is defined with a string type.

Thanks also for the Custom Agenda event component explanation!

**Comment by cutterbl** [comment]
@eduardolbruno Yeah, the project doesn't manage our TS types (currently). That's handled by an outside entity. I'm only now digging into Big Calendar TS with some pre-work for 'next'.
