### ISSUE TITLE
Incorrect events appearance after navigation back & next

### ISSUE THREAD

**Issue by destimon** [jquense/react-big-calendar#2529]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://jquense.github.io/react-big-calendar/examples/iframe.html?id=addons-drag-and-drop--example-1&viewMode=story

### Bug description

I faced problem which I also can reproduce on some of your examples (e.g. - https://jquense.github.io/react-big-calendar/examples/iframe.html?id=addons-drag-and-drop--example-1&viewMode=story)

https://github.com/jquense/react-big-calendar/assets/28014303/ba59c052-a25f-49c2-9307-c6d3510f576b

Steps:

- Switch to "Week" mode
- Click "Back" or "Next" navigation button
- Click another navigation button "Back" or "Next" to return back to previous week

It also can be fixed by clicking on any event. Looks like initially it calculates "top" property wrongly, and after click it re-calculates to correct value

Could you please help to understand whether it's expected or not? Thank you, your component is very nice!

### Expected Behavior

Events should be displayed 1:1 as it was before navigation next+back or back+next

### Actual Behavior

Events shifted straight to the bottom/top(depends what navigation button clicked)

### react-big-calendar version

1.11.1

### React version

18

### Platform/Target and Browser Versions

macOS+Chrome(122.0.6261.94) and Windows 10+Chrome(122.0.6261.94)

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a react-big-calendar issue and not an implementation issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by destimon** [comment]
Update: I've spotted that the same thing happens in "Day" view. While for "Month" view it's okay

**Comment by forceddd** [comment]
I found the same problem, and I created a [pr](https://github.com/jquense/react-big-calendar/pull/2532). I hope this helps you.

**Comment by destimon** [comment]
@forceddd Thank you, it works for me now. Great job!
