### ISSUE TITLE
ERROR in ./node_modules/react-big-calendar/dist/react-big-calendar.esm.js 6:0-62

### ISSUE THREAD

**Issue by peterzanetti** [jquense/react-big-calendar#2533]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

n/a

### Bug description

On a fresh install of react-big-calendar and rendering with the most basic example, I am immediately getting this error and it won't render. Please assist.

Module not found: Error: Package path ./helpers/esm/callSuper is not exported from package ../node_modules/@babel/runtime

### Expected Behavior

Renders the calendar

### Actual Behavior

Fails

### react-big-calendar version

1.11.2

### React version

18.2.0

### Platform/Target and Browser Versions

macOS

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a react-big-calendar issue and not an implementation issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by arepp23** [comment]
Having the same issue on a next.js 14.0.3 typescript app with node 18.17.0

**Comment by TarasPotsikaylo** [comment]
Having the same issue on a react typescript 18.2.0 app with node 18.13.0

**Comment by dcrec1** [comment]
Same here.

**Comment by Jobin-S** [comment]
same here react `^17.0.2`

**Comment by Jobin-S** [comment]
`npm i @babel/runtime`

Running this has fixed this issue. But the style (CSS) is not loading

<img width="818" alt="image" src="https://github.com/jquense/react-big-calendar/assets/63976083/1e52c054-7dea-4a59-9e23-a60087c04369">

**Comment by Jobin-S** [comment]
@peterzanetti  do you find any alternative? I have to submit the calendar event today. feked up :(

**Comment by qujunxian** [comment]
@Jobin-S You can lower the version to 1.8.7 to temporarily solve this problem  :)

**Comment by marcocinus91** [comment]
I had the same problem. Update to the latest version of @babel/runtime, then update Big Calendar. Check if another @babel directory exists inside your react-big-calendar directory and delete it.

**Comment by sethmcleod** [comment]
Looks like this was introduced in [v1.10.1](https://github.com/jquense/react-big-calendar/releases/tag/v1.10.1) with the updates to yarn.lock

**Comment by Ladvace** [comment]
same problem here, did you find any solution?

**Comment by cutterbl** [comment]
Please see @marcocinus91 comment above for the solution to this issue.

**Comment by joeplaa** [comment]
I solved it by adding `"@babel/runtime": "^7.24.6"` to the resolutions. When running `yarn install`, it removed duplicate (stale) entries. After that I removed the "resolution" and it still works.

```json
"resolutions": {
  "@babel/runtime": "^7.24.6"
},
```

**Comment by Rezaraki** [comment]
> `npm i @babel/runtime`
> 
> Running this has fixed this issue. But the style (CSS) is not loading
> 
> <img alt="image" width="818" src="https://private-user-images.githubusercontent.com/63976083/317350377-1e52c054-7dea-4a59-9e23-a60087c04369.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2ODI1NDAsIm5iZiI6MTcyOTY4MjI0MCwicGF0aCI6Ii82Mzk3NjA4My8zMTczNTAzNzctMWU1MmMwNTQtN2RlYS00YTU5LTllMjMtYTYwMDg3YzA0MzY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDExMTcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwYTIxY2U5OWRmOTFkOThjYzRjMjEzMTA3YzM4MWU3ZDI4YjFmMjgyNjUzZGZhMDNiOTg4YTQ4MGFiZWUxM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.A1erPlXRYcWN0mRqJHizXtxKzQO1acTTbZeaSfGMckg">

importing the styles as stated [here ](http://jquense.github.io/react-big-calendar/examples/?path=/docs/guides-custom-styling--page)fixed this
