### ISSUE TITLE
Incorrect date passed to onSelectSlot (and onSelecting)

### ISSUE THREAD

**Issue by KoflerStefan** [jquense/react-big-calendar#2536]
### Check that this is really a bug

- [x] I confirm

### Reproduction link

https://jquense.github.io/react-big-calendar/examples/iframe.html?id=examples--example-2&viewMode=story

### Bug description

Was able to reproduce issue on the public example. When selecting a timeslot the onSelectSlot and onSelecting methods receive the wrong date (only time is correct). It seems like the date-part is still from the last selection and not updated correctly. This bug was newly introduced with version 1.11.2 (1.11.1 this did still work as expected).

Viedeo recorded from the [public event creation example](https://jquense.github.io/react-big-calendar/examples/iframe.html?id=examples--example-2&viewMode=story):

https://github.com/jquense/react-big-calendar/assets/73938805/c29dec04-c59b-4cc8-8146-e9be450cb2e7

### Expected Behavior

Correct date is reflected in onSelectSlot/onSelecting

### Actual Behavior

Only selected time is correct, selected date is incorrect (last selected date instead of current one)

### react-big-calendar version

1.11.2

### React version

17

### Platform/Target and Browser Versions

Ubuntu 20.04 - Brave(121.1.62.165) and Firefox(123.0.1)

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a react-big-calendar issue and not an implementation issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by KoflerStefan** [comment]
Had to go back to 1.11.0 - this fixes this issue and also the one introduced with 1.11.1 (#2529)

**Comment by forceddd** [comment]
Thank you for raising the issue. I have created a [PR](https://github.com/jquense/react-big-calendar/pull/2545) for this issue. I think this issue will be fixed in the next version.

**Comment by forceddd** [comment]
> the problem i have in week view is that the date is always saturday ! the hour is correct but the date wherever i click is Saturday ! not fixed with version 1.11.3

yes，i know. Try version 1.11.1

**Comment by susosamuel** [comment]
I think that this is already fixed. We are using `^1.11.6` and we are not experiencing the issue anymore

**Comment by forceddd** [comment]
@KoflerStefan @goldfishers @susosamuel @meriemMat This issue has been fixed in version 1.11.6
