### ISSUE TITLE
Wrong possition for current time indicator

### ISSUE THREAD

**Issue by yannickfh** [jquense/react-big-calendar#2539]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/props--view

### Bug description

The current time indicator isn't shown (top position isn't updated). This is probably related to this fix:
[https://github.com/jquense/react-big-calendar/pull/2532](https://github.com/jquense/react-big-calendar/pull/2532)

### react-big-calendar version

1.11.2

### React version

18.2.0

### Platform/Target and Browser Versions

all platforms

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a react-big-calendar issue and not an implementation issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by forceddd** [comment]
@yannickfh @cutterbl This bug is resolved in [PR 2545](https://github.com/jquense/react-big-calendar/pull/2545)
