### ISSUE TITLE
Node modules manipulation for custom week view

### ISSUE THREAD

**Issue by rahulk1505** [jquense/react-big-calendar#2540]
### Clear and concise description of the problem

Can I modify node modules of time grid header.js file to swap resources with date i.e displaying dates and all resources under date? 

### Suggested solution

Please suggest any solution for this feature 

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples/index.html).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by cutterbl** [comment]
We provide the ability to trade out any view with a custom view. This is a long standing feature request, we just haven't had anyone file a PR for it. Biggest issue, in creating this view, is adjusting the layout algorithm to support it. I haven't looked too deep, but I imagine it would use similar logic to how we layout a 'week' in the month view.

I am closing this, as we have multiple issues for the same request

**Comment by rahulk1505** [comment]
Thank you for your quick response....
