### ISSUE TITLE
CSS inside the component

### ISSUE THREAD

**Issue by marcocinus91** [jquense/react-big-calendar#2541]
### Clear and concise description of the problem

Im' trying to set display: none for the .rbc-overlay. If I write this code inside a css file, it works, but i need it inside my component without importing the external css.

### Suggested solution

I have not idea

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples/index.html).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by cutterbl** [comment]
Please use 'Issues' for filing Bug Reports or Feature Requests. Questions on implementation should utilize our Slack channels or StackOverflow.
