### ISSUE TITLE
Limit events shown per day in calendar (Month view)

### ISSUE THREAD

**Issue by jingoldsby** [jquense/react-big-calendar#2542]
I am building a calendar that has multiple events per day, and I want to limit the events to only show one event per day, and the rest of the events displayed using the “show more” function. Is this possible by editing the stylings? I have played around with the heights but haven’t been able to find a solution

**Comment by cutterbl** [comment]
Please use 'Issues' for Bug Reports and Feature Requests. All questions of implementation should be directed to our Slack channels or StackOverflow.
