### ISSUE TITLE
onNavigate Link Not Functioning Correctly in Date Documentation

### ISSUE THREAD

**Issue by ikrammt** [jquense/react-big-calendar#2556]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

http://jquense.github.io/react-big-calendar/examples/?path=/docs/props--cal-date

### Bug description

<img width="944" alt="Screenshot 2024-04-04 at 11 10 28 PM" src="https://github.com/jquense/react-big-calendar/assets/145692307/7e6426f8-8af7-4b1a-a730-4ead8be793ba">

The "onNavigate" link within the date documentation appears to be dysfunctional. Clicking on the link does not lead to the expected destination or action.

### Expected Behavior

Clicking on the "onNavigate" link should navigate users to the appropriate location within the documentation  as indicated [here](http://jquense.github.io/react-big-calendar/examples/?path=/docs/props--on-navigate).

### Actual Behavior

https://github.com/jquense/react-big-calendar/assets/145692307/a7772dd9-fbfb-436d-9b2e-d17f24ee7d87

### react-big-calendar version

1.11.3

### React version

18.2.0

### Platform/Target and Browser Versions

macOS

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a react-big-calendar issue and not an implementation issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by yuiji** [comment]
This seemed like a good first issue. So I opened PR for that. Also I fixed other links that not working. For example links in onSelectSlot, onSelecting, selected, view pages.
