### ISSUE TITLE
Keydown triggers the selectDates function

### ISSUE THREAD

**Issue by yuiji** [jquense/react-big-calendar#2557]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

n/a

### Bug description

First double click on the slot, then click on a slot and finally press any key on the keyboard. This triggers the selectDates function and causes an error. 

Here is the demo:

https://github.com/jquense/react-big-calendar/assets/62891039/16e2d88c-b277-4475-aca1-6f2dc1145955

I think this problem is caused by the _handleTerminatingEvent function, the keydown event listener is added for the escape key, but there is no control for other keys, so it emits the select event when other keys are pressed.

https://github.com/jquense/react-big-calendar/blob/72a01478da2f0694ee2a3a4f1d2c1281ad8effc0/src/Selection.js#L340-L373

https://github.com/jquense/react-big-calendar/blob/72a01478da2f0694ee2a3a4f1d2c1281ad8effc0/src/Selection.js#L302-L305

### react-big-calendar version

1.11.2

### React version

18.2

### Platform/Target and Browser Versions

macOS

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a react-big-calendar issue and not an implementation issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by forceddd** [comment]
@yuiji Does this issue still exist on version 1.11.3? I have not been able to successfully reproduce this error.

**Comment by yuiji** [comment]
@forceddd  I checked again and this issue does not exist on version 1.11.3. I think this PR (https://github.com/jquense/react-big-calendar/pull/2551) solves this issue, right?

**Comment by forceddd** [comment]
@yuiji Yes, that's what it looks like right now.
