### ISSUE TITLE
onSelectSlot not returning doubleClick slotInfo objects

### ISSUE THREAD

**Issue by joggjogg** [jquense/react-big-calendar#2565]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/react-big-calendar-doubleclick-bug-v4qp78?file=%2Fsrc%2FApp.tsx%3A8%2C1

### Bug description

The onSelectSlot prop is no longer returning slotInfo objects caused by a double click. 

### Expected Behavior

When the selectable prop is true, and I double click on a slot in the calendar, I expect onSelectSlot to return a slotInfo object where `slotInfo.action == 'doubleClick'`

### Actual Behavior

I double click on a slot in the calendar and recieve two slotInfo objects where `slotInfo.action == 'click'`

### react-big-calendar version

1.11.3

### React version

18.2.0

### Platform/Target and Browser Versions

macOS Safari 17.4.1 

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a react-big-calendar issue and not an implementation issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by cutterbl** [comment]
There were some issues with Selection accidentally introduced in 1.11.0. Update to 1.11.6 and you should be fine.

**Comment by joggjogg** [comment]
Hi @cutterbl . I've updated to 1.11.6 and and I'm unfortunately experiencing the same bug.

**Comment by forceddd** [comment]
@joggjogg This [commit](https://github.com/jquense/react-big-calendar/pull/2571) was created to fix [#2565](https://github.com/jquense/react-big-calendar/issues/2565).Please pay attention to the status of this [PR](https://github.com/jquense/react-big-calendar/pull/2571).
