### ISSUE TITLE
warning ..\..\package.json: No license field

### ISSUE THREAD

**Issue by nourbenamor201** [jquense/react-big-calendar#2577]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

![image](https://github.com/jquense/react-big-calendar/assets/146487504/6583894b-6db1-413a-9c1b-72a8b3b719a2)

### Bug description

After forking the project and doing its setup locally, after typing "yarn storybook" on the command line (the next step after setting up "yarn" was done successfully), it shows me this warning:
`warning ..\..\package.json: No license field`
![image](https://github.com/jquense/react-big-calendar/assets/146487504/6688e600-5eab-44a6-a1c8-5e66c91b4fea)

The project runs successfully though.

![image](https://github.com/jquense/react-big-calendar/assets/146487504/15e19759-6e2a-4273-a7a6-ab2c9cb87fdf)

### Actual Behavior

![image](https://github.com/jquense/react-big-calendar/assets/146487504/6583894b-6db1-413a-9c1b-72a8b3b719a2)

### react-big-calendar version

1.12.0

### React version

17.0.2

### Platform/Target and Browser Versions

Microsoft Edge

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a react-big-calendar issue and not an implementation issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by cutterbl** [comment]
That is interesting. Must be a bug with Storybook, as `"license": "MIT"` is definitely in the package.json file
