### ISSUE TITLE
swap resource and day header in week view.

### ISSUE THREAD

**Issue by MehdiGR** [jquense/react-big-calendar#2592]
Hi i hope you're good  any one have solved problem of swap resource and day header in week view  ?

![react-big-calendar_swap](https://github.com/jquense/react-big-calendar/assets/67739986/c5658c1e-9658-4af1-b64a-e38d5e6dfc84)

**Comment by cutterbl** [comment]
@MehdiGR If they have, they haven't submitted a PR for it yet. We do have this, already, in our feature request backlog. I will note your vote for it and close this duplicate request.
