### ISSUE TITLE
When pass resizableAccessor=true, and draggableAccessor=false, than resizable is not working

### ISSUE THREAD

**Issue by Chirag-kalsariya** [jquense/react-big-calendar#2612]
When pass resizableAccessor=true, and draggableAccessor=false, then resizable is not working. But, When I pass resizableAccessor=false, and draggableAccessor=true, then draggable is working fine.

resizableAccessor=true, and draggableAccessor=false
In this case there is no pipe ( || ) is showing for make task resizable.

Here is codesandbox link for preview the bug (I don't know it's bug or I am missing something)

[https://codesandbox.io/s/react-big-calendar-drag-and-drop-forked-qmlfsy?file=/src/App.js](https://codesandbox.io/s/react-big-calendar-drag-and-drop-forked-qmlfsy?file=/src/App.js)

**Comment by geraldhoxha95** [comment]
<img width="937" alt="Screenshot 2024-07-11 at 8 14 47 PM" src="https://github.com/user-attachments/assets/fa411a66-ca8d-4805-b7b6-f79ff76fa5e2">
@Chirag-kalsariya according to the documentation, in order for an event to be resizable, it needs to be draggable.

**Comment by Chirag-kalsariya** [comment]
Okay got your point.
