### ISSUE TITLE
Error "Super expression must either be null or a function"

### ISSUE THREAD

**Issue by wyxcoder** [jquense/react-big-calendar#2615]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

...

### Bug description

I got the below error when add the calendar component. I am wondering if this is next.js 13 related? And when this can be fixed?

  1 | import setPrototypeOf from "./setPrototypeOf.js";
  2 | function _inherits(t, e) {
> 3 |   if ("function" != typeof e && null !== e) throw new TypeError("Super expression must either be null or a function");
    | ^
  4 |   t.prototype = Object.create(e && e.prototype, {
  5 |     constructor: {

### react-big-calendar version

latest

### React version

19.0.0-rc

### Platform/Target and Browser Versions

Chrome

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a react-big-calendar issue and not an implementation issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by cutterbl** [comment]
I have no idea what this is. No stack trace, no CodeSandbox reproduction. Impossible to know the root cause without more information.

**Comment by wyxcoder** [comment]
use code error.

**Comment by ChromeGG** [comment]
@wyxcoder 
How did you solve it? I faced the same issue :)

**Comment by AdrianRamiro** [comment]
@ChromeGG very likely related to https://stackoverflow.com/questions/74614922/super-expression-must-either-be-null-or-a-function-nextjs-13

Add `'use client'` to the loading page
