### ISSUE TITLE
Make ResourceID available in dayPropGetter

### ISSUE THREAD

**Issue by limzyishere** [jquense/react-big-calendar#2634]
### Clear and concise description of the problem

I am using employees (resources) for the calendar and for days where the employee is not working, i would like to be able to have them remain in the calendar View, however their class="rbc-events-container" Column be shaded slightly darker so that the user knows that this employee is actually not working.

having the resourceID available would allow me to style each column individually depending on conditions.

### Suggested solution

having the resourceID available would allow me to style each column individually depending on conditions.

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples/index.html).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by cutterbl** [comment]
Done. New [documentation](https://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/props--day-prop-getter) available
