### ISSUE TITLE
Id type are missing

### ISSUE THREAD

**Issue by MariuzM** [jquense/react-big-calendar#2635]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/react-big-calendar-example-v9wdyd?file=/src/App.js

### Bug description

In examples there is use of Id prop but type is missing in Event, any chance for this to get updated? 

### Expected Behavior

id type should be included in type definition

### react-big-calendar version

1.13.1

### React version

react 19 + react compiler

### Platform/Target and Browser Versions

mac

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a react-big-calendar issue and not an implementation issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by luizv** [comment]
I just bumped into the same problem, trying to reproduce some examples.
