### ISSUE TITLE
TimeGrid is not exported properly.

### ISSUE THREAD

**Issue by niranjan821** [jquense/react-big-calendar#2642]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/react-big-calendar-example-forked-lcvttq?file=%2Fsrc%2FWeek.js%3A3%2C47

### Bug description

I tried named importing TimeGrid component and rendering it, but I'm getting the following error.

Cannot read properties of undefined (reading 'defaultProps'). Basically TimeGrid is not exported.

When I import it like this it works.
import TimeGrid from 'react-big-calendar/lib/TimeGrid'; 

### Expected Behavior

The TimeGrip should be exported.

### Actual Behavior

TimeGrip component is not exported

### react-big-calendar version

1.13.3

### React version

17.0.0

### Platform/Target and Browser Versions

Chrome

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a react-big-calendar issue and not an implementation issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by cutterbl** [comment]
You are correct. We don't export any of the Calendar components, providing them in the `/lib`. That pattern was established long before I came to the project, but it's a well established pattern for projects of this size, and there's solid reasoning to the 'why' it was done.

This is not a bug, and is documented in the code examples for [Creating a Custom View](https://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/guides-creating-custom-views--page). I will add a personal task for expanding the documentation detail around the `/lib` folder.
