### ISSUE TITLE
Spanning Multiple Resources 

### ISSUE THREAD

**Issue by fluidpb** [jquense/react-big-calendar#2649]
### Clear and concise description of the problem

I have event that take up 2 courts, is there a way to make it so the event spans 2 courts vs individually?

![Screenshot 2024-09-11 at 9 40 04 PM](https://github.com/user-attachments/assets/9a723838-cf6c-4afa-b63d-d902fd7decdb)

### Suggested solution

N/A

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples/index.html).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by cutterbl** [comment]
Events shared by multiple resources will not span across resources, but be displayed individually within each.
