### ISSUE TITLE
New slack link please

### ISSUE THREAD

**Issue by jermin2** [jquense/react-big-calendar#2656]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

NA

### Bug description

NA

### react-big-calendar version

NA

### React version

NA

### Platform/Target and Browser Versions

NA

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a react-big-calendar issue and not an implementation issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by davidbattalion** [comment]
also waiting for a slack link

**Comment by dludemann** [comment]
Also waiting for slack link

**Comment by milkman4** [comment]
also waiting for slack link!

**Comment by cutterbl** [comment]
Done
