### ISSUE TITLE
Showing two 1AM slots in current week/day view for 'Europe/London' time-zone. 

### ISSUE THREAD

**Issue by kml-rohillaa** [jquense/react-big-calendar#2672]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/react-big-calendar-example-forked-w33qw4?file=%2Fsrc%2FApp.js

### Bug description

Use 'Europe/London' as the timezone. And set current date as the default date. You will see two 1AM slots in timeGutter for sunday. This is creating confusion for events. How can we fix this 
<img width="550" alt="Screenshot 2024-10-28 at 8 17 11 PM" src="https://github.com/user-attachments/assets/aa7e5c77-64d4-4abd-b93a-11548fea68d3">

### Expected Behavior

It should show just one 1AM slot. 

### Actual Behavior

It is showing two 1AM slots.

### react-big-calendar version

1.15.0

### React version

18.2.0

### Platform/Target and Browser Versions

All browsers

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a react-big-calendar issue and not an implementation issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by cutterbl** [comment]
Makes sense, as it's DST for Europe/London timezone in 2024. Hoping to do this better in 'next' version of the component.
