### ISSUE TITLE
Typescript timeSlotWrapper has no defined prop type

### ISSUE THREAD

**Issue by goskan93** [jquense/react-big-calendar#2695]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

.

### Bug description

interface for components looks like this 
```
export interface Components<TEvent extends object = Event, TResource extends object = object> {
    event?: React.ComponentType<EventProps<TEvent>> | undefined;
    eventWrapper?: React.ComponentType<EventWrapperProps<TEvent>> | undefined;
    eventContainerWrapper?: React.ComponentType | undefined;
    dateCellWrapper?: React.ComponentType<DateCellWrapperProps> | undefined;
    dayColumnWrapper?: React.ComponentType | undefined;

    timeSlotWrapper?: React.ComponentType | undefined;
   ... and so on
}
```
the time slot wrapper has no component props defined

"@types/react-big-calendar": "^1.16.0",

### Expected Behavior

Expecting to get access  to the props.

### react-big-calendar version

 1.16.3

### React version

18.2.0

### Platform/Target and Browser Versions

windows 11

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a react-big-calendar issue and not an implementation issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by cutterbl** [comment]
At this time all TS types are managed directly by [DefinitivelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped). Changes to TS types must be submitted there, as the Big Calendar team does not manage them.
