### ISSUE TITLE
Typescript components has no defined children prop in types

### ISSUE THREAD

**Issue by goskan93** [jquense/react-big-calendar#2696]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

.

### Bug description

interfaces and types for component props has no defined `children` property

"@types/react-big-calendar": "^1.16.0",
 

### react-big-calendar version

1.16.3

### React version

18.2.0

### Platform/Target and Browser Versions

windows 11

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a react-big-calendar issue and not an implementation issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by cutterbl** [comment]
At this time all TS types are managed directly by [DefinitivelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped). Changes to TS types must be submitted there, as the Big Calendar team does not manage them.
