### ISSUE TITLE
Uncaught Error: Invariant Violation: Uncontrolled(Calendar).render():

### ISSUE THREAD

**Issue by macejmic** [jquense/react-big-calendar#3]
Hi!

I'm trying to implement your component to the my project but I'm receiving one error all the time.

````
render: ->
  <BigCalendar />
````

Uncaught Error: Invariant Violation: Uncontrolled(Calendar).render(): A valid ReactComponent must be returned. You may have returned undefined, an array or some other invalid object.

Do you have some idea how to solve this or maybe an idea why I'm getting this kind of error?

Thank you very much!

**Comment by macejmic** [comment]
I'm trying figure out why I'm getting this error, for example:

````
calendar = <BigCalendar />

console.log calendar

# ReactElement {key: null, ref: null, _owner: ReactCompositeComponentWrapper, _context: Object, _store: Object}

````

So this looks like that in calendar variable is valid react element but maybe somewhere inside your component is some problem. What do you think?

**Comment by jquense** [comment]
Hey there, I am looking into it. but these sort of issues indicate something not handling imports correctly which suggests taht your build is at fault...

How are you importing the calendar?

**Comment by macejmic** [comment]
````
BigCalendar = require('react-big-calendar');
moment      = require('moment');

BigCalendar.setLocalizer(
  BigCalendar.momentLocalizer(moment)
);
`````

**Comment by jquense** [comment]
Unfortunately I can't repo this, so I am kind of at the end of my ability to troubleshoot the issue.

you can set some breakpoints around and see whats going on, but it seems like browserify is doing something odd to the package.

if you `console.log BigCalendar.ControlledComponent` do you get anything?

if you look at the render method in the uncontrollable package (a dep of react-big-calendar) where the error is actually occurring can you follow the stack trace back up to see where something is going wrong?

**Comment by macejmic** [comment]
````
console.log BigCalendar.ControlledComponent

application.js:99644(props, context, updater) {
      // This constructor is overridden by mocks. The argument is used
      // by mocks to assert on what gets mounted.

      if ("development" !== 'production')…

````

**Comment by jquense** [comment]
yeah so it doesn't look like anything is wrong with the files themselves.

I would try and follow the stacks to the main issue to pin it down. If you do end up finding something wrong with this package please let me know I will fix it quickly

**Comment by macejmic** [comment]
Ok. I'll let you know.
