### ISSUE TITLE
Suggestion to evaluate click as a smallest selection

### ISSUE THREAD

**Issue by haaragh** [jquense/react-big-calendar#5]
Hello! I am testing the calendar in own project.Thank you for your work.

In the week and day views while dragging the mouse we get a selected area which gives as **slotInfo** object, whereas mouse click does not do same thing. In case there was not prior selection dayslot does not hold **slotInfo** in its inner state. If there was a selection made, clicking will refer to that same selection's data as **slotInfo** (no matter where I click, obviously since in DaySlot state holds it, and click refers to this.state ).
```js
...
selector
      .on('select', () => {
        this._selectSlot(this.state)
        this.setState({ selecting: false })
      })
...
```
 It would be (imo) helpful to treat click as a smallest selection according to the slot where clicking was made, and like in selection set info to inner state.

**Comment by jquense** [comment]
ya that seems like a weird bug, I'll see what I can do. thanks
