### ISSUE TITLE
Toolbar Labels not passed down in props

### ISSUE THREAD

**Issue by rafsoaken** [jquense/react-big-calendar#8]
Thank you for this great component!
We are using it for a project that needs german labels. I could only get the german Toolbar labels (Today, Month, Week, ...) to work by including this Code in Calendar.jsx, so it passes the messages props to the Toolbar Component:

    diff --git a/src/Calendar.jsx b/src/Calendar.jsx
    index 6f79088..8bfb2b5 100644
    --- a/src/Calendar.jsx
    +++ b/src/Calendar.jsx
    @@ -276,6 +276,7 @@ let Calendar = React.createClass({
             label={viewLabel(current, view, formats, culture)}
             onViewChange={this._view}
             onNavigate={this._navigate}
    +        messages={this.props.messages}
           />
         }

Did I overlook something or is this a bug?
Thanks

**Comment by jquense** [comment]
looks like a bug! mind sending a PR? thanks

**Comment by rafsoaken** [comment]
PR sent.
